### ISSUE TITLE
docs: matrix example uses same image for all jobs

### ISSUE THREAD

**Issue by lazka** [actions/setup-python#109]
The example at https://docs.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#excluding-a-version describes how to run code on various Python versions and operating systems but always runs the jobs in ubuntu.

`runs-on: ubuntu-latest` should be `runs-on: ${{ matrix.os }}`

(It's not really clear where to report this doc bugs to, sorry)

**Comment by konradpabjan** [comment]
I'll work on updating this!

Thanks for bringing this up

**Comment by lazka** [comment]
@konradpabjan thanks!
