### ISSUE TITLE
`pip install`ing PyYAML crashes the Action running

### ISSUE THREAD

**Issue by jameshiebert** [actions/setup-python#114]
**Describe the bug**
`pip install`ing a version of PyYAML which is not the version being used to run the workflow causes the workflow runner to crash on subsequent steps.

```
2020-07-15T21:47:13.5356959Z FileNotFoundError: [Errno 2] No such file or directory: '/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/PyYAML-5.3.1-py3.7-linux-x86_64.egg'
2020-07-15T21:47:13.5916339Z ##[error]Process completed with exit code 1.
```

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**
3.7.8

**To Reproduce**
1. Run a workflow [e.g. this one](https://github.com/jameshiebert/action/runs/875331441?check_suite_focus=true) that `pip installs` some version of PyYAML
1. On my workflow, scroll down to "Install Conflicting PyYAML"
1. Notice the FileNotFoundError which is *not* from execution of my workflow.
1. Notice that the "Do Something Else" step is not run.

**Run/Repo Url**
https://github.com/jameshiebert/action/runs/875331441?check_suite_focus=true

**Additional context**
I guess the right (?) way to work around this is to install everything in a virtual environment (as shown in the [following commit](https://github.com/jameshiebert/action/runs/875350732?check_suite_focus=true)), but:

1. There's nothing in the [README](https://github.com/marketplace/actions/setup-python#setup-python-v2) (that I can find, at least) that says this is necessary, and
1. I'd argue that it's a bug (or at the very least, not proper encapsulation) if the user is able to cause the workflow runner to crash.

If I'm doing something wrong, I'd be happy to hear about it :) Thanks.

**Comment by nathan-weinberg** [comment]
Experiencing the same issue here https://github.com/nathan-weinberg/jeeves/pull/133/checks?check_run_id=875661858

**Comment by Ivaylo-Bachvarov** [comment]
Seems like a bug for me. In the official documentation the action is used without virtualenv: https://docs.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

**Comment by Borda** [comment]
The same also here - https://github.com/PyTorchLightning/pytorch-lightning/runs/889998403
for all OS (ubuntu-18.04, windows-2019, macOS-10.15) and python 3.6, 3.7 and 3.8

**Comment by nathan-weinberg** [comment]
I was able to workaround this by changing the pyyaml version from 5.1 to 5.3.1 in my requirements.txt

**Comment by maxim-lobanov** [comment]
Hello everyone, this issue is related to image, not the setup-python task. We are working on investigation and fix. Progress can be tracked in https://github.com/actions/virtual-environments/issues/1202#issuecomment-660006490

**Comment by Borda** [comment]
@nathan-weinberg I have tried to force `pyyaml==5.3.1` before installing requirements.txt but it did not help...

**Comment by nathan-weinberg** [comment]
@Borda Here is the PR in which I made the change - https://github.com/nathan-weinberg/jeeves/pull/135/files 

You may need to change the action version to v2

**Comment by nikita-bykov** [comment]
Hello @jameshiebert! 
The [related issue](https://github.com/actions/virtual-environments/issues/1202#issuecomment-660006490) from virtual-environments was resolved. I just tested it and everything works as expected for me. Could you please confirm that it works for you too?

**Comment by nikita-bykov** [comment]
@jameshiebert I'm going to close the issue, but feel free to contact us if you have any questions.
