### ISSUE TITLE
##[error]The process '/bin/bash' failed with exit code 127 

### ISSUE THREAD

**Issue by gorros** [actions/setup-python#115]
**Describe the bug**

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [x] self-hosted
- [ ] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**
3.7.8

**To Reproduce**
I am trying to install Python 3.7 on Ubuntu 18.04 self-hosted instance.

**Screenshots**

![Screen Shot 2020-07-16 at 1 27 04 PM](https://user-images.githubusercontent.com/10191638/87654512-102afb80-c768-11ea-8ba6-51f33f6b753c.png)

I assume that fails after this line of `setup.sh`
`cchmod +x ../python $PYTHON_MAJOR $PYTHON_MAJOR_DOT_MINOR $PYTHON_MAJORMINOR python`
 Since when I try `./python` I get.
`./python: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory`
System python version is 3.6.9
So when I changed version to 3.6.9 it worked.

**Comment by hfuss** [comment]
I'm using the https://github.com/summerwind/actions-runner-controller on OpenShift 4.5 and ended up just having to install Python 3.7 on top of the runner image from [deadsnakes](https://github.com/deadsnakes) PPA repo:

```dockerfile
FROM summerwind/actions-runner:v2.273.1

RUN sudo apt update -y \
  && sudo apt install -y software-properties-common \
  && sudo add-apt-repository ppa:deadsnakes/ppa \
  && sudo apt install python3-pip python3.7 python3.7-venv -y \
  && sudo python3.7 -m pip install --upgrade pip \
  && sudo rm -rf /var/lib/apt/lists/*
```

Another alternative for those who have `sudo` available and aren't trying to build the Python dep into their runner VM or container image, would be to use deadsnake's [GitHub Action for installing python](https://github.com/deadsnakes/action).

**Comment by konradpabjan** [comment]
With the latest `v2.1.4` release (if you're pinned to `v2` you're using the latest changes). This should now be resolved. Can anyone confirm?

**Comment by nikita-bykov** [comment]
Hello @gorros! Is this issue still relevant to you?

**Comment by nikita-bykov** [comment]
@gorros I'm going to close the issue, but feel free to contact us if you have any questions.
