### ISSUE TITLE
New Python 3.9.0b4 seems to be broken

### ISSUE THREAD

**Issue by webknjaz** [actions/setup-python#119]
**Describe the bug**

Python 3.9.0b4 makes pytest get stuck. The test step takes 1h 28m 46s, and a few starting log lines of
the pytest output are printed out, if you keep the job page open but disappear on reload.
Also, when downloading the logs archive, I see that it does not include any entries for that specific step.

It's not flaky and is happening on every build. Ref: https://github.com/pypa/setuptools/pull/2265.

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**

- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Python Versions**

3.9.0b4

**To Reproduce**

See the URL below.

**Run/Repo Url**

https://github.com/pypa/setuptools/pull/2265/checks?check_run_id=886735322

**Screenshots**

N/A

**Additional context**

I tried to integrate new Python 3.9.0 beta4 into the CI of setuptools.

**Comment by maxim-lobanov** [comment]
Hello @webknjaz , from https://github.com/pypa/setuptools/pull/2265 I see that your issue is related to extra files in workspace.
We have fixed this issue. Could you please try to specify `actions/setup-python@2.1.1` in your pipeline and check if issue is resolved?

**Comment by webknjaz** [comment]
Thanks! It worked!
