### ISSUE TITLE
Repository versioning not following GitHub action recommendations

### ISSUE THREAD

**Issue by frank-fischer-by** [actions/setup-python#120]
**Describe the bug**
We're using Dependabot to manage our dependencies.
Among others, Dependabot can also take care of _GitHub Actions_.

GitHub Actions has [recommendations on how to handle releases via tagging](https://docs.github.com/en/actions/creating-actions/about-actions#using-tags-for-release-management):
> * Create a release using semantic versioning. For more information, see "Creating releases."
> * **Move the major version tag (such as `v1`, `v2`) to point to the Git ref of the current release.** [...]

With release `v2.1.1` this was not done, (yet?) and the tag `v2` still points to `v2.1.0`.
As such Dependabot suggests to update `actions/setup-python@v2` to `actions/setup-python@v2.1.1` which of course would be a very short-sighted change.

Could you please point `v2` to 0c28554988f6ccf1a4e2818e703679796e41a214 (`v2.1.1`) or was this a deliberate decision?

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**To Reproduce**
1. Set up a GitHub Actions workflow with 
    ```yaml
    - name: SETUP - Set up Python
       uses: actions/setup-python@v2 
    ```
2. Set up a `.github/dependabot.yml` file with
    ```yaml
    version: 2
    updates:
      - package-ecosystem: "github-actions"
        directory: "/"
        schedule:
          interval: "daily"
    ```
3. Activate Dependency Graph & automatic dependency tracking
4. Check Pull Requests

**Comment by konradpabjan** [comment]
Thanks for opening the issue!

The `v2` tag has been updated to `0c28554988f6ccf1a4e2818e703679796e41a214` (same as `v2.1.1`)

I normally take care of updating tags whenever there are new releases but I was on 🌴 for a few days and away from my computer. This was one of the first things I did when I got back 😄
