### ISSUE TITLE
Allow specification of version X.Y including prereleases

### ISSUE THREAD

**Issue by altendky** [actions/setup-python#124]
**Describe the bug**
It would be nice to be able to specify a version such as 3.9 and have it get the latest prerelease if available.  I am not sure exactly why but can understand that someone might want the present behavior (failure) when only prereleases are available but perhaps a markup like '3.9-+' (or something much less terrible than that) could be used to enable either pre or regular releases.

**Comment by konradpabjan** [comment]
Will the following syntax not work for your use case?

``` 
with:
    python-version: '3.9.0-alpha - 3.9.0' # SemVer's version range syntax
```

Currently there is `Python 3.9.0b5` but lets say version `Python 3.9.0b6` comes out and then finally `Python 3.9.0` officially comes out. 

By specifying the range, the latest pre-release version will always be pulled. Once a stable version of Python 3.9 comes out (no new pre-release versions should come out for that specific version), the stable version of Python would be used.

**Comment by altendky** [comment]
Thank you for the quick response and for pointing out the solution.  I now see it was _right_ there in the docs.  My apologies for not finding it there myself.

I ended up with `3.9.0-alpha - 3.9.X` to get 'all prerelease or release' and implemented that as follows.

https://github.com/altendky/qtrio/blob/2f041af7a346b91d5e8f0765ee33c86cdc6f7e50/.github/workflows/ci.yml#L95
```yaml
        python: ['3.6', '3.7', '3.8', '3.9']
```


https://github.com/altendky/qtrio/blob/2f041af7a346b91d5e8f0765ee33c86cdc6f7e50/.github/workflows/ci.yml#L104
```yaml
          python-version: '${{ matrix.python }}.0-alpha - ${{ matrix.python }}.X'
```

Now just waiting on PySide2 and PyQt5 to release 3.9-supporting wheels...

**Comment by altendky** [comment]
Actually, I suppose this points out an error (I think) in the readme.  The range with the 0 micro/patch version did not (would not sensibly) allow stable releases beyond `.0` to be used.  As I recall just major.minor didn't work either and I had to use the major.minor.X noted above.

**Comment by ezio-melotti** [comment]
See also #213.
