### ISSUE TITLE
Seemingly correct version and environment not being recognized

### ISSUE THREAD

**Issue by aronchick** [actions/setup-python#125]
**Describe the bug**
I have a simple setup python job at the top of my workflow.

```
      - name: Set up Python 3.7.7
        id: python_setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.x'
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

```
However, when I run it, it doesn't seem to work. The weird thing is that you can see that the lines appear to pass correctly, but the test still fails.
```
[Lint and Test/Lint and Test    ]   💬  ::debug::check 3.7.8 satisfies 3.7.x
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && darwin===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && linux===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && linux===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && linux===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && win32===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x86===x64 && win32===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::check 3.7.7 satisfies 3.7.x
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && darwin===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && linux===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && linux===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && linux===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && win32===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x86===x64 && win32===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::check 3.7.6 satisfies 3.7.x
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && darwin===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && linux===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && linux===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && linux===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && win32===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x86===x64 && win32===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::check 3.7.5 satisfies 3.7.x
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && darwin===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && linux===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && linux===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && linux===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x64===x64 && win32===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::x86===x64 && win32===linux
[Lint and Test/Lint and Test    ]   💬  ::debug::check 3.6.11 satisfies 3.7.x
[Lint and Test/Lint and Test    ]   💬  ::debug::check 3.6.10 satisfies 3.7.x
[Lint and Test/Lint and Test    ]   💬  ::debug::check 3.6.9 satisfies 3.7.x
[Lint and Test/Lint and Test    ]   💬  ::debug::check 3.6.8 satisfies 3.7.x
[Lint and Test/Lint and Test    ]   💬  ::debug::check 3.6.7 satisfies 3.7.x
[Lint and Test/Lint and Test    ]   💬  ::debug::check 3.5.9 satisfies 3.7.x
[Lint and Test/Lint and Test    ]   💬  ::debug::check 3.5.4 satisfies 3.7.x
[Lint and Test/Lint and Test    ]   💬  ::debug::check 3.4.10 satisfies 3.7.x
[Lint and Test/Lint and Test    ]   💬  ::debug::check 3.3.7 satisfies 3.7.x
[Lint and Test/Lint and Test    ]   💬  ::debug::check 2.7.18 satisfies 3.7.x
[Lint and Test/Lint and Test    ]   💬  ::debug::check 2.7.17 satisfies 3.7.x
[Lint and Test/Lint and Test    ]   ❗  ::error::Version 3.7.x with arch x64 not found%0AThe list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
[Lint and Test/Lint and Test    ]   ❌  Failure - Set up Python 3.7.7
```

**Which version of the action are you using?**

- [ ] `v1`
- [X] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [ ] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**
Please list all of the effected versions of Python (`3.8.2`, etc.)
3.7.x

**To Reproduce**
1. Set up a VM with the following: `Linux cloudVM 5.3.0-1032-azure #33~18.04.1-Ubuntu SMP Fri Jun 26 15:01:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
2. Have a workflow with the job included.
3. Run the workflow.

**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.

**Screenshots**

**Additional context**

**Comment by RomainMuller** [comment]
I'm also hitting this with 3.6 (as `3.6.x`). Interestingly, it works in "real" GitHub Actions, but it does not work locally using [`nektos/act`](https://github.com/nektos/act).

**Comment by akhter-ali** [comment]
Running into the same with local runners.

**Comment by varunpalekar** [comment]
I also face same issue with local runner (`nektos/act`)

**Comment by carlthome** [comment]
Same issue here! My workaround for now is to run the job inside a container instead but ultimately I'd like to know that my Python application works on different OS:es so would still like to see this resolved.

**Comment by MrZilinXiao** [comment]
Same issue when using act!

**Comment by RomainMuller** [comment]
So - I suspect the culprit is actually different platform versions, which you can see in the manifest: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

Those are actually (silently) checked for in `@actions/tool-cache`: https://github.com/actions/toolkit/blob/af821474235d3c5e1f49cee7c6cf636abb0874c4/packages/tool-cache/src/manifest.ts#L87-L96

When using nektos/act, you'd want to ensure `act` is using an image that has is based off one supported platform image (per it's LSB tags). For example, adding `-P ubuntu-latest=nektos/act-environments-ubuntu:18.04` to the `act` invocation or in `.actrc` (careful - the `nektos/act-environments-ubuntu:18.04` image is *HUGE*).

**Comment by AutomatedTester** [comment]
This seems to have started 2 days ago on the [Selenium](https://github.com/seleniumhq/selenium) project. 

```yaml
- name: Set up Python 3.7
  uses: actions/setup-python@v2
  with:
       python-version: 3.7
```

In this[ run ](https://github.com/SeleniumHQ/selenium/runs/1974005634?check_suite_focus=true), we are setting 3.7 but the error below shows that python 3.6.9 is the runtime that is being used. 

```bash
assert sys.version_info >= (3, 7), f"To generate the CDP code requires python 3.7 or later. Executing python is {sys.version_info}"
AssertionError: To generate the CDP code requires python 3.7 or later. Executing python is sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
```

**Comment by yousefamar** [comment]
FYI, @RomainMuller hit the nail on the head, and there's a lighter workaround here: https://github.com/nektos/act/issues/251

**Comment by e-korolevskii** [comment]
Hello everyone!
I understand that a lot of time has passed and I apologize for that. Unfortunately, this bug cannot be reproduced at this time. Plus, it uses an outdated version of action.
Please let us know if this is still relevant for you, otherwise I'm going to close this issue.
