### ISSUE TITLE
setup_python fails with error "No such file or directory"

### ISSUE THREAD

**Issue by rhysmeister** [actions/setup-python#134]
**Describe the bug**
setup_python fails with error "No such file or directory"

Examples of action output

```
 Set up Python 3.60s
    setup_ccm_version_file: ./tests/integration/targets/setup_cassandra_cluster_manager/defaults/main.yml
Run actions/setup-python@v1
  with:
    python-version: 3.6
    architecture: x64
  env:
    setup_cassandra_version_file: ./tests/integration/targets/setup_cassandra/defaults/main.yml
    setup_ccm_version_file: ./tests/integration/targets/setup_cassandra_cluster_manager/defaults/main.yml
##[error]No such file or directory
```

```
 Set up Python 3.60s
    mongodb_version_file: ./tests/integration/targets/setup_mongodb/defaults/main.yml
Run actions/setup-python@v1
  with:
    python-version: 3.6
    architecture: x64
  env:
    mongodb_version_file: ./tests/integration/targets/setup_mongodb/defaults/main.yml
##[error]No such file or directory
```

**Which version of the action are you using?**

- [x ] `v1`
- [ ] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x ] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**
3.6

**To Reproduce**
Happens on all pull requests that have these actions using the setup_python action. 

**Run/Repo Url**
Observable on the folowing pulls...

https://github.com/ansible-collections/community.cassandra/pull/79
https://github.com/ansible-collections/community.mongodb/pull/160
https://github.com/ansible-collections/community.mongodb/pull/159

**Screenshots**

**Additional context**
Started happening yesterday afternoon, 10.09.2020 approx 3PM (CET)

**Comment by resmo** [comment]
Also same error message, can confirm date of appearance.

**Comment by rhysmeister** [comment]
Fixed my CI job with the info from @resmo in update 3. Specifically...

- Added default working dir to each job...

````
defaults:
      run:
        working-directory: ansible_collections/community/mongodb
````
- Changed actions/checkout@v1 to actions/checkout@v2.

**Comment by nikita-bykov** [comment]
Hello @rhysmeister! We apologize for such a late reply.
Do I understand correctly that your problem has been resolved and we can close the issue?

**Comment by rhysmeister** [comment]
@nikita-bykov  Yep. All good.

**Comment by nikita-bykov** [comment]
@rhysmeister That's great! Feel free to contact us if you have any questions.
