### ISSUE TITLE
Support PyPy3.7 separate from PyPy3.6

### ISSUE THREAD

**Issue by webknjaz** [actions/setup-python#136]
**Request**

PyPy 7.3.2 got released with versions compatible with Python 2.7, 3.6 and 3.7 (new!): https://morepypy.blogspot.com/2020/09/pypy-732-triple-release-python-27-36.html

I'd like to be able to specify `pypy` / `pypy3.6` and `pypy3.7` when using this action. Just like Travis CI allows us to do this.

**Comment by henryiii** [comment]
Just a thought, but "pypy3" could point at the "latest stable" python 3 mode, which is pypy3.6 for now.

**Comment by aouinizied** [comment]
Having both will allow easier wheels generation and will be a very nice feature.

**Comment by mattip** [comment]
PR gh-161 should move this forward.

**Comment by maxim-lobanov** [comment]
Hello everyone!
https://github.com/actions/setup-python/pull/168 was recently merged and PyPy support is available in `actions/setup-python@v2`. Please see more details on usage in README
