### ISSUE TITLE
Add Python 3.9 support

### ISSUE THREAD

**Issue by hugovk** [actions/setup-python#148]
Python 3.9.0 was released today, 2020-10-05:

* https://discuss.python.org/t/python-3-9-0-is-now-available-and-you-can-already-test-3-10-0a1/5375?u=hugovk

Please could you also add support in GitHub Actions for Python 3.9?

Thank you!

PS It took 21 days for 3.8: https://github.com/actions/setup-python/issues/30#issuecomment-549520845

**Comment by maxim-lobanov** [comment]
Hello everyone:
Python 3.9 is already available (It is not pre-cached on image yet, so it will be installed on-flight with minor latency):
```
- uses: actions/setup-python@v2
  with:
    python-version: '3.9'
```

We also going to deploy new image with pre-cached Python 3.9 next week.

**Comment by hugovk** [comment]
Confirmed it's now available on GHA, thank you!

<img src=https://user-images.githubusercontent.com/1324225/95213385-6eabc700-07f7-11eb-85a6-2c650609246b.png width=50%>

Took ~10s to install on Linux, ~60s on macOS and ~51s on Windows, not a problem for me, and good to hear the pre-cached images is coming soon.

https://github.com/hugovk/test/runs/1215290584?check_suite_focus=true


```
Run actions/setup-python@v2
Version 3.9 was not found in the local cache
Version 3.9 is available for downloading
Download from "actions/python-versions@3.9.0-83838 python-3.9.0-linux-20.04-x64.tar.gz (download)"
Extract downloaded archive
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/e8e512d5-ecbb-4563-9374-a1796267419e -f /home/runner/work/_temp/e9bdf138-7f69-49ec-8166-59a47b1d3ef4
Execute installation script
Check if Python hostedtoolcache folder exist...
Create Python 3.9.0 folder
Copy Python binaries to hostedtoolcache folder
Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
Upgrading PIP...
Looking in links: /tmp/tmpiitvwvjj
Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages (49.2.1)
Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages (20.2.3)
Collecting pip
Downloading pip-20.2.3-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
Successfully installed pip-20.2.3
Create complete file
Successfully setup CPython (3.9.0)
```

**Comment by hugovk** [comment]
> PS It took 21 days for 3.8: [#30 (comment)](https://github.com/actions/setup-python/issues/30#issuecomment-549520845)

This time: 18 hours! 🎈

**Comment by davidism** [comment]
Can you reopen this issue until the 3.9 image is available through the cache? Currently, 3.9 on Windows and Mac is frustratingly slow, and I have no way to track when it will be fast.

**Comment by davidism** [comment]
Opened #152 to track adding 3.9 to the pre-cached image.

**Comment by davidism** [comment]
Turns out the correct issue to watch is https://github.com/actions/virtual-environments/issues/1740, also reported by @hugovk. A link next time would be helpful. :slightly_smiling_face: :

**Comment by hugovk** [comment]
> PS It took 21 days for 3.8: [#30 (comment)](https://github.com/actions/setup-python/issues/30#issuecomment-549520845)

🎈 This year it 17 took hours! 🎉 

* https://twitter.com/hugovk/status/1321536957965574151
