### ISSUE TITLE
How to find available versions?

### ISSUE THREAD

**Issue by wbond** [actions/setup-python#15]
I'm keen on trying GitHub Actions with a few Python projects I have that I support a broad variety of older releases.

I saw the readme mentioned 2.x, 3.x and PyPy, but it wasn't clear what versions of Python are supported on what virtual environments?

In the past dealing with Travis it has always been really opaque and a source of annoyance to have to "guess" and create commits to trigger CI runs, just to try and figure out what versions I can actually target.

Having a list in the readme would be 👍.

**Comment by Julian** [comment]
(As a specific instance of this -- I spent a few failed builds figuring out that this action calls `pypy`  for Python 2 `pypy2`, rather than just `pypy`.)

**Comment by konradpabjan** [comment]
We have a new support page that describes all of the available software on our hosted runners. You can check it out here: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

There are a few things that I see wrong with the available versions of python so I'll make sure those get updated. But in general, the support page is where you'll be able to find information about all the  software on the runners

**Comment by agronholm** [comment]
"Oops, this page does not exist".

**Comment by hugovk** [comment]
Try this:

https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-software
