### ISSUE TITLE
Python 3.10 alphas?

### ISSUE THREAD

**Issue by The-Compiler** [actions/setup-python#150]
Based on this in the readme:

> If there is a specific version of Python that is not available, you can open an issue here

I'd like to request support for the Python 3.10.0 Alpha 1 which was [recently released](https://www.python.org/downloads/release/python-3100a1/) - that is, unless it's intended to only support Betas for pre-releases and not Alphas.

The reason I'm asking is that the [project](https://www.qutebrowser.org/) I'm developing parses annotations for functions and those change to being lazily evaluated by default ([PEP 563 -- Postponed Evaluation of Annotations](https://www.python.org/dev/peps/pep-0563/)). I'd like to test compatibility with that change as early as possible, and I unfortunately can't use `from __future__ import annotations` because that's not supported on Python 3.6.

**Comment by dmitry-shibanov** [comment]
Hello @The-Compiler , python 3.10.0a1 was added and you can use it by this snippets:
```
- uses: actions/setup-python@v2
  with:
    python-version: '3.9.0 - 3.10.0-alpha.1'
```
or
```
- uses: actions/setup-python@v2
  with:
    python-version: '3.10.0-alpha.1'
```

**Comment by nulano** [comment]
`3.10-dev` also works: https://github.com/actions/setup-python/blob/878156f1deda8836af6aca53d02b078285bdf154/dist/index.js#L6792-L6801

**Comment by The-Compiler** [comment]
Amazing, thanks! Closing this then. I can't really test it right now because I'm running into https://github.com/pypa/wheel/issues/354 but that'll hopefully be resolved soon as well.
