### ISSUE TITLE
Could not use python 3.9 with windows agent

### ISSUE THREAD

**Issue by menishmueli** [actions/setup-python#154]
**Describe the bug**
Could not use python 3.9 with windows agent
**This only being reproduce in V1 and not in V2**

**Which version of the action are you using?**

- [x] `v1`
- [ ] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [ ] Linux
- [x] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**
python 3.9

**To Reproduce**
Add python 3.9 to python-version
Set os to windows-latest
use  setup-python@v1

See https://github.com/menishmueli/minio-py/blob/master/.github/workflows/pythonpackage-windows.yml

**Run/Repo Url**
V1 Windows(not working): https://github.com/menishmueli/minio-py/runs/1260839168?check_suite_focus=true
V1 Linux(working): https://github.com/menishmueli/minio-py/runs/1260839168?check_suite_focus=true
V2 windows (working): https://github.com/menishmueli/minio-py/runs/1260918853?check_suite_focus=true

**Screenshots**
![image](https://user-images.githubusercontent.com/11976579/96175473-9c011f00-0f33-11eb-967c-d6ad67099cba.png)

Working on linux:
![image](https://user-images.githubusercontent.com/11976579/96175508-aae7d180-0f33-11eb-80f5-0eec61b6c0a8.png)

**Comment by manastalukdar** [comment]
Same issue on MacOS.

**Comment by maxim-lobanov** [comment]
Hello @menishmueli , please switch to `actions/setup-python@v2`. Python 3.9 is not added to image yet. Version v1 is not able to install Python in runtime. V2 can.

**Comment by menishmueli** [comment]
@maxim-lobanov I did switched to V2 and the issue did not reporoduced (see third line in the start of the issue) 

I hope you will add python 3.9 to image in V1 in the near future, because from the error message you couldn't tell that moving to V2 (and the fact that V2 exists) will solve the problem

Maybe add to V1 an error message in case python version does not exist to consider using V2? this might help in future python versions

**Comment by maxim-lobanov** [comment]
Yes, Python 3.9 will be added to image but usually happens in ~3 weeks after release.
As for the error message, cc: @konradpabjan

**Comment by konradpabjan** [comment]
I'm inclined to not add any error messages to the `v1` version. At this point it's considered "legacy" and it only should receive updates/patches if there is some security concern or fix that is absolutely required.

We recommend all users switch over to `v2` since all new features and enhancements only get added to that version. There are no compat differences or blockers that should require users to stick with `v1`.

The `README` in this repo has extensive documentation about `v2` and how it only supports downloading distributions on the fly,. If you look at the readme of what the `v1` tag is pinned to you'll notice there is no mention of downloading distributions on the fly: https://github.com/actions/setup-python/tree/releases/v1

**Comment by AraHaan** [comment]
if it was me I would delete v1 but that is not always an option  and have v1 be proxy to v2 😆.

![image](https://user-images.githubusercontent.com/15173749/96626746-e0970c80-12dd-11eb-86f8-377552ab09a4.png)

**Comment by konradpabjan** [comment]
Unfortunately we don't have any first party mechanism to deprecate actions or feature to tell users **not** to use a specific version. As long as a sha or ref exists, users can pin to it and we can't do much about it.

We also don't like to break users. Internal telemetry indicates that a large percentage of users are still pinned to a older versions and we don't want to break anyone so at least for the moment, we won't be deprecating anything.

Regarding the error, there is another issue tracking this: https://github.com/actions/setup-python/issues/146
