### ISSUE TITLE
Add python 3.0.x up to python 3.4.x for x86 and x64

### ISSUE THREAD

**Issue by AraHaan** [actions/setup-python#157]
**Describe the bug**

Python 3.0.x all the way to Python 3.4.x for x86 and x64 are all missing.

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [ ] Linux
- [x] Windows
- [ ] Mac

If applicable, please specify if you're using a container
No containers.

**Python Versions**
Please list all of the effected versions of Python (`3.8.2`, etc.)
- 3.0.x
- 3.1.x
- 3.2.x
- 3.3.x
- 3.4.x

**To Reproduce**
1. Create jobs that try to use python 3.0.x for x86 and x64 all the way up to python 3.9.
2. Let the jobs run and do their thing.
3. notice all of them fail until Python 3.5 and newer on the x86 and the x64 targets.

**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.
https://github.com/AraHaan/pthmgr/actions/runs/319111689

**Screenshots**
I think the repo url just about covers it.

**Additional context**

I am not sure however yet how it will work on linux or mac as the python usage in my repo contains Windows only extension module code.

I do not care much for the revisions, I basically did major and minor versions of python 3.

**Comment by AraHaan** [comment]
@MaksimZhukov after looking at the python repository mind explaining where the only version of 3.4 and 3.3 that can find on it only contains linux x64?

![image](https://user-images.githubusercontent.com/15173749/96744688-4ee9d680-1393-11eb-84be-840d2e1ca91c.png)

**Comment by AraHaan** [comment]
Hmm according to what I see in the previous releases of python 3.0 on python.org it seems that python 3.0.1 was the final release of python 3.0.

**Comment by Leseratte10** [comment]
I'd be interested in something like that as well. I need a python3 version that's still compatible with Windows XP x86, and 3.4.10 seems to be the latest version that supports that, but the newest x86 Windows version that's supported by this Github Action is 3.5.4. 

The 3.4.10 and 3.3.7 versions do exist, but only for x64 Linux, not for x86 Windows. Can that be changed?

**Comment by AraHaan** [comment]
yes I agree we do need 3.0.x all the way up to 3.4.x for both x86 and x64 here on my c extension because of the fact that I would not only like to test and see if it actually compiles for that python version, but also for the fact that the code it uses is compatible all the way down to windows 98 because it only touches the registry and then broadcasts said changes to all programs (an environment variable change aka ``WM_SETTINGCHANGE``)

**Comment by AraHaan** [comment]
I have found the latest binary releases to these python versions:

Those being:
- 3.0.1
- 3.1.4
- 3.2.5
- 3.3.5
- 3.4.4

*WARNING DO NOT DELETE THIS COMMENT WILL PULL REQUEST THE URLS OF THE UPLOADED FILES HERE TO THE PYTHON-VERSIONS REPOSITORY!!!*
[python-3.0.1-win32-x64.zip](https://github.com/actions/setup-python/files/5417589/python-3.0.1-win32-x64.zip)
[python-3.0.1-win32-x86.zip](https://github.com/actions/setup-python/files/5417590/python-3.0.1-win32-x86.zip)
[python-3.1.4-win32-x64.zip](https://github.com/actions/setup-python/files/5469576/python-3.1.4-win32-x64.zip)
[python-3.1.4-win32-x86.zip](https://github.com/actions/setup-python/files/5469578/python-3.1.4-win32-x86.zip)
[python-3.2.5-win32-x64.zip](https://github.com/actions/setup-python/files/5469579/python-3.2.5-win32-x64.zip)
[python-3.2.5-win32-x86.zip](https://github.com/actions/setup-python/files/5469580/python-3.2.5-win32-x86.zip)
[python-3.3.5-win32-x64.zip](https://github.com/actions/setup-python/files/5469581/python-3.3.5-win32-x64.zip)
[python-3.3.5-win32-x86.zip](https://github.com/actions/setup-python/files/5469582/python-3.3.5-win32-x86.zip)
[python-3.4.4-win32-x64.zip](https://github.com/actions/setup-python/files/5469583/python-3.4.4-win32-x64.zip)
[python-3.4.4-win32-x86.zip](https://github.com/actions/setup-python/files/5469584/python-3.4.4-win32-x86.zip)

**Comment by Leseratte10** [comment]
Just leaving this comment here' not 100% sure if this is the correct place: It looks like the old Python versions were now added (requesting Python version 3.4.4 on Windows x86 does now work), but it seems like there is an error in the install script. 

The file that is downloaded contains a "setup.ps1" script that installs and configures the Python stuff, and that script is updating Pip with the following command `cmd.exe /c "$PythonExePath -m ensurepip && $PythonExePath -m pip install --upgrade pip"`. 

In my case, this removes Pip 7.1.2 and installs Pip 20.2.4. 

However, it looks like Pip 20.2.4 requires Python 3.5 or later, so this Python installation is effectively broken now as it has a Pip version that can no longer run using the installed Python version: 

```
  File "c:\hostedtoolcache\windows\python\3.4.4\x86\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 92, in <module>
    raise RuntimeError("Python 3.5 or later is required")
RuntimeError: Python 3.5 or later is required
```

Can the installation script be changed so it doesn't update Pip to the most recent version, or maybe make it update to the last version that supports the given Python version?

**Comment by MaksimZhukov** [comment]
Hello everyone!
We've published the following Python versions for Windows to the [actions/python-versions](https://github.com/actions/python-versions/releases) repository:
- 3.4.4
- 3.3.5
- 3.2.5
- 3.1.4
- 3.0.1

These Python versions can be installed by `actions/setup-python` action. Please find more details [here](https://github.com/actions/virtual-environments/issues/1943).

I will close this issue, but feel free to contact us if you have any concerns.
