### ISSUE TITLE
Modifying LD_LIBRARY_PATH causes issues

### ISSUE THREAD

**Issue by polm** [actions/setup-python#159]
**Describe the bug**

The changes in #144 cause issues running some applications in the container, such as git cloning with https urls. See these related issues:

https://github.com/pypa/manylinux/issues/812
https://github.com/RalfG/python-wheels-manylinux-build/issues/26

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

I was using the `pypa/manylinux1_x86_64` container.

**Python Versions**

Happens with all Python versions.

**To Reproduce**

    git clone https://...

Gives a libcurl error.

**Run/Repo Url**

https://github.com/polm/fugashi/runs/1291141895?check_suite_focus=true

**Comment by nikita-bykov** [comment]
Hello @polm!
This issue has been open for a year without any activity, so I'm going to close it as stale.
Please feel free to contact us if the issue is still relevant to you and we will reopen it.
Thanks!
