### ISSUE TITLE
PyPy3 version is quite old

### ISSUE THREAD

**Issue by Julian** [actions/setup-python#16]
The version of PyPy3 that's provisioned is quite old (and buggy -- e.g. PyYAML doesn't even seem to work on it on Windows -- https://github.com/Julian/github-actions-test/runs/205309060#step:5:29 )

The current version is a Python 3.6 (https://www.pypy.org/download.html#building-from-source) and a lot more stable (I'm not sure whether it fixes the YAML issue above but going to check, it probably should).

(Not sure whether the PyPy2 is also out of date, I can't tell yet how to check its version without writing a build to just output it -- also not sure if this is something I can fix myself and send a PR for but if I do see how to do that will be sure to.)

**Comment by Julian** [comment]
Polite ping on this one -- is this something an end-user such as myself can help address, or is the thing that needs updating not actually exposed publically?

**Comment by konradpabjan** [comment]
PyPy3 is on its way. Should be out this week. Using the latest 7.2.0 version for 3.6: https://bitbucket.org/pypy/pypy/downloads/

PyPy2 is also a little out of date so I'll update that as well (hoping to do it next week at the latest). The repo for updating the tools cache is not open source at the moment unfortunately.

**Comment by Julian** [comment]
Great! Thanks for the update! Much appreciated.

**Comment by konradpabjan** [comment]
PyPy3 is now up to the latest version

![image](https://user-images.githubusercontent.com/16109154/70455046-8f8d7980-1a79-11ea-8373-6d14bac82ac3.png)

**Comment by Julian** [comment]
Awesome, thanks again!
