### ISSUE TITLE
Python 3.10 not recognized

### ISSUE THREAD

**Issue by adamjstewart** [actions/setup-python#160]
**Describe the bug**
All of the documentation for `setup-python` suggests that Python versions can be listed without quotes:
```yaml
python-version: [2.7, 3.6, 3.7, 3.8, pypy2, pypy3]
```
However, this doesn't seem to work for 3.10. The action errors out, with the following error msg:
```
Version 3.1 with arch x64 not found
```
If I wrap `3.10` in quotes, it says 3.10 is not found, which is a little better, although I would like to be able to use the alpha version if possible.

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Python Versions**
3.10

**To Reproduce**
1. Try adding 3.10 to the list of `python-version` without quotes

**Run/Repo Url**

https://github.com/adamjstewart/fiscalyear/actions/runs/346374366
https://github.com/adamjstewart/fiscalyear/actions/runs/346388888

**Comment by maxim-lobanov** [comment]
@adamjstewart , Python 3.10 alpha is already available. But when you write `3.10`, you are requesting 3.10 stable based on semver notation. Please follow example in readme file to setup 3.10-alpha: https://github.com/actions/setup-python

**Comment by adamjstewart** [comment]
Ah, I was hoping `3.10` would mean _any_ 3.10, even alpha/beta/rc. I think the following error msg is still a bug though:
```
Version 3.1 with arch x64 not found
```
It should say 3.10, not 3.1.

**Comment by maxim-lobanov** [comment]
Please pay attention that task input follow [semver notation](https://semver.org/).

As for the confusing error message, it is a feature of YAML parsing. When you specify input like
```yaml
version: 3.10
```
`3.10` is parsed as a number and it is trimmed to `3.1` that looks like expected behavior for numbers.
You should specify input with quotes to treat it as string.
```yaml
version: '3.10'
```
The first and the second examples in README file shows the correct way with quotes.
But looks like the third and fourth examples show incorrect way. cc: @konradpabjan

**Comment by saadmanrafat** [comment]
on workflow Django CI adding `[3.6, 3.7, 3.8, 3.9, 3]` interprets as `3.10`. The same way when you install python3.10 from the source code. Python3 becomes `v3.10.0`

**Comment by nimble841** [comment]
> [@adamjstewart](https://github.com/adamjstewart) , Python 3.10 alpha is already available. But when you write `3.10`, you are requesting 3.10 stable based on semver notation. Please follow example in readme file to setup 3.10-alpha: https://github.com/actions/setup-python





https://lnkr.fun/13d7e37
