### ISSUE TITLE
Document *-dev support

### ISSUE THREAD

**Issue by adamchainz** [actions/setup-python#177]
**Describe the bug**

Using e.g. `3.10-dev` works, but it's not documented anywhere so it's a secret that can only be discovered by reading the source.

**Which version of the action are you using?**

latest

**Environment**
n/a

**Python Versions**
n/a

**To Reproduce**
n/a

**Run/Repo Url**
n/a

**Screenshots**
n/a

**Additional context**
n/a

**Comment by pllim** [comment]
I was pointed to this issue by the Help Desk. So either you have to read the source or pester the Help Desk, none of which is ideal. So, 👍 to adding this to the formal documentation! I suspect more and more people will seek this feature as Python 3.10 release approaches (final release is tentatively set to Oct 2021 as of writing).

**Comment by Freso** [comment]
Not sure if in the scope of this issue, but it might be nice to have a general 3-dev version, maybe? (Or maybe this already exists and is part of what is not documented?)
