### ISSUE TITLE
Accessing system-site-packages

### ISSUE THREAD

**Issue by ukBaz** [actions/setup-python#178]
**Describe the bug**
Access Python dist-packages that are installed with `apt`

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**
Please list all of the effected versions of Python (`3.8.2`, etc.)

    python-version: 3.8

**To Reproduce**

The Python dbus package is already on the Linux image used but if it needs to be installed it is `sudo apt install python3-dbus` and this allows the `import dbus` to be available nornally. However because this is an `apt` install it goes to `/usr/lib/python3/dist-packages`. This requires a python virtual environment on a local machine to require `--system-site-packages`

**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.

Failing PR: https://github.com/ukBaz/python-bluezero/pull/296

Log: https://github.com/ukBaz/python-bluezero/runs/1594397534?check_suite_focus=true#step:6:210

**Screenshots**
```none
 test_observer (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_observer (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_observer
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/runner/work/python-bluezero/python-bluezero/tests/test_observer.py", line 1, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```

**Additional context**

**Comment by nikita-bykov** [comment]
Hello @ukBaz!
This issue has been open for a year without any activity, so I'm going to close it as stale.
Please feel free to contact us if the issue is still relevant to you and we will reopen it.
Thanks!
