### ISSUE TITLE
Document how to evade a specific version

### ISSUE THREAD

**Issue by Julian** [actions/setup-python#18]
It'd be great if the documentation covered specifically how to "evade" a given version -- i.e., how does one use this action to provision 2.7 and 3.3, but if the 3.4 provisioning is broken for whatever reason, how does one drop down a level and provision that one themselves.

(Obviously related to #16, where now I'm trying to figure out how I use this for everything but the combination of pypy3-on-windows, where I have to figure out how to manually get the right version myself)

**Comment by Julian** [comment]
Covering this from the contributor's perspective would be great too (i.e. what file does one modify to fix the provisioning and send a PR -- though from what I can tell that seems possibly not in here? am I missing where the actual "meat" of the provisioning is?)

**Comment by Julian** [comment]
Ah I see, from the README: "optionally installing a version of python and adding to PATH. Note that this action only uses versions of Python already installed in the cache." -- I don't know what "the cache" refers to, but I guess I assume it's some thing already provisioned on virtual machines and all this thing does is know how to pull files out of it, there's no remote downloading involved?

(Would probably be great to document that too)

**Comment by konradpabjan** [comment]
A big help-doc was recently published that details Actions + Python https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-python-with-github-actions 

The doc includes an example on how to exclude a specific version of Python. I've added a similar example to the README here and added a link to the help-doc.

The help-doc and recent changes to the README here document all of the intricacies of how `setup-python` works.

**Comment by Julian** [comment]
Nice, thanks!
