### ISSUE TITLE
Setting up python2.7 on x86 architecture for Linux environment is not supported 

### ISSUE THREAD

**Issue by mpconte** [actions/setup-python#181]
Action fails when try to setup a Linux environment using python2.7 on x86 architecture.  I receive an error indicating that this configuration is not supported.

v2.2.1

Linux

No containers

**Python Versions**
2.7

**Comment by dmitry-shibanov** [comment]
Hello @mpconte. At the moment task does not support arch x86 on Linux. If you want we can track this as feature request ? The list of all available versions you can find [here](https://github.com/actions/python-versions/blob/main/versions-manifest.json).

**Comment by mpconte** [comment]
Hello @dmitry-shibanov. Thanks, I'd appreciate that.

**Comment by dmitry-shibanov** [comment]
Hello @mpconte. The [support for python 2.7](https://github.com/actions/setup-python/issues/672) was removed that is why I'm going to close the issue.
