### ISSUE TITLE
v2 tag doesn't use the latest 2.x.x version

### ISSUE THREAD

**Issue by yoichiwo7** [actions/setup-python#183]
**Describe the bug**

When we set the action tag to `v2` the runner doesn't use the latest version: `v2.2.1` tag.
We know it's not latest version because bug that is already fixed (#144) occurs.
If we set the action tag to `v2.2.1`, the runner uses the latest version as expected; the fixed bug won't occur.

It's very confusing which version is used when `@v2` tag is specified.
Doesn't setting `v2` tag mean "Use the latest 2.x.x version"?

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [x] Some other tag (such as `v2.0.1` or `master`)
  - [x] `v2.2.1` - Because `v2` doesn't use the latest release version

**Environment**
- [x] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**

Python 3.6 - 3.8

**To Reproduce**

Set `v2` tag when using setup-python.

```yaml
    - uses: actions/setup-python@v2
```

When we run the workflow, it won't use the latest version: `v2.2.1` tag.

**Run/Repo Url**

None (It's private GHE Server)

**Screenshots**

\-

**Additional context**

-\-

**Comment by konradpabjan** [comment]
Currently it points to the latest release. After every new release there is sometimes a 1-2 day delay before we update the major tag to `v1` or `v2`. Lets us test a little bit more
