### ISSUE TITLE
Avoid need for Administrator rights on Windows

### ISSUE THREAD

**Issue by carsonyl** [actions/setup-python#193]
**Describe the bug**
I'm using this action with a self-hosted runner on Windows. As described in the readme, under this scenario, the action needs to run as Administrator in order to set up new Python versions. But this clashes with running the self-hosted runner as a service under `NT AUTHORITY\NETWORK SERVICE`, and it seems unwise to run the service as Administrator.

Ideally, the action could avoid needing Administrator rights by installing Python just for the current user, or by using one of the embeddable packages of Python that don't involve an MSI.

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [x] self-hosted
- [ ] Linux
- [x] Windows
- [ ] Mac

**Python Versions**
3.9.2 x64

**To Reproduce**
With the self-hosted runner running as a service using default settings, and starting with an empty work folder, run the action to trigger a Python installation attempt failure. The log ends with:

```
Install Python 3.9.2 in C:\actions-runner\_work\_tool\Python...

Error: Error happened during Python installation
Error: At C:\actions-runner\_work\_temp\9353962a-1e9f-484c-bb48-761d49ade1c8\setup.ps1:121 char:5
+     Throw "Error happened during Python installation"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error happened ...on installation:String) [], RuntimeException
    + FullyQualifiedErrorId : Error happened during Python installation
Error: The process 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
```

**Workaround**
1. Pin the version of Python installed by the action, so future minor and patch releases won't trigger an install attempt that will result in failure. (assuming that automatic upgrades can happen)
2. With the self-hosted runner running as Administrator, run the workflow(s) that install the version(s) of Python needed.
3. For subsequent runs, the self-hosted runner can run as a service under `NT AUTHORITY\NETWORK SERVICE`.

**Comment by frostming** [comment]
Any update on this? I hit the same issue.

**Comment by marko-zivic-93** [comment]
Hello @carsonyl and @frostming 
We have started investigation of this bug. You may expect feedback very soon :)

**Comment by brcrista** [comment]
Thanks for the detailed writeup @carsonyl.  Some thoughts:

> Ideally, the action could avoid needing Administrator rights by installing Python just for the current user, or by using one of the embeddable packages of Python that don’t involve an MSI.

The embeddable package seems to me like a bit of a hack since [it's not intended to be a replacement for a standard Python installation](https://docs.python.org/3/using/windows.html#windows-embeddable).  Installing Python for the current user sounds like a good idea, but I wonder what the implications of that are and whether it would be a breaking change.  Of course, it would be best if the action "just worked," but perhaps an easy and safe fix would be to add a new input for a per-user installation.

For context, on GitHub-hosted Windows runners, the runner process [runs as administrator](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#administrative-privileges-of-github-hosted-runners).  From a security perspective, a machine running a self-hosted runner should be considered completely untrusted whether it's running as admin or not.

**Comment by dsame** [comment]
Hello @carsonyl,
As @brcrista explained, we are not going to implement this functionality for now. We advise you to use your own python setup in case if you can not afford the runner with Administrative setup and caching it. Do you need our help for setting this pipeline? If you do, please feel free to let us know.

**Comment by carsonyl** [comment]
Thanks, @dsame and all. That's fine by me. It wasn't originally clear to me that self-hosted runners are expected to run as admin, or that runner hosts should be completely untrusted. I assumed that it was an acceptable use case to host a runner in workstation environments that may have other things going on.

**Comment by marko-zivic-93** [comment]
Thank you guys! I will now close this issue due to the fact that we are not going to pursue implementing it. 
@carsonyl if you have any additional concerns or questions, please feel free to leave a comment here or to create a new issue.

**Comment by brcrista** [comment]
@carsonyl it all depends on your project.  If it's a small private repo and you trust everyone who has access, then running a self-hosted runner on a workstation might be fine.  As you get into a bigger private repo or a public repo, that becomes pretty risky and you should consider dedicated build infrastructure.

If you're maintaining self-hosted runners for a big project, I'd recommend looking at https://github.com/actions-runner-controller/actions-runner-controller and enabling the `ephemeral` feature.  That will make sure each job runs in a clean environment, just like using a GitHub-hosted runner.
