### ISSUE TITLE
How to setup pip cache?!? (And please enable github Discussions)

### ISSUE THREAD

**Issue by jedie** [actions/setup-python#194]
The github discussion is not enabled in this project. So i just create this issues:

How can i setup cache for pip in actions?

**Comment by mrlubos** [comment]
Hey @jedie, would this help? https://medium.com/ai2-blog/python-caching-in-github-actions-e9452698e98d

**Comment by hugovk** [comment]
Good news, simpler caching is coming soon in https://github.com/actions/setup-python/pull/266!

**Comment by nikita-bykov** [comment]
Thank you for opening issue! [This PR](https://github.com/actions/setup-python/pull/266) includes caching for pip and pipenv  dependencies.
I'm going to close this issue as duplicate of #226
