### ISSUE TITLE
Setting up python3.6 or Upper Version on  [amd64,arm64,ppc64le,s390x] architecture for Linux environment is not supported 

### ISSUE THREAD

**Issue by bivasda1** [actions/setup-python#197]
**Describe the bug**
While Enabling multiarc support by buildX for che pkg,python3.6 is not supported for **amd64,arm64,ppc64le,s390x** .What is the best Approach to enabling multiarch for giving arch?
Currently given Arch is not supported: https://github.com/actions/python-versions/blob/main/versions-manifest.json

**Which version of the action are you using?**
- [ ] `v2`
```
- name: Set up Python 3.6
        uses: actions/setup-python@v2
```
**Environment**
- [ ] Linux

**Python Versions**
Please list all of the effected versions of Python (`3.6 and Upper version`, etc.)

**Screenshots**
```
Run actions/setup-python@v2
Version 3.9.2 was not found in the local cache
Error: Version 3.9.2 with arch ppc64le not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-
```

**Comment by konradpabjan** [comment]
I'm going to group this under "won't support"

The issue with Python is that we have to compile the binaries from source for all of our runners and then those are uploaded to here: https://github.com/actions/python-versions/releases (the action then pulls the distributions from there)

We can't support every architecture and platform and we only have hosted runners for `Ubuntu`, `Windows` and `Mac` with certain architectures. The same rules apply as for our virtual environments: https://github.com/actions/virtual-environments#available-environments. We would have to actively have self-hosted runners with the following architectures to compile & test everything so for the moment we're actively choosing not to support this.

**Comment by NiklasRosenstein** [comment]
@konradpabjan `arm` and `arm64` are supported architectures by the Gitlab Runner, are there any plans to provide binaries for Python for these platforms?

**Comment by remilapeyre** [comment]
Hello @konradpabjan, the self-hosted runners support ARM32 and ARM64 (this one is still in beta): https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#architectures

Would it be possible to revisit the decision of not providing Python for those architectures?
