### ISSUE TITLE
actions/python-versions is missing 3.8.9

### ISSUE THREAD

**Issue by Parnassius** [actions/setup-python#200]
**Describe the bug**
Python 3.8.9 is missing from https://github.com/actions/python-versions/releases. It was released along with 3.9.3, which is indeed present (and 3.9.4, released a couple of days after, is there as well).

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [x] Linux
- [ ] Windows
- [ ] Mac

**Python Versions**
`3.8.9`

**Comment by nulano** [comment]
They've just added it now.

https://github.com/actions/python-versions/releases/tag/3.8.9-104257
https://github.com/actions/python-versions/pull/90/files

**Comment by Parnassius** [comment]
> They've just added it now.

Thanks for the heads-up, I'm closing this
