### ISSUE TITLE
Python 3.9.4 jobs on windows appear to be missing python3.lib

### ISSUE THREAD

**Issue by alex** [actions/setup-python#202]
**Describe the bug**

Starting with Python 3.9.4, we're seeing jobs fail because `python3.lib` is not available. This file is used as a part of the PEP384 ABI.

You can see an example this failure here: https://github.com/pyca/cryptography/pull/5961/checks?check_run_id=2308023145

A past job which was using 3.9.2 passes fine: https://github.com/pyca/cryptography/runs/2296503076?check_suite_focus=true

**Which version of the action are you using?**

v2.2.1

**Environment**
- [ ] self-hosted
- [ ] Linux
- [x] Windows
- [ ] Mac

**Comment by davidhewitt** [comment]
@alex there's something suspicious going on for sure in that CI run you link. I can see that `setup-python` reports it installed `3.9.4`, but just above the cryptography build failure message this is the search path that is being passed to rustc:

```
-L native=c:\hostedtoolcache\windows\python\3.9.2\x86\libs
```

... `3.9.2` ? 🤔 

FWIW we haven't seen any issues upstream in PyO3 on equivalent jobs. https://github.com/PyO3/pyo3/runs/2385052607?check_suite_focus=true

**Comment by alex** [comment]
Oh shoot. I think this is actually a caching issue... which I'm not sure how to fix... I think the issue is that our cache key contains the version specified (3.9), not the version installed (3.9.2).

In any event, I'll close this.
