### ISSUE TITLE
Bogus "3.10.0-beta.1" release

### ISSUE THREAD

**Issue by The-Compiler** [actions/setup-python#207]
In https://github.com/actions/python-versions/pull/92/, it looks like a 3.10.0-beta.1 [release](https://github.com/actions/python-versions/releases/tag/3.10.0-beta.1-105026) was pushed, which also gets used with `python: 3.10-dev` now. 

However, the actual [Beta 1 release](https://www.python.org/dev/peps/pep-0619/) is planned to happen on May 3rd, thus this tag has nothing to do with the "real" beta 1.

Not sure if that was intended? If it was, it sure seems confusing to me...

**Comment by nedbat** [comment]
Looks like there's a bogus .tgz on python.org:  https://www.python.org/ftp/python/3.10.0/Python-3.10.0b1.tgz

**Comment by hugovk** [comment]
ping 3.10 release manager @pablogsal, should this premature Python-3.10.0b1.tgz be removed? ^

**Comment by pablogsal** [comment]
> ping 3.10 release manager @pablogsal, should this premature Python-3.10.0b1.tgz be removed? ^

Hummm, absolutely. That should not be there :(

I don't know what created that tarfile but it should be deleted. I will do it today. Beta is scheduled for next week.

**Comment by pablogsal** [comment]
I just removed the bogus tarball. Should be removed from the fpt  servers soon.

**Comment by pablogsal** [comment]
Could someone revert the changes made in https://github.com/actions/python-versions/pull/92 so we are sure that that artifact won't collide with the beta that we are going to release next week?

**Comment by hugovk** [comment]
Thanks Pablo! 

@MaksimZhukov will remove the release: https://github.com/actions/python-versions/pull/92#discussion_r623007125

**Comment by pablogsal** [comment]
I will start an investigation on what process has created such tarball so this doesn't happen again. I checked and there was no other trace of this so my guess is that this has been some kind of automation or human error at some problem in the download server.

**Comment by MaksimZhukov** [comment]
Hello everyone! Thanks for the notice! 
We've removed the `3.10.0-beta.1` release from `actions/python-versions` repository in scope of [this PR](https://github.com/actions/python-versions/pull/93).

I'm closing this issue. Please let us know if you have any concerns.
