### ISSUE TITLE
Allow to specify only release level (alpha, beta, rc) instead of full version

### ISSUE THREAD

**Issue by EwoutH** [actions/setup-python#210]
For some CI runs it's not preferable to constantly update the specific level build, but are early warning systems for new (breaking) Python features. In that case you want to always use the latest version within some constrained.

To enable that, I would suggest to allow using the release levels (from the Python [development cycle](https://devguide.python.org/devcycle/). This allows using the following values for `python-version`:

- `alpha` or `a` uses the latest alpha, beta, release candidate or release build
- `beta` or `b` uses the latest beta, release candidate or release build
- `release-candidate` or `rc` uses the latest release candidate or release build
- `release` or `r` uses the latest release build

So currently `alpha` would use Python 3.10.0a7, while all others would use Python 3.9.4. When 3.10.0b1 is released, `beta` would also start using that together with `alpha`. This way you can create a staggered approach in your CI.

**Comment by agronholm** [comment]
What if I want X.Y to mean the latest development version if there is no full release yet, and only stable releases once there is at least one? Then I could add testing for prerelease versions early and not have to change my CI configuration once that version is fully released. Seems like a legitimate use case, yes?

**Comment by agronholm** [comment]
What I mean is, is there any legitimate reason to test _specifically_ against an alpha or beta if there is a stable release for X.Y available?

**Comment by e-korolevskii** [comment]
Hello @EwoutH,

Thank you for that issue. Unfortunately, setup-python (like most other setup-* actions) use SemVer notation. It`s depends on the source code of the using tools for action, so we can`t change it. 
If you have any additional questions it`s free to ask here or create a separate issue. 

Have a nice day!
