### ISSUE TITLE
`pypy-3.7` on Windows is installing the older `7.3.3` release, not `7.3.4`

### ISSUE THREAD

**Issue by davidhewitt** [actions/setup-python#211]
**Describe the bug**
The default `pypy-3.7` install on windows is still using PyPy `7.3.3` even though PyPy `7.3.4` has been released for some time now. This makes me suspect that `setup-python`'s artifact resolution has gone awry.

`pypy-3.7` on macos and linux runners is correctly using PyPy 7.3.4.

Possibly related to #196 

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [ ] Linux
- [x] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**
PyPy `7.3.4`

**To Reproduce**
1. Run the following action on a windows runner:
    ```
    uses: actions/setup-python@v2
    with:
      python-version: pypy-3.7
      architecture: x86
    ```

I expect to see a `PyPy 7.3.4` install, but the output is:

```
Successfully setup PyPy 7.3.3 with Python (3.7.9)
```

**Run/Repo Url**
All recent PyO3 CI runs, e.g. https://github.com/PyO3/pyo3/runs/2452756055

**Comment by nulano** [comment]
This action prefers installing locally cached versions over downloading the latest. The linux and macos runners have had 7.3.4 cached for a while now, but the windows images are still being deployed: https://github.com/actions/virtual-environments/pull/3267 (the PR is usually merged after the image is fully deployed for all users). If you need 7.3.4, you can specify `pypy-3.7-v7.3.4` and it will be downloaded by this action.

(Note however that you shouldn't release Windows wheels built with 7.3.4: https://foss.heptapod.net/pypy/pypy/-/issues/3443)

**Comment by nulano** [comment]
`pypy-3.7` now installs 7.3.4 for me and the PR linked above is now merged.

**Comment by davidhewitt** [comment]
Thanks, I can confirm that I am also now getting `7.3.4` installs. I should have been just a little bit more patient! 🙇
