### ISSUE TITLE
How to specify best available Python minor version

### ISSUE THREAD

**Issue by jaraco** [actions/setup-python#213]
I'd like to simply specify, "give me the best Python 3.10 you have". Ideally, "3.10" would indicate that specifier and include alphas and betas and release candidates until that version is stable at which point it would only include stable releases. I'd like not to have to specify "3.10.alpha - 3.10" (or similar) and later have to remove "alpha". If someone is specifying "3.10" before there's any stable release, couldn't that be simply interpreted to mean pre-releases until stable then just stable releases? It seems to me that's what 99% of users would require and would save a lot of toil around configs.

**Comment by dmitry-shibanov** [comment]
Hello @jaraco. Thank you for your report. Sorry for the late response. I think this [pull request](https://github.com/actions/setup-python/pull/318) should resolve your question.

**Comment by jaraco** [comment]
I don't think that PR does quite what I'd like. What I'd really like is to install the latest stable version, but to install the alpha or beta if no stable version is available. That is, I'd like to specify "3.8" and that would install 3.8.0aN until the beta is released, install 3.8.0bN until 3.8.0 is released, and then install stable releases of 3.8.X thereafter.

**Comment by ssbarnea** [comment]
I totally support @jaraco claim as we really want to be able to setup a pipeline for a newer version of python before that is released and still continue to use it after it is released, **without having to make another change to the repository to switch to stable**.

This should be achievable by ensuring that aliases include unstable versions if not stable version match is found.

**Comment by mayeut** [comment]
> If someone is specifying "3.10" before there's any stable release, couldn't that be simply interpreted to mean pre-releases until stable then just stable releases? It seems to me that's what 99% of users would require and would save a lot of toil around configs.

I do agree with @jaraco statement so I went ahead and opened a PR.

The correct syntax to specify python `3.11 pre-releases until stable then just stable releases` would be `~3.11.0-0` for now. This feels overly complicated for something as simple as that.

**Comment by jaraco** [comment]
Confirmed that syntax does have the intended effect, if somewhat awkward a syntax. Thanks!

**Comment by jaraco** [comment]
I just realized that by requiring this awkward syntax, it affects other reports downstream, such as when one uses the python version to [tag codecov environments](https://github.com/python/bedevere/blob/ad03d53e210b9c2f84733ef8f264e6831b062e40/.github/workflows/ci.yml#L47). Applying the prescribed workaround means that those codecov environments will display it as `Python_~3.10.0-0` instead of `Python_3.10`.

**Comment by aesopius** [comment]
I hope that the team maintaining this action will realise that these workaround has far more side-effect and incur costs on maintainers and finally decide to do the right thing: allow basic version selectors to use pre-releases when no release is available.

That is natural and would allow people starting to use pre-released versions of python before they go out... and not have to do other changes when python is reaches GA.

Please, do the right thing!

**Comment by IvanZosimov** [comment]
Hi, @all 👋 I recommend you to check our `X.Y-dev` [syntax](https://github.com/actions/setup-python#available-versions-of-python) because It solves the problem.

By now I'm going to close this issue, if you have any question or additions feel free to ping us.

**Comment by hugovk** [comment]
@IvanZosimov Hi! https://github.com/actions/setup-python#available-versions-of-python says:

> Use `-dev` instead of a patch number (e.g., `3.11-dev`) to install the latest patch version release for a given minor version, _alpha and beta releases included_.

I understand if I use `3.11-dev` right now, it will use the beta, and next week it will use the first release candidate ([schedule](https://peps.python.org/pep-0664/) for reference).

Are you also saying that when 3.11.0 final comes out, `3.11-dev` will use to 3.11.0 stable (I hope so), or will it stay on the last RC?

It would be even nicer to just say `3.11` and get the latest available alpha/beta/RC/stable: PR https://github.com/actions/setup-python/pull/414.

**Comment by ssbarnea** [comment]
@hugovk The workaround to your dilemma is `~3.11.0-0`, but I am still perplexed by the refusal of action team to just make "3.11" work when there are no releases yet.

**Comment by IvanZosimov** [comment]
Hi, @hugovk 👋 Yes, when 3.11.0 final comes out `3.11-dev` will install 3.11.0, there is no need to use `~3.11.0-0`.

**Comment by jaraco** [comment]
> Hi, @ALL 👋 I recommend you to check our `X.Y-dev` [syntax](https://github.com/actions/setup-python#available-versions-of-python) because It solves the problem.
> 
> By now I'm going to close this issue, if you have any question or additions feel free to ping us.

Hi Ivan. Did you see the comment above?

> I just realized that by requiring this awkward syntax, it affects other reports downstream, such as when one uses the python version to [tag codecov environments](https://github.com/python/bedevere/blob/ad03d53e210b9c2f84733ef8f264e6831b062e40/.github/workflows/ci.yml#L47). Applying the prescribed workaround means that those codecov environments will display it as `Python_~3.10.0-0` instead of `Python_3.10`.

So even though `3.11-dev` is less awkward than `~3.11.0-0`, it still adds annoying cruft to everything that relies on the python version (i.e. "-dev" appears in everything that relies on the version). I think it's going to be difficult for me to request that every action out there write `["3.8-dev", "3.9-dev", "3.10-dev"]` in their matrix just to get a nice, consistent behavior across Python versions... and if you don't write it consistently, then you once again adopt the two-phase problem, where you have to introduce `-dev` before the first stable release, carry the inconsistency until the stable release, and then remove it later.

Also, I'm surprised that `-dev` works as you describe. I would have expected `3.8-dev` today to be different than `3.8`, but you're staying there's literally no difference between the two after the first stable release is made. Is that right?

**Comment by jaraco** [comment]
In https://github.com/jaraco/skeleton/commit/325916c8240b8b3c7c41f24b664ca591e8555ea9, I've realized that the `-dev` can actually be factored out so that it doesn't have to be in the matrix, but can be in the setup invocation. If that's the recommended usage for keeping things simple, maybe you would accept a PR to the docs to present this approach as the recommended usage?

**Comment by brondsem** [comment]
@jaraco that seems like a nice approach.  However it doesn't seem to work if you have pypy versions in the matrix ☹️

**Comment by jaraco** [comment]
@IvanZosimov Can you re-open this issue, as simply appending `-dev` is not an elegant solution.

**Comment by IvanZosimov** [comment]
Hi, @jaraco 👋 Thank you for your comments! Why do you think that it's needed to reopen this issue? You found a really nice way to use `matrix` syntax together with the `-dev` syntax and this solved your problems. I think the better solution here is to open a new feature request with `-dev` syntax for Pypy if you really need it. It would be better for us to keep track of the feature request and for you to implement/check the progress of the issue.

**Comment by jaraco** [comment]
> I think the better solution here is to open a new feature request with `-dev` syntax for Pypy if you really need it.

Yes, I need that for jaraco/skeleton#63 (and others). I'll open that issue.

**Comment by webknjaz** [comment]
> I just realized that by requiring this awkward syntax, it affects other reports downstream, such as when one uses the python version to [tag codecov environments](https://github.com/python/bedevere/blob/ad03d53e210b9c2f84733ef8f264e6831b062e40/.github/workflows/ci.yml#L47). Applying the prescribed workaround means that those codecov environments will display it as `Python_~3.10.0-0` instead of `Python_3.10`.

@jaraco FYI, the Codecov bit is fixable by using the action output with the exact version: https://github.com/python/bedevere/pull/507.

**Comment by brcrista** [comment]
Reopening this -- there's some ongoing discussion at https://github.com/actions/setup-python/pull/414

**Comment by EwoutH** [comment]
I would just like to say that I support enabling to use preview Python versions without the -dev suffix, since it will reduce maintenance efforts. Thanks for the PR!
