### ISSUE TITLE
Python 3.6.9 and later patches unavailable on Windows

### ISSUE THREAD

**Issue by domdfcoding** [actions/setup-python#222]
**Describe the bug**

Looking at https://github.com/actions/python-versions/blob/main/versions-manifest.json I can see that Python 3.6.9 and later patch versions unavailable on Windows. Those releases include several security fixes; see https://docs.python.org/3.6/whatsnew/changelog.html

The releases in question are available for Linux and macOS

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [ ] Linux
- [x] Windows
- [ ] Mac

If applicable, please specify if you're using a container

**Python Versions**

* 3.6.13
* 3.6.12
* 3.6.11
* 3.6.10
* 3.6.9

**To Reproduce**

**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.

**Screenshots**

**Additional context**

**Comment by MaksimZhukov** [comment]
Hello @domdfcoding!
We do not build Python from source for Windows images, we directly download and install Python versions from [python.org](https://www.python.org/ftp/python/). Unfortunately, there are no distributions for Python 3.6.9 and later versions.

I'm going to close the issue. Feel free to contact us if you have any questions. Thanks!
