### ISSUE TITLE
Builtin pip cache

### ISSUE THREAD

**Issue by chingc** [actions/setup-python#226]
[setup-node](https://github.com/actions/setup-node) recently released a new version with builtin cache support that can be enabled simply by adding `cache` under `with`. Are there plans for setup-python to get the same convenience instead of having to use [actions/cache](https://github.com/actions/cache)?

> setup-node@v2
> 
> The action has a built-in functionality for caching and restoring npm/yarn dependencies. Supported package managers are npm , yarn .
> 
> ```
> - uses: actions/setup-node@v2
>   with:
>     node-version: '14'
>     cache: 'npm'
> ```

I asked on [github.community](https://github.community/t/setup-python-pip-cache/188356) but got no response so I figured I try here.

**Comment by chingc** [comment]
setup-java recently added [builtin cache support](https://github.com/actions/setup-java#caching-packages-dependencies) as well.

**Comment by hugovk** [comment]
Good news, a PR is at https://github.com/actions/setup-python/pull/266!

**Comment by dmitry-shibanov** [comment]
Hello everyone. We added [support for pip and pipenv caching](https://github.com/actions/setup-python/pull/266) for setup-python in [2.3.0 release](https://github.com/actions/setup-python/releases/tag/v2.3.0). Soon we'll update major tag.

**Comment by chingc** [comment]
Thank you!

**Comment by dmitry-shibanov** [comment]
Hello everyone, we've updated tag v2. It points to release `2.3.0`.
