### ISSUE TITLE
Python 2 compiled without wide unicode support

### ISSUE THREAD

**Issue by JayH5** [actions/setup-python#23]
Hi there 👋 

Not sure if this is the right forum for this (maybe a GitHub Actions VM image issue), but the version of Python 2.7 when running in a VM is not compiled with wide unicode support (`--enable-unicode=ucs4` [during the configure step](https://github.com/docker-library/python/blob/ca8eac507c34853349177cab608f237d9b664f35/2.7/buster/Dockerfile#L44)).

This seems the same on both `ubuntu-18.04` and `ubuntu-16.04` images.

Python installed from the Ubuntu repos does include wide unicode support, and so do the official Python Docker images.

This has the subtle effect that you can only install wheels built _without_ wide unicode support (`cp27m` packages), rather than the more common wide unicode support (`cp27mu`). Some popular packages (e.g. `pandas`) only build wheels with wide unicode support and so will fail to install (for various reasons) on Python 2.7 in a GitHub Actions VM. [Here](https://github.com/JayH5/github-actions-manylinux/pull/1) is some code showing this.

**Comment by asottile** [comment]
Seeing the same on azure pipelines (which is presumably the same backend)

**Comment by konradpabjan** [comment]
Python 2.7 with wide character support should now be available to everyone

![image](https://user-images.githubusercontent.com/16109154/70454641-c2833d80-1a78-11ea-93eb-2f20fce316f5.png)

**Comment by lexelby** [comment]
Seems like this is broken again on the latest python available in a ubuntu-18.04 (2.7.17).

**Comment by konradpabjan** [comment]
Yup, looks like it's busted. Thanks for the heads up 😢 Confirmed: https://github.com/konradpabjan/TestPython/runs/414015432?check_suite_focus=true

@miketimofeev I know there has been some recent work in terms of how Python gets installed on our hosted runners. Could you take a look

**Comment by lexelby** [comment]
Thanks!

To unblock my project (inkstitch/inkstitch) I switched to installing python through apt but it'd be great if I could switch back to the already-installed one in the runner.
