### ISSUE TITLE
Python `3.10rc2` support

### ISSUE THREAD

**Issue by sobolevn** [actions/setup-python#239]
I am trying to update my `3.10` setup from `beta2` to `rc2` which was released several days ago.
But, CI currently fails: https://github.com/dry-python/returns/pull/1058

```
Version 3.10.0-rc2 was not found in the local cache
Error: Version 3.10.0rc2 with arch x64 not found
```

**Comment by cclauss** [comment]
Python 3.10.0 source is now available at https://www.python.org/ftp/python/3.10.0/
