### ISSUE TITLE
Python 3.8.12 support

### ISSUE THREAD

**Issue by OldSneerJaw** [actions/setup-python#240]
Python 3.8.12 was [released](https://www.python.org/downloads/release/python-3812/) a couple weeks ago, but it does not seem to be supported by this action yet. When I attempt to specify `python-version: 3.8.12` in my CI configuration, I get this output:

```
Version 3.8.12 was not found in the local cache
Error: Version 3.8.12 with arch x64 not found
```

**Comment by dmitry-shibanov** [comment]
Hello @OldSneerJaw !
Python 3.8.12 will be added to the images with the next images rollout. Please specify full Python version to download and setup it:
```
- uses: actions/setup-python@v2
  with:
      python-version: 3.8.12
```
