### ISSUE TITLE
package.json: the version number is out of date

### ISSUE THREAD

**Issue by pzhlkj6612** [actions/setup-python#245]
Hi there!

I found the [version number](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#version) in [package.json](https://github.com/actions/setup-python/blame/2d803e7feaf26323835f529f28efa6400f18ad01/package.json#L3) has not been updated for a long time. Is this on purpose?

Thank you in advance.

**Comment by nikita-bykov** [comment]
Hello @pzhlkj6612! Thanks for your report. 
We've updated version number: `2.0.1` -> `2.2.2`
