### ISSUE TITLE
Deprecate passing floats in Python version in build file

### ISSUE THREAD

**Issue by jkterry1** [actions/setup-python#253]
Before the release of Python 3.10, many build files looks like `python-version: [3.7, 3.8, 3.9]`, maintainers such as myself then just changed this to `python-version: [3.7, 3.8, 3.9, 3.10]`. Your build parse treats these numbers without quotes as floats (which was not an obvious behavior to me at least, and like I maintain libraries with tens of millions of installations on PyPI), and so 3.10 becomes 3.1, which results in an error because you don't support Python 3.1. While you could get away with this before Python 3.10, given that it's now released and you'll need to support it for a good half decade or so and this will almost certainly be a continual source of confusion, it seems like the least bad course of action would be to deprecate and then eventually drop support for defining python versions as floats.

**Comment by nikita-bykov** [comment]
Hello @jkterry1. I'm going to close the issue, but feel free to contact us if you have any questions.
