### ISSUE TITLE
Python & PyPy versions needs to be updated to latest stable

### ISSUE THREAD

**Issue by auvipy** [actions/setup-python#269]
I have added  PR for pypy update but other python versions should be updated & upgraded as well in e2e tests

**Comment by nikita-bykov** [comment]
Hello @auvipy. Thanks for your contribution!
The main purpose of these tests is to make sure that the action works as expected with all possible ways of specifying versions, for example: `pypy-3.7`, `pypy-3.7-v7.3.5`, `pypy-3.7-v7.3.x`, `pypy-3.7-nightly` and the same for Python versions.
For now, we would not like to expand test matrix with other versions.

**Comment by posita** [comment]
What about `pypy-3.8`?

**Comment by posita** [comment]
Follow-up: It looks like #256 helps with that.

**Comment by nikita-bykov** [comment]
Hello @posita, this issue is related to "[update pypy test version as 7.3.6 is a hotfix #268](https://github.com/actions/setup-python/pull/268)" PR.
The PR you provided is related to documentation and will be reviewed separately.

**Comment by nikita-bykov** [comment]
@auvipy I am going to close the issue and the PR, but feel free to contact us if you have any questions.
