### ISSUE TITLE
GitHub Actions failing because of a python module

### ISSUE THREAD

**Issue by alanwilter** [actions/setup-python#270]
**Description:**
The original ticket is here: https://support.github.com/ticket/personal/0/1334390

Briefly:

After tens of commits to debug GitHub actions (act is really useless for me) I found and fixed the issue with:

```bash
ln -s /usr/lib/python3/dist-packages/openbabel /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/
```

Obviously this is a really poor solution. I tried to add `/usr/lib/python3/dist-packages/` to the python system path but it causes conflict.

Using `pip` to install openbabel was neither a solution as it won't install.

I understand now that GH Action env does not use Ubuntu's standard python, so my question now is if there's a env parameter for `/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/` so if I'm using a different python I will still be able to symlink openbabel lib to it.

**Action version:**
`2.283.1`
https://github.com/alanwilter/acpype/runs/3776823725?check_suite_focus=true

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

3.8.12

**Repro steps:**  
[See here](https://github.com/alanwilter/acpype/blob/9e7beb9304cc95e1f0dce56ca63210a9ba68fc99/.github/workflows/python-app.yml#L40-L53)

**Comment by alanwilter** [comment]
I realised that original ticket is not publicly accessible.

Please see below the whole story from the original ticket:

* **Bottomline**: _I got GH action to work but with a nasty solution that will stop working eventually. Looking for a more robust solution._

Working on https://github.com/alanwilter/acpype

I have a local Docker with Ubuntu 20.04 where I can "simulate" all the steps I expected GitHub Actions to execute but I'm having trouble with the python module Openbabel. Needless to say all works on my local machine but when trying on GH Actions...

I have clearly these 2 steps from my `acpype/.github/workflows/python-app.yml`:

```yaml
      - name: Install OpenBabel
        run: |
            sudo apt-get install --no-install-recommends -y openbabel

      - name: Install OpenBabel Python Module
        run: |
            sudo apt-get install --no-install-recommends -y python3-openbabel
```

I can see from the logs that I see nothing wrong with these packages installations (like in my local machine).
but when I run this step:

```yaml
      -  name: Test with PyTest
         run: |
            cd /home/runner/work/acpype/acpype/test
            acpype -di AAA.pdb -c gas
``` 

<details><summary><b>it will fail with:</b></summary>
<p>

```bash
Run cd /home/runner/work/acpype/acpype/test
  cd /home/runner/work/acpype/acpype/test
  acpype -di AAA.pdb -c gas
  pytest --color=yes
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.12/x64/lib
    DEBIAN_FRONTEND: noninteractive
    AMBERHOME: /home/runner/work/acpype/acpype/amber19-0_linux
========================================================================================
| ACPYPE: AnteChamber PYthon Parser interfacE v. 2021-02-05T22:15:50CET (c) 2021 AWSdS |
========================================================================================
DEBUG: Python Version 3.8.12 (default, Sep 13 2021, 08:28:12) 
[GCC 9.3.0]
DEBUG: Max execution time tolerance is 3h
DEBUG: setResNameCheckCoords done
WARNING: no charge value given, trying to guess one...
DEBUG: guessCharge: /usr/bin/obabel -ipdb AAA.pdb -omol2 -O AAA.mol2
DEBUG: 1 molecule converted
==> Debugging...
/home/runner/work/acpype/acpype/amber19-0_linux/bin/antechamber -dr no -i /home/runner/work/acpype/acpype/test/.acpype_tmp_AAA/AAA.mol2 -fi mol2 -o tmp -fo mol2 -c gas -pf n
==> Debugging...
DEBUG: /home/runner/work/acpype/acpype/amber19-0_linux/bin/antechamber -dr no -i tmp -fi mol2 -o tmp -fo mol2 -c wc -cf tmp.crg -pf n
++++++++++start_quote+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Welcome to antechamber 19.0: molecular input file processor.


---Judge bond type for Residue 1 with ID of 1 and Name of ALA ---

---Judge bond type for Residue 2 with ID of 2 and Name of ALA ---

---Judge bond type for Residue 3 with ID of 3 and Name of ALA ---

++++++++++end_quote+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DEBUG: readMol2TotalCharge: -2.9999999999891225e-06
DEBUG: Net charge drift '0.000003'
==> ... charge set to 0
==> ... converting pdb input file to mol2 input file
DEBUG: /usr/bin/obabel -ipdb AAA.pdb -omol2 -O AAA.mol2
==> * Babel OK *
==> Executing Antechamber...
==> Debugging...
DEBUG: /home/runner/work/acpype/acpype/amber19-0_linux/bin/antechamber -dr no -i AAA.mol2 -fi mol2 -o AAA_gas_gaff.mol2 -fo mol2 -c gas -nc 0 -m 1 -s 2 -df 2 -at gaff -pf n 
==> * Antechamber OK *
DEBUG: /home/runner/work/acpype/acpype/amber19-0_linux/bin/parmchk2 -i AAA_gas_gaff.mol2 -f mol2 -o AAA_AC.frcmod
==> * Parmchk OK *
==> Executing Tleap...
DEBUG: /home/runner/work/acpype/acpype/amber19-0_linux/bin/tleap -f tleap.in
++++++++++start_quote+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Checking 'ALA'....
Checking parameters for unit 'ALA'.
Checking for bond parameters.
Checking for angle parameters.
Unit is OK.
++++++++++end_quote+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
==> * Tleap OK *
DEBUG: prmtop and inpcrd files loaded
DEBUG: basename defined = 'AAA'
DEBUG: getCoords done
DEBUG: getABCOEFs done
DEBUG: charge to be balanced: total -0.0000030012
DEBUG: balanceCharges done
DEBUG: Balanced TotalCharge -0.0000000000
DEBUG: PBC = None
DEBUG: getAtoms done
DEBUG: getBonds done
DEBUG: getAngles done
DEBUG: getDihedrals done
ACPYPE FAILED: No module named 'openbabel'
  File "/usr/local/bin/acpype", line 5263, in init_main
    molecule.createMolTopol()
  File "/usr/local/bin/acpype", line 2571, in createMolTopol
    self.molTopol = MolTopol(
  File "/usr/local/bin/acpype", line 4898, in __init__
    self.getChirals()
  File "/usr/local/bin/acpype", line 2921, in getChirals
    if checkOpenBabelVersion() >= 300:
  File "/usr/local/bin/acpype", line 1196, in checkOpenBabelVersion
    import openbabel as obl
Total time of execution: less than a second
Error: Process completed with exit code 19.
```
</p>
</details>

I have no idea how to debug this scenario, how come the openbabel library is not there?


---------(then)---------

After tens of commits to debug GitHub actions (`act` is really useless for me) I found and fixed the issue with:

```bash
ln -s /usr/lib/python3/dist-packages/openbabel /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/
```

Obviously this is a really poor solution. I tried to add `/usr/lib/python3/dist-packages/` to the python system path but it causes conflict.

Using `pip` to install openbabel was neither a solution as it won't install.

I understand now that GH Action env does not use Ubuntu's standard python, so my question now is if there's a env parameter for `/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/` so if I'm using a different python I will still be able to symlink openbabel lib to it.

So my current solution is below.
See https://github.com/alanwilter/acpype/blob/9e7beb9304cc95e1f0dce56ca63210a9ba68fc99/.github/workflows/python-app.yml#L40-L53

```yaml
...            
      - name: Install OpenBabel
        run: |
            sudo apt-get install --no-install-recommends -y openbabel

      - name: Install OpenBabel Python Module and Hack it <<<<< CREATE a symlink!
        run: |
            sudo apt-get install --no-install-recommends -y python3-openbabel
            ln -s /usr/lib/python3/dist-packages/openbabel /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/
...
```

**Comment by nikita-bykov** [comment]
Hello @alanwilter.
Unfortunately we don't have any environment variables for paths like `/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/`.
We can suggest you to use `$pythonPath` env variable to get the required path. In your case it contains `/opt/hostedtoolcache/Python/3.8.12/x64`. So you can replace `/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/`  by `$pythonLocation/lib/python*`.

**Comment by alanwilter** [comment]
Thanks for that but could you save me the guess work since I tried many ways and it's all failing. How on earth do I set the env in the yaml file?

```
ln -s /usr/lib/python3/dist-packages/openbabel ${{ env.pythonPath }}/lib/python3.8/
```
Does not work
Neither `${{ pythonPath }}`, `$pythonPath`.

This is so cumbersome in GitHub actions.

**Comment by dmitry-shibanov** [comment]
Hello @alanwilter. Thank you for your response. Could you please try to use `pythonLocation` environment variable. Could you please try this snippet:
```
ln -s /usr/lib/python3/dist-packages/openbabel $pythonLocation/lib/python3.8/
```

**Comment by alanwilter** [comment]
Hooray, it did work, thanks.
