### ISSUE TITLE
`pip cache not found`

### ISSUE THREAD

**Issue by Stanzilla** [actions/setup-python#278]
**Description:**
Updated to the new action 2.3.0 and added `cache: "pip"` to my workflow

**Action version:**
2.3.0

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

3.8.12

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

See description

**Expected behavior:**
Working cache

**Actual behavior:**
Run actions/setup-python@v2.3.0
Successfully setup CPython (3.8.12)
/opt/hostedtoolcache/Python/3.8.12/x64/bin/pip cache dir
/home/runner/.cache/pip
pip cache is not found

**Comment by skeggse** [comment]
Did you resolve this?

**Comment by Stanzilla** [comment]
Yeah, it started working after a few builds.
