### ISSUE TITLE
Python 2.7 setup runtime unable to successfully install packages

### ISSUE THREAD

**Issue by matthewfeickert** [actions/setup-python#28]
Hi. In a [recent PR on a project I work on](https://github.com/diana-hep/pyhf/pull/584#issuecomment-535245889) I tried to move testing of Python 2.7 from Travis CI to GitHub Actions. In doing so I found that the Python 2.7 runtime setup by `setup-python` has the tests fail as it is unable to install TensorFlow during the the Install dependencies step.

I've made a minimal failing example in the following repo: [test-setup-python-action](https://github.com/matthewfeickert/test-setup-python-action). [Here I show](https://github.com/matthewfeickert/test-setup-python-action/commit/c8755abf3ed99fa1180847a90852c72043cc3653/checks) that if I only have `setup-python` setup Python 3.6 and Python 3.7 runtimes the installation is able to succeed and the GitHub Action finishes. If I then also ask for `setup-python` to setup Python 2.7 [it fails quickly](https://github.com/matthewfeickert/test-setup-python-action/commit/993fbb63972d2fa4965c79ab5a7433dc1995f689/checks). Unless I've misunderstood something about how `setup-python` works this seems to show that there is something about the Python 2.7 runtime that is setup which is causing installation issues. Additionally, I have checked that the installation with Python 2.7 [works fine in the Python 2.7 Docker image](https://github.com/diana-hep/pyhf/pull/584#issuecomment-535347894).

I realize I'm simply reporting information rather then actually pointing to anything specific. If I can be of help in trying to fix this in any way please let me know, as my project would love to be able to fully move our testing to GitHub Actions. 

Also, thanks for making the `setup-python` action! It is great!

cc @kratsg @lukasheinrich

**Comment by matthewfeickert** [comment]
I'm tagging @bryanmacfarlane as [this comment](https://github.com/actions/setup-python/issues/30#issuecomment-542243912) makes it seem like they are now in charge of the setup-python Action.

**Comment by JayH5** [comment]
You may have hit the same problem I did with #23

**Comment by matthewfeickert** [comment]
> You may have hit the same problem I did with #23

Very possibly. Thanks for alerting me to your issue!

**Comment by bryanmacfarlane** [comment]
@madhurig team owns

**Comment by konradpabjan** [comment]
Python 2.7 on ubuntu 1604 and 1804 is being rebuilt with ucs4 so it should fix any packages that fail to install

**Comment by matthewfeickert** [comment]
> Python 2.7 on ubuntu 1604 and 1804 is being rebuilt with ucs4 so it should fix any packages that fail to install

Sounds good. So watch this space/check back in a few weeks?

**Comment by konradpabjan** [comment]
New version of 2.7 is compiled and it's just awaiting deployment to all vms. 

Nov 18th-20th is my rough estimate for when it should roll out everywhere. Normally we do weekly deployments but due to Github Universe happening next week we're not going to be pushing out any new changes.

**Comment by konradpabjan** [comment]
#23 has been closed out so it should be possible to install all types of packages with 2.7 that required wide-character support

![image](https://user-images.githubusercontent.com/16109154/70454844-2ad21f00-1a79-11ea-9eb9-6128e831cfa7.png)

**Comment by matthewfeickert** [comment]
Thanks @konradpabjan!
