### ISSUE TITLE
Update @actions/cache version to 1.0.8 

### ISSUE THREAD

**Issue by aparna-ravindra** [actions/setup-python#280]
**Description:**
The action depends on [`@actions/cache`](https://github.com/actions/setup-python/blob/3ef38b826b0d09ce746cd326f8cdfa37933f0d6d/package.json#L26). The latest version `1.0.8` is now available and it supports upto 10GB cache upload. 

**Justification:**
Support 10GB cache upload using the latest version `1.0.8` of [`@actions/cache` ](https://www.npmjs.com/package/@actions/cache)

**Are you willing to submit a PR?**
Yes

**Comment by nikita-bykov** [comment]
Hello @aparna-ravindra. Thanks for your feature request! 
We have successfully updated `@actions/cache` to `1.0.8` version and created the [release](https://github.com/actions/setup-python/releases/tag/v2.3.1) for it. New changes are already available under the `v2` tag!
I'm going to close the issue, but feel free to contact us if you have any questions.
