### ISSUE TITLE
(node:1605) [DEP0005] DeprecationWarning: Buffer() is deprecated.

### ISSUE THREAD

**Issue by XhmikosR** [actions/setup-python#286]
**Description:**

I know it's just a warning, but it should probably be fixed.

**Action version:**

2.3.0

**Platform:**

- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**

- [X] Hosted
- [ ] Self-hosted

**Tools version:**

3.8.12 but it's probably unrelated to the Python version

**Repro steps:**  

* https://github.com/pi-hole/docs/blob/dev/.github/workflows/ci.yml
* https://github.com/pi-hole/docs/runs/4345322222?check_suite_focus=true#step:3:14

**Expected behavior:**

No warnings to show

**Actual behavior:**

```
(node:1605) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by nikita-bykov** [comment]
Hello @XhmikosR, thank you for report!
We have just [released](https://github.com/actions/setup-python/releases/tag/v2.3.1) a new version of setup-python, which is already available by tag `v2`. This update helped me get rid of the warning. Could you please confirm if this works for you?

**Comment by XhmikosR** [comment]
Yup, confirmed, all good now!
