### ISSUE TITLE
Support custom Python versions

### ISSUE THREAD

**Issue by SerVB** [actions/setup-python#29]
My project requires Python 2.7.7 because it has to be compatible with a game that uses this version. It will be cool if the `setup-python` supports old versions. Now it doesn't:

```
##[error]Version 2.7.7 with arch x64 not found
Available versions:

2.7.16 (x64)
3.5.7 (x64)
3.6.9 (x64)
3.7.4 (x64)
##[error]Node run failed with exit code 1
```

So I have to add script to install it manually:

<https://github.com/SerVB/TheRecentStatOfYou/blob/cc20ecf4e2f530feb219a9e28dfd7aea847ea6a6/.github/workflows/build.yml#L9-L21>

Can you implement executing these lines if the version not in [2.7.16, 3.5.7, 3.6.9, 3.7.4]? My script will be much smaller!

**Comment by konradpabjan** [comment]
We deliberately choose to only include a single major/minor version of Python in the tools cache. `2.7.16` is the most recent version of Python 2.7. Every time there is an update, we remove the old version (example going from Python 3.5.8 -> 3.5.9). 

Manually installing a specific older version of Python is the best solution we can recommend.

**Comment by SerVB** [comment]
That's pity... Could you share reasons?

**Comment by pcraciunoiu** [comment]
Heroku requires a python version pinned AFAIK, and so every time the latest version changes in GitHub actions, builds break for our projects. This is costing us a lot of time, and is not something I had to deal with for CircleCI. If we were to manually install, I assume it would be slower and cost more in build time? Seems to me like you can at least support a version for a month or an overlap period.
