### ISSUE TITLE
Support a `.python-version` file

### ISSUE THREAD

**Issue by indifferentghost** [actions/setup-python#291]
**Description:**
The [2.5.0 release of _actions/setup-node_](https://github.com/actions/setup-node/releases/tag/v2.5.0) released support determine the node version via an `.nvmrc` file at the root. I think it'd be prudent to use the [_pyenv_ standard of a `.python-version` file](https://github.com/pyenv/pyenv#choosing-the-python-version) to support this.

**Justification:**
It'd be nice to be DRY when specifying versions across multiple actions.

**Are you willing to submit a PR?**

**Comment by nikita-bykov** [comment]
Hello @indifferentghost, thanks for your feature request! We will look at it.

**Comment by indifferentghost** [comment]
Using a `.*-version` file is already defined by [ruby/setup-ruby](https://github.com/ruby/setup-ruby#supported-version-syntax) as well.

**Comment by fregante** [comment]
I'll append my request for [Heroku’s `runtime.txt` format](https://devcenter.heroku.com/articles/python-runtimes)
