### ISSUE TITLE
pypy3 does not install latest

### ISSUE THREAD

**Issue by avylove** [actions/setup-python#296]
**Description:**
I want to use the latest stable pypy release for 3.x. I didn't see a way to do this in the docs, but the action did accept `pypy3`, however this installs 3.6.12, which looks like the latest version of 3.6 in [versions.json](https://downloads.python.org/pypy/versions.json).

If there is another way to use the latest version of 3.x, please let me know. I think this is a bug either way, as it is intuitive and accepted, yet doesn't provide intuitive behavior.

**Action version:**
actions/setup-python@v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
pypy3.x

**Repro steps:** 
You can see in this [workflow](https://github.com/Rockhopper-Technologies/enlighten/runs/4494094119?check_suite_focus=true), under the pypy3 job.

`matrix.python-version` is set to `pypy3`

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

**Expected behavior:**
The latest stable version supporting Python 3.x should be installed

**Actual behavior:**
pypy3.6 (3.6.12) is installed

**Comment by nikita-bykov** [comment]
Hello @avylove!
`pypy3` is old syntax and points only to 3.6 (more information you can find in [this PR](https://github.com/actions/setup-python/pull/168#issue-766477901)). You have to specify the PyPy version as stated in the [documentation](https://github.com/actions/setup-python#specifying-a-pypy-version).
For example `pypy-3.8` if you want to use the latest release for now.
I'm going to close the issue, but feel free to contact us if you have any questions.

**Comment by avylove** [comment]
I'm sorry, but this still seems like a bug. The behavior is not mentioned in the documentation, does not produce a deprecation warning, and does not behave as one would expect. I think there are a few options to remediate:

1.) Print a deprecation warning and plan to retire old behavior
2.) Make pypy3 point to latest 3.x version

In the very least, the behavior should be documented with the other options.

I'll put in a separate feature request to specify the latest 3.x behavior.
