### ISSUE TITLE
Request for Python 3.10.1 support

### ISSUE THREAD

**Issue by achimnol** [actions/setup-python#299]
**Description:**
Please add Python 3.10.1 in addition to 3.10.0.
I think the maintainers may have your own schedules to periodically check and update, but just want to point out that Python's official release cycle follows a two-months patch release cadence, so it might be good to revisit here on every two month. :wink:

**Justification:**
[Some of bug fixes in 3.10.1](https://docs.python.org/3/whatsnew/changelog.html#python-3-10-1-final) are required to run my projects, such as:

> [bpo-45416](https://bugs.python.org/issue45416): Fix use of `asyncio.Condition` with explicit `asyncio.Lock` objects, which was a regression due to removal of explicit loop arguments. Patch by Joongi Kim.

**Are you willing to submit a PR?**

I tried but could not figure out how to "build and post" a specific Python version here.
Just following "If there is a specific version of Python that is not available, you can open an issue here".

**Comment by nikita-bykov** [comment]
Hello @achimnol, thanks for your request!
Python 3.10.1 is already available for installation using setup-python on Windows and Ubuntu images, and will be available on macOS later.
I'll let you know as soon as it is ready for use on macOS.

**Comment by achimnol** [comment]
Oh, I confirmed that 3.10.1 is now available in my GitHub Actions workflows. Thanks!
