### ISSUE TITLE
Syntax to specify the latest stable major release

### ISSUE THREAD

**Issue by avylove** [actions/setup-python#300]
**Description:**
Add syntax to specify the latest stable major release. For example pypy-3. The ask is specifically for PyPy, but could apply more generally as well.

**Justification:**
Some library maintainers like to validate their packages work with PyPy, but generally only test on the latest stable version. This is primarily to catch unexpected inconsistencies between Cython and PyPy. The idea is to set it up once and only worry about it if a PyPy-specific bug comes up. In the current syntax, a maintainer is required to periodically check to see if there is a new major PyPy version. This is enough friction that some maintainers will drop testing PyPy altogether or pick the current latest and never revisit it. 

**Are you willing to submit a PR?**
I would if I had the cycles

**Comment by nikita-bykov** [comment]
Hello @avylove, thanks for your feature request! We will look at it.

**Comment by IvanZosimov** [comment]
Hi, @avylove 👋 ! Thank you for this issue and sorry for the late response. Unfortunately, I'm going to close this issue as a copy of [one already created and closed in the past](https://github.com/actions/setup-python/issues/360) - there you can find the motivation also.
