### ISSUE TITLE
`python-version: ['3.11.0-alpha - 3.11.0']` brings alpha.2 not alpha.3

### ISSUE THREAD

**Issue by SamuelMarks** [actions/setup-python#302]
**Description:**
Penultimate version selected incorrectly

**Action version:**
3.11

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
```yml
python-version: ['3.11.0-alpha - 3.11.0']
```

https://github.com/offscale/cdd-python/blob/7b4066d/.github/workflows/main.yml

**Expected behavior:**
Always bring in latest 3.11 version (this syntax worked for 3.10 and I think I used it on 3.9 also)

**Actual behavior:**
https://github.com/offscale/cdd-python/runs/4542720759

**Comment by nikita-bykov** [comment]
Hello @SamuelMarks, thanks for your request!
Python 3.11.0-alpha.3 is not currently available for installation with setup-python, we are working on adding it.
I'll let you know as soon as it is ready for use.

**Comment by nikita-bykov** [comment]
Hello @SamuelMarks, Python 3.11.0-alpha.3 version is already available via the setup-python action.
I'm going to close the issue, but feel free to contact us if you have any questions.
