### ISSUE TITLE
After running setup python for 3.6, 3.8 is also available

### ISSUE THREAD

**Issue by thomasborgen** [actions/setup-python#310]
**Description:**

After running actions/steup-python@v1 with 3.6, python 3.8 is also available.

I stumbled upon a problem with the python versions after removing support for python 3.6 in my `pyproject.toml` without removing the tests for `3.6` in my github workflows. The test passed and I Dug deeper. Turns out `poetry` correctly prints that 3.6 is not supported but also looks for supported installed versions. Then it finds python 3.8 and runs the tests with that.

The output of the two interesting steps are:

```sh
Run actions/setup-python@v1
  with:
    python-version: 3.6
    architecture: x64
Successfully setup CPython (3.6.15)
```

And then the poetry install step:

```sh
Run poetry config virtualenvs.in-project true
  poetry config virtualenvs.in-project true
  poetry install
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.6.15/x64
The currently activated Python version 3.6.15 is not supported by the project (^3.7).
Trying to find and use a compatible version. 
Using python3.8 (3.8.10)
```

Last line there says `Using python3.8 (3.8.10)` 

**Action version:**
v1

**Platform:**
- [ x ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ x ] Hosted
- [ ] Self-hosted

**Tools version:**
`3.6`

**Repro steps:**  

[repo to reproduce](https://github.com/thomasborgen/github-python36-also-has-38-available)
[direct link to actions](https://github.com/thomasborgen/github-python36-also-has-38-available/runs/4618191019?check_suite_focus=true)

**Expected behavior:**
When I ask for python `3.6` I expect that only `3.6.x` is available

**Actual behavior:**
`3.8` is also installed and available somehow.

**Comment by thomasborgen** [comment]
So I found the culprit. I use `runs-on: ubuntu-latest` which comes preinstalled with `python 3.8`. Running some other image will solve it. I'll post back when I have a fix so if anyone else has the same problem it might show up when they google ^^

**Comment by thomasborgen** [comment]
The docs for setup-python actually uses `ubuntu-latest`, so maybe it would be beneficial with a heads up about this.

**Comment by shelper** [comment]
@thomasborgen Just wonder how you resolved this issue, I have the opposite case, where I use ubuntu-18.04, and specified the python version for setup-python, then i got an error saying: 
`The currently activated Python version 3.6.9 is not supported by the project (^3.7.1).`

i already have python version set to 3.8 for setup-python but seems it does not work. and i have to manually do :
`poetry env use 3.8` to resolve this, but then the caching of poetry does not work....

if you haven't find a solution for this, then  maybe we should reopen this issue...

**Comment by thomasborgen** [comment]
@shelper 
Sry for the late reply

The problem i faced was with ubuntu-latest coming preinstalled with py 3.8. to fix my problem one would have to specify python version like you did. This problem has roots in the fact that poetry looks for supported versions. 

Your problem however seems to me is setup python not setting the default python to the one specified in the yaml. So I don't think it's related. 

I would open a new issue, and also double check your yaml against someone else's.
