### ISSUE TITLE
Latest versions of packages not available via pip

### ISSUE THREAD

**Issue by ross** [actions/setup-python#317]
**Description:**

I've run into problems a few times now across a number of (similar) repos where the latest versions of packages are available locally and in locally built docker containers, but fail when run inside of an actions job. I have helper scripts that keep my requirements.txt files up to date, but when I use them I end up having to make multiple rounds of bumping specific packages back down a version (or two) to use things available in actions.

E.g. most recent encounter https://github.com/octodns/octodns-route53/pull/2
* https://github.com/octodns/octodns-route53/runs/4777277388?check_suite_focus=true
* https://github.com/octodns/octodns-route53/runs/4777323220?check_suite_focus=true

Digging into the first one:

```
ERROR: Could not find a version that satisfies the requirement importlib-metadata==4.10.0 (from versions: 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.6.1, 1.7.0, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 3.0.0, 3.1.0, 3.1.1, 3.2.0, 3.3.0, 3.4.0, 3.5.0, 3.6.0, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.8.0, 3.8.1, 3.8.2, 3.9.0, 3.9.1, 3.10.0, 3.10.1, 4.0.0, 4.0.1, 4.1.0, 4.2.0, 4.3.0, 4.3.1, 4.4.0, 4.5.0, 4.6.0, 4.6.1, 4.6.2, 4.6.3, 4.6.4, 4.7.0, 4.7.1, 4.8.0, 4.8.1, 4.8.2, 4.8.3)
ERROR: No matching distribution found for importlib-metadata==4.10.0
Error: Process completed with exit code 1.
```

`importlib-metadata` cut 2 releases in mid-December, one on the 16th the other on 19th, https://pypi.org/project/importlib-metadata/#history. They're both available locally & in docker containers, but not showing up when things run in actions. 

I've dug around in the action and don't see anything obvious that would lead to this problem. I'm also not sure if the issue is with the setup-python action or something awry in the underlying `ubuntu-latest` image, but this seems like the place to start. 

I've been running into this for the past couple weeks, but thought I'd give it some time to see if it's just something temorary, which it doesn't appear to be.

**Action version:**

[`actions/setup-python@v2`](https://github.com/octodns/octodns-route53/blob/0fa1c0075c41f88cf3c73d2a0ca25b66ace4b59c/.github/workflows/main.yml#L14)

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

I'm seeing it with [`python-version: [3.6, 3.7, 3.8, 3.9]`](https://github.com/octodns/octodns-route53/blob/0fa1c0075c41f88cf3c73d2a0ca25b66ace4b59c/.github/workflows/main.yml#L10)

**Repro steps:**  

First two failures in https://github.com/octodns/octodns-route53/pull/2, e.g. https://github.com/octodns/octodns-route53/pull/2/commits/3b663301fad1d8e444da2b39adf73eb492fd8ada

**Expected behavior:**

Packages that show up on pypi and are available locally work within the actions context.

**Actual behavior:**

Things appear to be stale, perhaps pulling from a mirror that's not up to date?

**Comment by nikita-bykov** [comment]
Hello @ross, thanks for report! 
We'll look at your issue.

**Comment by hugovk** [comment]
This is working as expected.

importlib-metadata 4.10.0 does not support EOL Python 3.6, see the "Requires: Python >=3.7" at:

https://pypi.org/project/importlib-metadata/4.10.0/#data

So you need to either also drop EOL 3.6 (my recommendation) or make your pins conditional on the Python version.

**Comment by ross** [comment]
> importlib-metadata 4.10.0 does not support EOL Python 3.6, see the "Requires: Python >=3.7" at:

Ah. I hadn't noticed that it was 3.6 only failing, I guess maybe it was failing early and stopping the others from succeeding so I didn't catch it only being a problem with 3.6. 

Since it's date has passed, https://devguide.python.org/devcycle/#end-of-life-branches I'll just remove it from my versions matrix.

**Comment by ross** [comment]
Will reopen if that turns out not to be the problem. Sorry for the noise.

**Comment by hugovk** [comment]
Yeah, it helps to have `fail-fast: false` on the CI so it doesn't auto-cancel all the other jobs if one fails. I've made https://github.com/octodns/octodns-route53/pull/4 to add that.

(I think it'd be better if GHA had it `false` by default, but that's another issue :)
