### ISSUE TITLE
Python 3.11.0-alpha.4 isn't available for Windows?

### ISSUE THREAD

**Issue by nedbat** [actions/setup-python#322]
**Description:**
The current versions of Python include 3.11.0-alpha.4, but only for Linux and Mac: https://github.com/actions/python-versions/blob/7e70acf5f2887a2366c5ca12a8896a82ce12716e/versions-manifest.json

alpha.3 and earlier are available for Windows.  Is there a reason we can't also have alpha.4?

**Action version:**
@v2

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

3.11.0-alpha.4

**Comment by MaksimZhukov** [comment]
Hello @nedbat! Thank you for the report! We've published Python 3.11.0-alpha.4 for Windows, so you can now use it via setup-python action.
