### ISSUE TITLE
When running Python setup in Windows VM fails with pip

### ISSUE THREAD

**Issue by aaltat** [actions/setup-python#333]
**Description:**
We have matrix job which setups [Python](https://github.com/MarketSquare/robotframework-browser/blob/main/.github/workflows/on-push.yml#L54). For Linux and Mac that Python setup works fine, but for Windows host, there is error like this:
```
Successfully setup CPython (3.7.9)
C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\pip.exe cache dir
Error: The process 'C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\pip.exe' failed with exit code 3221225477
```

**Action version:**
`actions/setup-python@v2`

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
3.7, 3.8, 3.9

**Repro steps:**  
Link to [yaml](https://github.com/MarketSquare/robotframework-browser/blob/main/.github/workflows/on-push.yml#L54) definition and here is link to [execution](https://github.com/MarketSquare/robotframework-browser/runs/5065014398?check_suite_focus=true) 

**Expected behavior:**
Python would be setup would have been completed without errors. 

**Actual behavior:**
There is error: 
```
Successfully setup CPython (3.7.9)
C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\pip.exe cache dir
Error: The process 'C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\pip.exe' failed with exit code 3221225477
```

**Comment by hugovk** [comment]
Duplicate of https://github.com/actions/setup-python/issues/328? 

Does `actions/setup-python@v2.3.2` work?

**Comment by aaltat** [comment]
Well, could be duplicate. Although my problems happens in setup phase. 

But using `actions/setup-python@v2.3.2` fixes the problem, thank you.

**Comment by aaltat** [comment]
Do I need to always keep updating the version? Because I tough that using `actions/setup-python@v2` would always give me latest and greatest version.

**Comment by dmitry-shibanov** [comment]
Hello @aaltat. The tag v2 should be updated. Could you please confirm, that everything works as expected ?

**Comment by aaltat** [comment]
Yes, now it works. Thank you.
