### ISSUE TITLE
PyPy 3.7 on ubuntu latest has an outdated sqlite

### ISSUE THREAD

**Issue by Ian-Foote** [actions/setup-python#339]
**Description:**
Since today, the version of sqlite3 available in PyPy 3.7 is 3.7.17, not the expected 3.31.1.

**Action version:**
actions/setup-python@v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
PyPy-3.7

**Repro steps:**  
Create a workflow on ubuntu latest with python version PyPy-3.7 and check the sqlite version:
https://github.com/Ian-Foote/pypy-sqlite-bug

**Expected behavior:**
I expect the sqlite3 version to be `3.31.1` (or something similarly modern)

**Actual behavior:**
The sqlite3 version is `3.7.17`.

**Comment by nikita-bykov** [comment]
Hello @Ian-Foote, thanks for the report!
We'll take a look.

**Comment by hashlash** [comment]
Btw, the action used in jazzband/django-defender/pull/203 is using PyPy-3.8. Maybe the other PyPy versions are affected too.

**Comment by nikita-bykov** [comment]
Hello @Ian-Foote. 
Looks like it's `PyPy 7.3.8` issue, the [same ticket](https://foss.heptapod.net/pypy/pypy/-/issues/3690) was created in the PyPy repository as I can see.
When you specify PyPy version in the format `pypy-<python_version>`, setup-python will use the latest PyPy for specified Python version (this is `PyPy 7.3.8` in case of `Python 3.7`). 
As a workaround, we can suggest you to use the [full format](https://github.com/actions/setup-python#specifying-a-pypy-version) to specify PyPy version and point to previous version, such as 7.3.7:
```
- uses: actions/setup-python@v2
  with:
    python-version: 'pypy-3.7-v7.3.7'
```

**Comment by marko-zivic-93** [comment]
Hello @Ian-Foote 
Due to the fact that this issue is not related to setup-python repo I will close this issue.
For fixing the issue you experienced, please find the comment posted by @nikita-bykov above.
If you have any additional questions or concerns, please feel free to create a new issue or to re-open this one.

**Comment by hashlash** [comment]
PyPy 7.3.9 has now been [released](https://doc.pypy.org/en/latest/release-v7.3.9.html) with the updated SQLite version.
