### ISSUE TITLE
One version of Python 3.7 is no longer available on all OSes

### ISSUE THREAD

**Issue by matchai** [actions/setup-python#34]
Until recently, I have been using Python 3.7.4 for cross-platform testing. Now that 3.7.4 has been removed from the tool cache on Ubuntu, there is no longer a version of Python 3.7 available for cross-platform testing.

Here is a sample run:
https://github.com/starship/starship/runs/282675872

**Comment by dominicroessner** [comment]
Same for us, running on ubuntu-latest with Python 3.7.4 on a private repo. 

Workflow:
```
      - name: Use Python 3.7.4
        uses: actions/setup-python@v1
        with:
          python-version: "3.7.4"```

Log:
```Run actions/setup-python@v1
##[error]Version 3.7.4 with arch x64 not found
Available versions:

2.7.16 (x64)
3.5.7 (x64)
3.6.9 (x64)
3.7.5 (x64)
3.8.0 (x64)
##[error]Node run failed with exit code 1```

**Comment by JasonFreeberg** [comment]
+1 
Happened to me too. My app doesn't depend on a minor version so I changed the version to `"3.7.x"`.

**Comment by madhurig** [comment]
The [guidelines on what's installed in the virtual environments for GitHub Actions](https://github.com/actions/virtual-environments#guidelines-for-whats-installed) vary based on the toolset. For Python we chose to automatically update the minor versions but will announce if we are removing any major versions. So, we replaced Python 3.7.4 with 3.7.5. When we removed Python 3.4, we posted a [change log](https://github.blog/changelog/2019-10-17-github-actions-removing-python-3-4-and-ruby-2-3-from-the-virtual-environments/). 

We are looking for ways to communicate this better. Having this called out in the readme here seems useful. Let us know if you have any other suggestions.

**Comment by matchai** [comment]
@madhurig My biggest pain point is not the communication of version updates but is the staggered timing of image updates across platforms. We have no way of using the same Python version across all OSes, ensuring our tests are running consistently across all supported platforms.

Would it be possible to keep the previous minor until the latest minor is made available on all OSes? (e.g. both 3.7.4 and 3.7.5 are on the latest image, then 3.7.4 is removed on the next image)

**Comment by madhurig** [comment]
@matchai - good point and thanks for bringing this up. The virtual environment updates are not synchronized as you have found. The solution you are suggesting seems reasonable. We will attempt that for future updates.
