### ISSUE TITLE
Getting kill signal during Actions CI

### ISSUE THREAD

**Issue by sarthakpati** [actions/setup-python#350]
**Description:**
Hi,

I am getting a weird kill signal error when performing CI for [this PR](https://github.com/CBICA/GaNDLF/pull/327) with the following error [[ref](https://github.com/CBICA/GaNDLF/runs/5467115669?check_suite_focus=true)]:

```
  pytest --cov=. --cov-report=xml
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.12/x64/lib
============================= test session starts ==============================
platform linux -- Python 3.7.12, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/runner/work/GaNDLF/GaNDLF
plugins: cov-3.0.0
collected 30 items

/home/runner/work/_temp/0dbe16bb-3052-4a6e-9755-00561fed9f22.sh: line 1:  2930 Killed                  pytest --cov=. --cov-report=xml
testing/test_full.py .......
Error: Process completed with exit code 137.
```

I have also tried updating `setup-python` to `v3.0.0` but I am getting the same error. Any help would be greatly appreciated! 

**Action version:**
2 and 3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Python 3.7

**Repro steps:**  
- Repo: https://github.com/CBICA/GaNDLF
- Workflow: https://github.com/CBICA/GaNDLF/blob/master/.github/workflows/python-test.yml
- PR in question: https://github.com/CBICA/GaNDLF/pull/327

**Expected behavior:**
The weird thing is that no other PR for this repo is getting affected [[1](https://github.com/CBICA/GaNDLF/pull/331),[2](https://github.com/CBICA/GaNDLF/pull/329),[3](https://github.com/CBICA/GaNDLF/pull/303)], and the error is coming when pytest is collecting tests, not when it is executing them. I am able to run the tests without issue on my local machine.

**Actual behavior:**
The CI build is failing while trying to collect the targets for pytest.

**Comment by vsafonkin** [comment]
Hi @sarthakpati, this issue is still actual for you?

**Comment by sarthakpati** [comment]
Oh, no, I have fixed it. Thanks!

**Comment by roshanrjn14** [comment]
@sarthakpati can you please let me know how you fixed this? even am also getting the same issue

**Comment by roshanrjn14** [comment]
@sarthakpati  is it not bcs of memory issue of hosted runner in github?
<img width="689" alt="SS" src="https://user-images.githubusercontent.com/105373156/200856556-769a8f79-73cb-4a41-96f3-3518dd7870d3.PNG">
 
I have attached the SS of issue which am facing while running the tests.

**Comment by GitToby** [comment]
having the same issue on https://github.com/GitToby/data-processing-benchmarks

@sarthakpati @roshanrjn14 

any pointers on how to fix it?

**Comment by GitToby** [comment]
I mean I'm doing some processing on data up to 1GB but it's not all loaded into memory at the same time.. I couldn't see any hard limits in any docs anywhere, there's no warning dialogues for high memory usage either.

Any tools you recommend for monitoring this stuff?
