### ISSUE TITLE
Allow specifying pip cache dependencies inline in the yaml

### ISSUE THREAD

**Issue by ben-spiller** [actions/setup-python#351]
**Description:**
The new functionality to take care of caching dependencies is great. However I'd love to be able to specify the versions of Python third parties in-line in my yaml rather than in a separate requirements.txt file. 

For example:

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
          # Enabled caching of dependencies
          cache: pip
          cache-dependencies: |
              pysys==2.0 
              coverage==3.5

**Justification:**
For non-Python repos that just happen to use Python, having a requirements.txt wouldn't be normal. More importantly, it increases clarity to see all the third party versions in one place - makes it easy to check and update your GH actions versions at the same time as the Python dependencies. 

Implementation should be very easy - just write out the "cache-dependencies" string to a file and pass it to "cache-dependency-path". 

**Are you willing to submit a PR?**
Not able to right now

**Comment by marko-zivic-93** [comment]
Hello @ben-spiller 
Thank you for your feature request.
We will inspect this potential feature and the benefits it could provide and will come back to you with our decision.

**Comment by marko-zivic-93** [comment]
Hello @ben-spiller 
According to our [ADR](https://github.com/actions/setup-python/blob/main/docs/adrs/0000-caching-dependencies.md#goals--anti-goals) we will not pursue creating custom solutions of this type.
If you wish to add some customization to the existing functionalities, please use our action called `actions/cache`.
Thank you for your report once again!

**Comment by solodon4** [comment]
I need this feature too. How many votes do you need before you realize you need to adjust your ADR (whatever that means)?
