### ISSUE TITLE
RFE: ability to install "latest pypy3"

### ISSUE THREAD

**Issue by scop** [actions/setup-python#352]
**Description:**

Would be good to be able to install the latest available pypy the same way as cpython, i.e. `pypy-3.x`. There are some `.x` possibilities for the PyPy version part, but this is about the PyPy Python version.

**Action version:**
v3

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
Try configuring a matrix with `pypy-3.x` in it.

**Expected behavior:**
Latest PyPy 3.x installed.

**Actual behavior:**
Error message
> Invalid format of Python version for PyPy. Python version should be specified in format 'x.y'. See README for examples and documentation.

**Comment by nulano** [comment]
> With v2, one could install the latest pypy 3.x using python-version pypy3.

IIRC `pypy3` was defined to be PyPy3.6, not latest PyPy.

**Comment by scop** [comment]
Ah, correct, bad assumption on my side. Will modify this to be a feature request, then :)

**Comment by marko-zivic-93** [comment]
Hello @scop 
Thank you for your report.
This seems to be a feature request instead of a bug. Could you please create a feature request instead?
I will close this issue due to that reason.

**Comment by scop** [comment]
https://github.com/actions/setup-python/issues/360
