### ISSUE TITLE
Request for Python 3.11.0a6 support

### ISSUE THREAD

**Issue by achimnol** [actions/setup-python#353]
**Description:**
Please add the pre-release Python version: 3.11.0.a6, which was released in about one week ago.

**Justification:**
It has `asyncio.TaskGroup` which is a new key feature to test with.

**Are you willing to submit a PR?**
This is just a kindly reminder.

**Comment by achimnol** [comment]
> @achimnol I might be wrong, but I think `setup-python` relies on [`python-versions`](https://github.com/actions/python-versions) for the version manifests

I know.  `actions/python-versions` do not accept issue reports but only PRs, and as in #299, this is the place to request addition of specific Python versions. :wink:

**Comment by edgarrmondragon** [comment]
@achimnol this was fixed by https://github.com/actions/python-versions/pull/147
