### ISSUE TITLE
Caching Support for GHES

### ISSUE THREAD

**Issue by tiwarishub** [actions/setup-python#362]
**Description:**
👋  Team,  we have recently added support for caching in GHE (target version 3.5). And we saw ``setup-python`` action is also using the Action cache service to cache dependency, based on user input, using the ``actions/cache`` package.  
As we have added support for caching in GHES 3.5, you can modify [this](https://github.com/actions/setup-python/blob/main/src/setup-python.ts#L14-L16) condition to use the new ``isFeatureAvailable`` [function](https://github.com/actions/toolkit/blob/main/packages/cache/src/cache.ts#L52)  present in ``@actions/toolkit 2.0.0``  to check the presence of Actions cache service. 
You can also refer to [this](https://github.com/actions/cache/blob/c31528629d55886d56018ef0e8d0da5986e4fe31/src/utils/actionUtils.ts#L79-L93) change which we are doing for [actions/cache ](https://github.com/actions/cache/) action.

**Comment by tiwarishub** [comment]
@actions/actions-service for visibility

**Comment by tiwarishub** [comment]
PR is raised for this https://github.com/actions/setup-python/pull/363

**Comment by marko-zivic-93** [comment]
We added caching support for GHES.
Closing the issue thread.
