### ISSUE TITLE
README links to tool cache are broken

### ISSUE THREAD

**Issue by gene1wood** [actions/setup-python#386]
**Description:**
The links in the [`Hosted Tool Cache`](https://github.com/actions/setup-python#hosted-tool-cache) section of the README link to 

* https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/hosted-tool-cache.sh
* https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Download-ToolCache.ps1

However something changed at some point in the past and these files no longer exist in this form.

I looked to see if they were moved but couldn't quite tell where the information that was in these files now lives in the repo

**Repro steps:**  

Click the two links in the  [`Hosted Tool Cache`](https://github.com/actions/setup-python#hosted-tool-cache) section of the README

**Expected behavior:**

You're taken to pages describing the contents of the hosted tool cache

**Actual behavior:**

You get a 404

**Comment by marko-zivic-93** [comment]
Hello @gene1wood 
We need to investigate the history of changes and find either correct URL's or remove the links.
We will post the status as soon as we have any updates related to this issue :)

**Comment by vsafonkin** [comment]
Hi @gene1wood, outdated links are fixed, thank you for your report!

**Comment by gene1wood** [comment]
@vsafonkin Thanks! I would have PRd it myself but I hadn't imagined that the Ubuntu (Linux) virtual machines were provisioned using PowerShell. Today-I-Learn.
