### ISSUE TITLE
Add Python 3.7.13 to actions/python-versions manifest

### ISSUE THREAD

**Issue by f3ndot** [actions/setup-python#395]
<img width="1103" alt="Screen Shot 2022-04-28 at 1 48 13 PM" src="https://user-images.githubusercontent.com/740289/165815671-b2ebc31a-76a4-45f6-a9c0-3a14a94d19f1.png">

**Description:**
Requesting that `3.7.13` is a Python version available to be used in `actions/setup-python` via it being in the `action/python-versions` manifest

**Justification:**
[Python 3.7.13 was released March 16th, 2022](https://docs.python.org/release/3.7.13/whatsnew/changelog.html#changelog) and contains fixes as well as CVE security patches for Windows environments. It is a version we are trying to use and indeed the official `python` Docker image [has `3.7.13` tags released](https://hub.docker.com/layers/python/library/python/3.7.13/images/sha256-0827a5451746929d077de6f275c61cffffdec172af2220bb05cb3e0eb8e6efce?context=explore)

**Are you willing to submit a PR?**
Teach me how, and what I need to do, and I will 😄

**Comment by marko-zivic-93** [comment]
Hello @f3ndot 
Thank you for your request :)
Python version 3.7.13 will be available through next image generation in the toolcache or can be installed by setting check-latest: true
I am going to close this issue now. If you have any additional questions or concerns, please feel free to post them here or to create a new issue
