### ISSUE TITLE
Profile Guided Optimized python binary???

### ISSUE THREAD

**Issue by machinexa2** [actions/setup-python#404]
PGO takes advantage of recent versions of the GCC or Clang compilers. If used, either via configure --enable-optimizations or by manually running make profile-opt regardless of configure flags,

Is the python PGO optimized wen i use "3.11" or "3.10" version, if not how can i make it

also ping me when python3.12 is available in setup-python

**Comment by dsame** [comment]
Hello @machinexa2, thanks for your request,

I've just checked the https://github.com/actions/python-versions repo used to build python binaries and confirm the binaries already optimised for [ubuntu](https://github.com/actions/python-versions/blob/0d45fa8df44738b4628c76cb26f3483a4c266515/builders/ubuntu-python-builder.psm1#L38) and [macos](https://github.com/actions/python-versions/blob/0d45fa8df44738b4628c76cb26f3483a4c266515/builders/macos-python-builder.psm1#L41). 

Python for windows [installed from the prebuilt binaries](https://github.com/actions/python-versions/blob/0d45fa8df44738b4628c76cb26f3483a4c266515/builders/win-python-builder.psm1#L94).

**Comment by machinexa2** [comment]
I didn't know snou that repo. I check ed it out. It looks like they do build optimised binary
$configureString = "./configure"
        $configureString += " --prefix=$pythonBinariesLocation"
        $configureString += " --enable-shared"
        $configureString += " --enable-optimizations"
