### ISSUE TITLE
set-up python

### ISSUE THREAD

**Issue by swathida-byte** [actions/setup-python#408]
How do I set up python and install dependencies on self-hosted runners in which I hosted self hosted runners using k8s on summer wind image

**Comment by panticmilos** [comment]
Hi @swathida-byte,

For the setup of Python on self-hosted runners, you can refer to the [documentation](https://github.com/actions/setup-python#using-setup-python-with-a-self-hosted-runner) related to that topic. If you have additional questions about your case feel free to ask.

Cheers

**Comment by vsafonkin** [comment]
I'm going to close this issue, feel free to reopen it if you have any concerns, thank you!
