### ISSUE TITLE
Support Anaconda Python

### ISSUE THREAD

**Issue by chrisdembia** [actions/setup-python#42]
I would like to use GitHub Actions to build a Conda package. I know that the environments contain Anaconda Python but it would be great if we could select Anaconda Python versions using the actions in this repository.

**Comment by goanpeca** [comment]
@chrisdembia this is probably out of the scope of this action ?

Checkout https://github.com/goanpeca/action-setup-conda for

**Comment by chrisdembia** [comment]
Oh my gosh thank you so much! Your action will be super helpful. I suggest that the documentation for this action references your action.

**Comment by goanpeca** [comment]
@chrisdembia let me know if this works for you https://github.com/marketplace/actions/setup-miniconda and report any issues suggestions for improvement.

Cheers!

**Comment by chrisdembia** [comment]
Thanks; I'm trying it out now in https://github.com/opensim-org/conda-opensim-moco/blob/master/.github/workflows/conda_build_windows.yml.

**Comment by nikita-bykov** [comment]
Hello @chrisdembia! We apologize for such a late reply.
Unfortunately we are not planning to add this functionality to our repository. We may suggest using client actions like [setup-miniconda](https://github.com/conda-incubator/setup-miniconda). It looks like you tried using it and I hope this helped you.
I'm going to close this issue, but feel free to contact us if you have any questions.
