### ISSUE TITLE
Document how to configure setup-python on a self hosted runner

### ISSUE THREAD

**Issue by konradpabjan** [actions/setup-python#45]
GitHub hosted runners have a tools cache that `setup-python` relies on. Self-hosted runners do not have this tools cache downloaded/setup so `setup-python` will not work.

If the tools cache is downloaded/setup on a self-hosted runner, `setup-python` can be used.

**Comment by Ikana** [comment]
I'm running self hosted runners on AWS, I've been trying to install the tooling from this [repo](https://github.com/actions/virtual-environments) into our runners, but no luck yet, would that be the correct approach? I would be happy to write the documentation for this one I get it working.

**Comment by r-chris** [comment]
There is some basic info about the cache here: https://github.com/marketplace/actions/setup-python-environment#hosted-tool-cache

Would this script: https://github.com/actions/virtual-environments/blob/master/images/linux/scripts/installers/1804/hosted-tool-cache.sh be the one to setup the runner cache?

It would be very helpful to get an idea of how to do that in our `self-hosted` virtual machines.

**Comment by konradpabjan** [comment]
I've added Docs on how to configure `setup-python` on a self hosted runner. https://github.com/actions/virtual-environments/issues/275

Sometime around mid-January we did a major overhaul in terms of how Python gets installed on our images. All the versions of Python that we use for our VMS now get released as NPM packages that can be found here: https://github.com/actions/virtual-environments-packages

Before these NPM packages it was pretty painful, but now it's a matter of setting up a few env variables + running `npm install`

**Comment by jef** [comment]
> I've added Docs on how to configure setup-python on a self hosted runner. actions/virtual-environments#275

I don't think that's the right link? Unless I'm missing something...

**Comment by oberstet** [comment]
> I've added Docs on how to configure setup-python on a self hosted runner.

Mmh, ok, sounds good, thanks, but where are the docs? Can't find it ..

The link points to a closed issue relating to TK. I have searched for docs. The only reference in https://github.com/actions/virtual-environments/blob/main/README.md points to https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners - but that does not talk about Python at all.

So how do I configure Python (eg CPython 3.8 vs PyPy 3.7 available on a self-hosted runner) so that the CI job run will be done in a newly created virtual env?

**Comment by ckingbailey** [comment]
@oberstet I dug around and found this https://github.com/actions/setup-python#using-setup-python-with-a-self-hosted-runner

**Comment by sourcecodemage** [comment]
AFAIK - the linux setup-Python action will only run on  Ubuntu . I tried running it on my Debian server and it fails. See notes on what operating systems are supported by this action -> https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-setup-python-with-a-self-hosted-runner/
