### ISSUE TITLE
Cache, or increase TTL for cached versions of, stable build tools such as Python x.y to avoid remote breakage  

### ISSUE THREAD

**Issue by dirkf** [actions/setup-python#457]
**Description:**

This feature request results from the suggestion under "Expected Behaviour" when reporting the failure of CI tests specifying PyPy 3.7.
```
2022-07-04T23:12:24.5261882Z ##[group]Run actions/setup-python@v2
2022-07-04T23:12:24.5262166Z with:
2022-07-04T23:12:24.5262474Z   python-version: pypy-3.7
2022-07-04T23:12:24.5262955Z   token: ***
2022-07-04T23:12:24.5263234Z ##[endgroup]
2022-07-04T22:52:51.6322476Z PyPy version 3.7 (x) was not found in the local cache
2022-07-04T22:52:52.1006041Z ##[error]
2022-07-04T22:52:52.1006041Z ##[error]
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 certificate has expired</title>
  </head>
  <body>
    <h1>Error 503 certificate has expired</h1>
    <p>certificate has expired</p>
    <h3>Error 54113</h3>
    <p>Details: cache-iad-kiad7000098-IAD 1656975172 2426781050</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```
**Action version:**
See log

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

PyPy 3.7

**Repro steps:**  

https://github.com/ytdl-org/youtube-dl/runs/7187814676?check_suite_focus=true

Also, try https://downloads.python.org/pypy/

**Expected behaviour:**

Run test as specified with PyPy 3.7.

Even if the actual problem is with Python.org's slack site admin, it would be better to set a long cache lifetime for mainline tools that are updated only infrequently, so that if something like this happens the cached version can be used and a warning flagged. The lifetime should be of the order of the time that it takes to resolve this sort of failure, ie days or weeks.

**Actual behaviour:**

See log.

**Comment by dirkf** [comment]
Email sent:
```email 
Subject: Certificate expiry: https://downloads.python.org/pypy/
Date: Tue, 5 Jul 2022 00:39:50 +0100
To: infrastructure-staff@python.org

On 10/06/2022 13:29, I wrote:
> This link, used by GitHub's PyPy provisioner and linked from 
> https://www.pypy.org/download.html ("See these links for _other 
> versions_ or ...") is down, as of the last ~10 hours.
> 
> Navigate to https://downloads.python.org/pypy/; get this HTML:
> ...

Today, instead:

> <html>
>   <head>
>     <title>503 certificate has expired</title>
>   </head>
>   <body>
>     <h1>Error 503 certificate has expired</h1>
>     <p>certificate has expired</p>
>     <h3>Error 54113</h3>
>     <p>Details: cache-lhr7363-LHR 1656977671 582297432</p>
>     <hr>
>     <p>Varnish cache server</p>
>   </body>
> </html>

Please sort it out. Also, set up a certificate renewal process. Or just use http if that's easier.
```

**Comment by IvanZosimov** [comment]
Hi, @dirkf 👋 ! Thank you for the issue, we will investigate it and get back to you with updates 💌

**Comment by IvanZosimov** [comment]
Hi, @dirkf 👋 As you wrote, this issue is related to CA certificates on the https://downloads.python.org side. We've already pinged maintainers of https://downloads.python.org as well. By now I'm going to change the label from `bug` to `feature request`, thank you for your suggestion!

**Comment by dmitry-shibanov** [comment]
Hello everyone. For now I'm going to close the feature request because the issue with the certificate was solved and we pre-cache the most popular [versions](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#pypy) on the hosted runners that is why it should be the issue with availability of PyPy.

**Comment by dirkf** [comment]
So the issue concerns the expiry time of the versions [listed there](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#user-content-pypy). Why didn't I get the cached version of PyPy 3.7 when the source site was broken?

**Comment by dmitry-shibanov** [comment]
Hello @dirkf. It looks like the pypy-3.7 is not installed for [Ubuntu-18.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu1804-Readme.md#pypy) that is why you got failure.

**Comment by mattip** [comment]
@dirkf please upgrade to use at least PyPy3.8, I would recommend PyPy3.9. PyPy3.7 is no longer supported by the PyPy team.

**Comment by dirkf** [comment]
The point of our CI testing is to test against a swathe of reasonable Pythons that users might somehow be stuck with, Python 2.7, PyPy 3.7, Jython , ... I can't "upgrade" all the PyPys in the world.

Just as an example, ESM Ubuntu 16.04, supported till 2026, gives you Python 2.7.12 and 3.5.1, and PyPy 2.7 (7.3.6) and PyPy 3 (7.3.7).
