### ISSUE TITLE
Cannot create directory ‘/opt/hostedtoolcache’ after recent release

### ISSUE THREAD

**Issue by kenorb** [actions/setup-python#459]
**Description:**

The following error start happening after the recent action release:

```
2022-07-12T14:12:47.7158848Z ##[group]Run actions/setup-python@v4
2022-07-12T14:12:47.7159230Z with:
2022-07-12T14:12:47.7159527Z   python-version: 3.x
2022-07-12T14:12:47.7160059Z   token: ***
2022-07-12T14:12:47.7160394Z   update-environment: true
2022-07-12T14:12:47.7162682Z ##[endgroup]
2022-07-12T14:12:48.0166854Z Version 3.x was not found in the local cache
2022-07-12T14:12:48.3072207Z Version 3.x is available for downloading
2022-07-12T14:12:48.3074130Z Download from "https://github.com/actions/python-versions/releases/download/3.10.5-2452607758/python-3.10.5-linux-20.04-x64.tar.gz"
2022-07-12T14:12:49.1279090Z Extract downloaded archive
2022-07-12T14:12:49.1380950Z [command]/usr/bin/tar xz --warning=no-unknown-keyword -C /actions-runner/_work/_temp/2d83bfeb-a252-4083-95bf-6f30cffc5507 -f /actions-runner/_work/_temp/c2619dbf-23ad-46f0-9b07-baf06258c9c8
2022-07-12T14:12:52.2679935Z Execute installation script
2022-07-12T14:12:52.2887302Z Check if Python hostedtoolcache folder exist...
2022-07-12T14:12:52.2888180Z Creating Python hostedtoolcache folder...
2022-07-12T14:12:52.2921018Z ##[error]mkdir:
2022-07-12T14:12:52.2937518Z ##[error]cannot create directory ‘/opt/hostedtoolcache’
2022-07-12T14:12:52.2939104Z ##[error]: Permission denied
2022-07-12T14:12:52.2941609Z ##[error]The process '/usr/bin/bash' failed with exit code 1
2022-07-12T14:12:52.3294942Z Post job cleanup.
```

**Action version:**

v4

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Tools version:**

- 3.10.5

**Repro steps:**  

```
  setup-python:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
```

**Expected behavior:**

Won't error.

**Actual behavior:**

It errors.

**Comment by IvanZosimov** [comment]
Hi, @kenorb 👋 Thank you for that issue, we will investigate it and get back to you with updates.

**Comment by dmitry-shibanov** [comment]
Hello @kenorb. Could you please take a look at this [pull request](https://github.com/actions/setup-python/pull/394). I think it can be related to your issue.

**Comment by techman83** [comment]
@dmitry-shibanov yes, it would be directly related. RUNNER_TOOL_CACHE on GitHub hosted vs Self Hosted is different.

Self Hosted
```
Run echo ${RUNNER_TOOL_CACHE}
  echo ${RUNNER_TOOL_CACHE}
  shell: /usr/bin/bash -e {0}
/home/actions/actions-runner/_work/_tool
```

Hosted
```
Run echo ${RUNNER_TOOL_CACHE}
  echo ${RUNNER_TOOL_CACHE}
  shell: /usr/bin/bash -e {0}
/opt/hostedtoolcache
```

This variable is a [default](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables), I'd expect whilst we might want to make sure it exists, replacing it with a fixed path might cause consumers of the action to experience unexpected behaviour.

**Comment by dsame** [comment]
@techman83 
The best solution is just to create `/opt/hostedtoolcache` with the write permissions on the self-hosted manually as it is said in [README](https://github.com/actions/setup-python#linux):
<img width="892" alt="image" src="https://user-images.githubusercontent.com/245540/178691194-38e9fc77-bfc3-46ba-b549-24341ae8b9d5.png">

Alternatively, you can choose the installation directory to any location by setting AGENT_TOOLSDIRECTORY env. variable, but it should not be used because of:

<img width="895" alt="image" src="https://user-images.githubusercontent.com/245540/178691713-a7fb6bc0-8581-4dd4-9e11-b88b0d471d8f.png">

**Comment by techman83** [comment]
@dmitry-shibanov yes, that is a work around. Why would an action choose to override this variable as opposed to being a consumer of it? If for instance there is another workflow step that uses this path before, and after the python actions setup, the behaviour would be unexpected.

I'm not sure I follow what the benefit of overriding this default is, and what is gained by trying to assume what GitHub would have set it to.

**Comment by techman83** [comment]
@dsame - Apologies if I came across as blunt yesterday, still getting over covid and had already shaved many yaks. Having read through `actions/python-versions` this does not appear necessary. I have forked and done a [quick hack](https://github.com/techman83/setup-python/commit/b04a7d56deab8147ff2857683eac3bc6bb944b7e) to test my theory.

Log
```
Version 3.11.0-beta.4 was not found in the local cache
Version 3.11.0-beta.4 is available for downloading
Download from "https://github.com/actions/python-versions/releases/download/3.11.0-beta.4-266143546[8](https://github.com/Effortless-Networking/test-actions/runs/7332033650?check_suite_focus=true#step:4:9)/python-3.11.0-beta.4-linux-20.04-x64.tar.gz"
Extract downloaded archive
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/actions/actions-runner/_work/_temp/625425b3-7372-47a5-[9](https://github.com/Effortless-Networking/test-actions/runs/7332033650?check_suite_focus=true#step:4:10)836-2d19931eb061 -f /home/actions/actions-runner/_work/_temp/56914020-7d5d-443e-81b9-ddae1e3bfff2
Execute installation script
Check if Python hostedtoolcache folder exist...
Creating Python hostedtoolcache folder...
Create Python 3.[11](https://github.com/Effortless-Networking/test-actions/runs/7332033650?check_suite_focus=true#step:4:12).0-beta.4 folder
Copy Python binaries to hostedtoolcache folder
Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
Upgrading pip...
Looking in links: /tmp/tmpta_28ad7
Requirement already satisfied: setuptools in /home/actions/actions-runner/_work/_tool/Python/3.11.0-beta.4/x64/lib/python3.11/site-packages (58.1.0)
Requirement already satisfied: pip in /home/actions/actions-runner/_work/_tool/Python/3.11.0-beta.4/x64/lib/python3.11/site-packages (22.0.4)
Collecting pip
Downloading pip-[22](https://github.com/Effortless-Networking/test-actions/runs/7332033650?check_suite_focus=true#step:4:23).1.2-py3-none-any.whl (2.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 28.3 MB/s eta 0:00:00
Installing collected packages: pip
Successfully installed pip-22.1.2
Create complete file
Successfully set up CPython (3.11.0-beta.4)
```

Files in the local docker container connected to my test org:
```
actions@a34231b1bafa:~/actions-runner$ ls -lah _work/_tool/Python/3.11.0-beta.4/
total 12K
drwxr-xr-x 3 actions actions 4.0K Jul 14 01:15 .
drwxr-xr-x 3 actions actions 4.0K Jul 14 01:14 ..
drwxr-xr-x 6 actions actions 4.0K Jul 14 01:14 x64
-rw-r--r-- 1 actions actions    0 Jul 14 01:15 x64.complete
```

So to me it doesn't look necessary, and adds extra steps when configuring a self hosted runner, along with breaking existing workflows (though there is always that [one guy](https://xkcd.com/1172/)). One of the benefits is normally that the runner is pretty self contained.

**Comment by techman83** [comment]
And for completeness to check hosted (I haven't checked self hosted Mac/Windows, I have not convenient access to either).

Linux Hosted:
> Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.11.0-beta.4/x64/lib/python3.11/site-packages 
```
Run techman83/setup-python@fix/tool_path
Version 3.11.0-beta.4 was not found in the local cache
Version 3.11.0-beta.4 is available for downloading
Download from "https://github.com/actions/python-versions/releases/download/3.11.0-beta.4-2661435468/python-3.11.0-beta.4-linux-20.04-x64.tar.gz"
Extract downloaded archive
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/bc6a529a-13[7](https://github.com/Effortless-Networking/test-actions/runs/7332530725?check_suite_focus=true#step:3:8)7-4477-bfe1-e2ac9bbec74a -f /home/runner/work/_temp/21a2a966-f272-471[8](https://github.com/Effortless-Networking/test-actions/runs/7332530725?check_suite_focus=true#step:3:9)-87d5-7104c13d[9](https://github.com/Effortless-Networking/test-actions/runs/7332530725?check_suite_focus=true#step:3:10)3cd
Execute installation script
Check if Python hostedtoolcache folder exist...
Create Python 3.[11](https://github.com/Effortless-Networking/test-actions/runs/7332530725?check_suite_focus=true#step:3:12).0-beta.4 folder
Copy Python binaries to hostedtoolcache folder
Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
Upgrading pip...
Looking in links: /tmp/tmpb7m5gq7b
Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.11.0-beta.4/x64/lib/python3.11/site-packages (58.1.0)
Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.11.0-beta.4/x64/lib/python3.11/site-packages (22.0.4)
Collecting pip
Downloading pip-[22](https://github.com/Effortless-Networking/test-actions/runs/7332530725?check_suite_focus=true#step:3:23).1.2-py3-none-any.whl (2.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 84.9 MB/s eta 0:00:00
Installing collected packages: pip
Successfully installed pip-22.1.2
Create complete file
Successfully set up CPython (3.11.0-beta.4)
```

Windows Hosted:
> Requirement already satisfied: setuptools in c:\hostedtoolcache\windows\python\3.11.0-beta.4\x64\lib\site-packages (58.1.0)
```
Run techman83/setup-python@fix/tool_path
Version 3.11.0-beta.4 was not found in the local cache
Version 3.11.0-beta.4 is available for downloading
Download from "https://github.com/actions/python-versions/releases/download/3.11.0-beta.4-2661435468/python-3.11.0-beta.4-win32-x64.zip"
Extract downloaded archive
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\c501b4c7-c0e0-4a52-a1ec-178d361ae7f9', 'D:\a\_temp\a28e5e41-49e7-4003-bf2e-fcd102e395d0')"
Execute installation script
Check if Python hostedtoolcache folder exist...
Check if current Python version is installed...
No Python3.11.* found
Remove registry entries for Python 3.11(x64)...
Create Python 3.11.0-beta.4 folder in C:\hostedtoolcache\windows\Python
Copy Python binaries to C:\hostedtoolcache\windows\Python\3.11.0-beta.4\x64
Install Python 3.11.0-beta.4 in C:\hostedtoolcache\windows\Python...
Create python3 symlink
Directory: C:\hostedtoolcache\windows\Python\3.11.0-beta.4\x64
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---l         7/14/2022   2:19 AM              0 python3.exe
Install and upgrade Pip
Looking in links: c:\Users\RUNNER~1\AppData\Local\Temp\tmp4dibj_3k
Requirement already satisfied: setuptools in c:\hostedtoolcache\windows\python\3.11.0-beta.4\x64\lib\site-packages (58.1.0)
Requirement already satisfied: pip in c:\hostedtoolcache\windows\python\3.11.0-beta.4\x64\lib\site-packages (22.0.4)
Requirement already satisfied: pip in c:\hostedtoolcache\windows\python\3.11.0-beta.4\x64\lib\site-packages (22.0.4)
Collecting pip
Downloading pip-22.1.2-py3-none-any.whl (2.1 MB)
---------------------------------------- 2.1/2.1 MB 17.0 MB/s eta 0:00:00
Installing collected packages: pip
Attempting uninstall: pip
Found existing installation: pip 22.0.4
Uninstalling pip-22.0.4:
Successfully uninstalled pip-22.0.4
Successfully installed pip-22.1.2
Create complete file
Successfully set up CPython (3.11.0-beta.4)
```

Mac Hosted:
> Requirement already satisfied: pip in /Users/runner/hostedtoolcache/Python/3.11.0-beta.4/x64/lib/python3.11/site-packages (22.0.4)
```
Run techman83/setup-python@fix/tool_path
  
Version 3.11.0-beta.4 was not found in the local cache
Version 3.11.0-beta.4 is available for downloading
Download from "https://github.com/actions/python-versions/releases/download/3.11.0-beta.4-2661435468/python-3.11.0-beta.4-darwin-x64.tar.gz"
Extract downloaded archive
/usr/bin/tar xz -C /Users/runner/work/_temp/d2c80313-3a62-466d-b5e4-8a101b949bb9 -f /Users/runner/work/_temp/b147eaa3-0341-46e6-b0ea-0c7322549c12
Execute installation script
Check if Python hostedtoolcache folder exist...
Create Python 3.11.0-beta.4 folder
Copy Python binaries to hostedtoolcache folder
Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
Upgrading pip...
Looking in links: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpke_ijoy4
Requirement already satisfied: setuptools in /Users/runner/hostedtoolcache/Python/3.11.0-beta.4/x64/lib/python3.11/site-packages (58.1.0)
Requirement already satisfied: pip in /Users/runner/hostedtoolcache/Python/3.11.0-beta.4/x64/lib/python3.11/site-packages (22.0.4)
Collecting pip
Using cached pip-22.1.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
Successfully installed pip-22.1.2
Create complete file
Successfully set up CPython (3.11.0-beta.4)
```

**Comment by dsame** [comment]
@techman83 

As you already have noted, the  python is installed in `_work/_tool` directory if `AGENT_TOOLSDIRECTORY ` is not specified:

`ls -lah _work/_tool/Python/3.11.0-beta.4/`

This works in many cases, but the [README warns](https://github.com/actions/setup-python#linux):
`compiled from source in /opt/hostedtoolcache/ with the [--enable-shared](https://github.com/actions/python-versions/blob/94f04ae6806c6633c82db94c6406a16e17decd5c/builders/ubuntu-python-builder.psm1#L35) flag, which makes them non-relocatable`


Installing python in the directory other then `/opt/hostedtoolcache/` works in many cases, but always there's a probability of unpredictable misbehaviour as soon as some shared libraries loaded. To avoid this the default installation forced to be `/opt/hostedtoolcache/` although with AGENT_TOOLSDIRECTORY it is still possible to choose another installation directory.

Does it make sense now?

**Comment by k24dizzle** [comment]
@dsame I'm curious, what environment variables would we have to set to revert back to the previous behavior?

**Comment by dsame** [comment]
@k24dizzle 
just set AGENT_TOOLSDIRECTORY to any location the runner user has write permission to.

Namely for Pytjon-3.11.0-betat.4 as in the log above:

```
  env:
    AGENT_TOOLSDIRECTORY: /home/actions/actions-runner/_work/_tool/Python/3.11.0-beta.4/x64/
```

**Comment by techman83** [comment]
@k24dizzle - Alternatively, you can use the context variable.
```
        env:
          AGENT_TOOLSDIRECTORY: ${{ runner.tool_cache }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0-beta.4"
```

**Comment by techman83** [comment]
@dsame I don't, I hope I have articulated clearly enough to show that this is a regression for self hosted users. Even though that regression technically aligns the behaviour of `actions/setup-python` with the documentation, I don't think that is the best technical outcome here.

**Comment by fredflev** [comment]
> env:
>     AGENT_TOOLSDIRECTORY: /home/actions/actions-runner/_work/_tool/

Hi, I am working on the same repo as @kenorb where the GH action is being used. 

I ended up following the suggestion, but I would say, use whatever value `RUNNER_TOOL_CACHE` defaults too when setting `AGENT_TOOLSDIRECTORY`. 

Also the value of `RUNNER_TOOL_CACHE` depends on the value of `RUNNER_DIR`. 

E.g:  in my case `RUNNER_DIR=/actions-runner`.

![image](https://user-images.githubusercontent.com/42792052/179444609-90f20e7d-9f28-4359-9a18-262f256347ab.png)

So in I am setting `AGENT_TOOLSDIRECTORY` to: 

> env:
>     AGENT_TOOLSDIRECTORY: /actions-runner/_work/_tool/

Then I can confirm that the action is setting up the Python tool under `/actions-runner/_work/_tool/Python/`

![image](https://user-images.githubusercontent.com/42792052/179444680-371b26fb-9b56-4fe1-bbdd-8bed858b9a97.png)

And that this path is then used by the other action depending on python, such as `ansible-lint` here:

![image](https://user-images.githubusercontent.com/42792052/179444768-8ed48f8d-11b6-46fd-b8d6-b995d9a5fbee.png)

This really makes me wonder why `AGENT_TOOLSDIRECTORY` doesn't default to the value of `RUNNER_TOOL_CACHE` if not set/defined instead of defaulting to `/opt/hostedtoolcache`. 

Cf this comment from @techman83 : 

> Internally they use a TOOLCACHE_ROOT variable, which they set to RUNNER_TOOL_CACHE when AGENT_TOOLSDIRECTORY is not provided. If the same is implemented here, actions-python will behave in the same manner, and respect the path that is configured as part of the self hosted runner options.

That would make a lot more sense to me and by doing so we wouldn't have to tinker with `AGENT_TOOLSDIRECTORY` when calling the action.

**Comment by dsame** [comment]
@fredflev 
> This really makes me wonder why `AGENT_TOOLSDIRECTORY` doesn't default to the value of `RUNNER_TOOL_CACHE` if not set/defined instead of defaulting to `/opt/hostedtoolcache`.

Because for the robust shared library loading python must be installed in `/opt/hostedtoolcache` and the other locations must not be default

**Comment by fredflev** [comment]
> dsame

Fair enough, I guess I am probably looking at this trough the "this would be better for my use case" lens without seeing the bigger picture.

**Comment by dsame** [comment]
@techman83 

> this is a regression for self hosted users

it fix the issues like [this](https://github.com/actions/setup-python/issues/162) and [this](https://github.com/actions/setup-python/issues/401)

**Comment by techman83** [comment]
@dsame I appreciate what it is trying to do, but those issues relate to `python-versions` previously hard coding that path, which was fixed some time ago -> actions/python-versions#21. I have tested the release prior to v4.1.0, and I'm able to use the builds from python-versions regardless of if I'm running self-hosted or hosted.

I don't think it's correct to alter `RUNNER_TOOL_CACHE`, because GitHub set this for us. We can depend on it being correct, regardless of if the runner is hosted or self-hosted. Which is likely why the python-versions use it when no AGENT_TOOLSDIRECTORY is provided.

**Comment by techman83** [comment]
@dsame - hopefully this demonstrates things a bit better -> https://github.com/Effortless-Networking/test-setup-python/runs/7384473653

In fact, I was able to omit all those lines entirely. And everything "just worked".

**Comment by MarkArts** [comment]
We where having this issue while setting up our own runners with the ubuntu example in: https://github.com/philips-labs/terraform-aws-github-runner.
We could fix it by making these changes to the ubuntu example:
https://github.com/philips-labs/terraform-aws-github-runner/pull/2302/files
