### ISSUE TITLE
Discrepancy in the documentation

### ISSUE THREAD

**Issue by dsame** [actions/setup-python#464]
**Description:**

[README says](https://github.com/actions/setup-python) : "The Python packages ... are originally compiled from source in /opt/hostedtoolcache/ ... which makes them non-relocatable."

But [instruction to setup tool cache on self-hosted runners without internet access](https://docs.github.com/en/enterprise-server@3.5/admin/github-actions/managing-access-to-actions-from-githubcom/setting-up-the-tool-cache-on-self-hosted-runners-without-internet-access#populating-the-tool-cache-for-a-self-hosted-runner) mentions "RUNNER_DIR/_work/_tool"

This leads to the confusion, see the discussion of https://github.com/actions/setup-python/issues/459

**Comment by techman83** [comment]
Hi @dsame - I've done a bit of digging. When this [documentation was written](https://github.com/actions/setup-python/pull/90), it was likely based on the implementation within `actions/python-versions` at the time. However shortly before this change was made to the docs, the code for Linux/Mac [aligned](https://github.com/actions/python-versions/commit/f75c0e6e4b33d1d070936b35d682b7c9efceaa4b) with the windows self-hosted experience.

#394 was introduced to align the implementation with the documentation. This is a good thing, however the documentation doesn't reflect how `actions/python-versions` works now. The upstream now uses `RUNNER_TOOL_CACHE` if `AGENT_TOOLSDIRECTORY` is not set. The implementation in #394 overwrites `RUNNER_TOOL_CACHE` to the path that is the default (`/opt/hostedtoolcache`) for hosted runners. However self-hosted runners use a configurable relative path, provided during launch of the [runner](https://github.com/actions/runner/blob/main/src/Runner.Listener/Runner.cs#L628).

I realise I am being pedantic in relation to something that breaks my use case, however I feel strongly that the better technical outcome would be that users of self-hosted runners get a consistent experience compared to hosted, and it is what I attempted in #461. The added bonus is that the behaviour in that PR for users of the hosted runners is identical with or without my change, whilst also simplifying the self-hosted experience in the process.

**Comment by techman83** [comment]
The initial issue has been resolved and the documentation for macOS improved to be clear about the issue. So this can probably be closed.

**Comment by IvanZosimov** [comment]
I agree with @techman83 and think that this issue can be closed because this discrepancy appears only for python binaries on macOS self-hosted runners and this fact is mentioned in the [documentation](https://github.com/actions/setup-python/pull/472/files#diff-e8f077830705686ec3300dbcec8ee6ac6345ae9a2965508ff3abc4146d520bf8R452) for `setup-python`.

By now I'm going to close this issue, If you have any additional questions, please, feel free to ping us.
