### ISSUE TITLE
`pip install .` gives `ModuleNotFoundError` for a module included in `setup.py`

### ISSUE THREAD

**Issue by bczsalba** [actions/setup-python#468]
**Description:**
My library depends on `typing_extensions`, and this is clearly stated in `setup.py`'s `install_requires` list. It seems to be configured just fine, as it installs & runs on fresh Python installations.

After running `setup_python` (at v2 originally, but same behaviour exists on v4) my next step is to install dependencies. Everything installs just fine, and `pip freeze` includes the module in question. However, as soon as `pip install .` is started and `typing_extension` shows up in the source the action crashes.

**Action version:**
Tested on v2 and v4.

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
`3.8`, `3.9`, `3.10`

**Repro steps:**  
Not sure how easy to reproduce the exact situation is, but most of the recent [logs](https://github.com/bczsalba/pytermgui/runs/7431867020) indicate the issue. There is also a separate [branch](https://github.com/bczsalba/pytermgui/tree/fix-dependency) I made to try and fix whatever's going on, so you can see some steps I've already tried.

**Expected behavior:**
Since the module is already installed, `pip install .` should just work.

**Actual behavior:**
As mentioned above, installation raises `ModuleNotFoundError: No module named 'typing_extensions'`.

Not sure if this is the right place for this issue, but it seemed most logical. Am I doing something wrong?

**Comment by IvanZosimov** [comment]
Hi, @bczsalba 👋 Thank you for that issue, we will investigate it and get back to you with updates.

**Comment by IvanZosimov** [comment]
@bczsalba I tried to [reproduce](https://github.com/IvanZosimov/pytermgui/runs/7445935778?check_suite_focus=true) your issue without using setup-python action (using system's python version) and the error is still here. Although `typing_extensions` module is indeed installed (you can check it with `pip list -v`) but pip isn't able to find it. Probably it's better to address this issue to [pip](https://github.com/pypa/pip/issues) directly. 

By now I'm going to close this issue, If you have any questions feel free to ping us.

**Comment by bczsalba** [comment]
Had a feeling that would happen :(

Thanks for your quick help & response!

**Comment by bczsalba** [comment]
For any future readers:

I asked the guys over at [pip](https://github.com/pypa/pip/issues/11281#issuecomment-1191714091), and they explained the reason this is happening. I asked if moving to `pyproject.toml` would fix it; they said yes and they were [right](https://github.com/bczsalba/pytermgui/runs/7454901770)!

**Comment by graceyangfan** [comment]
@IvanZosimov @bczsalba  I meet the same problem!
