### ISSUE TITLE
Support for Python 3.7.3

### ISSUE THREAD

**Issue by UncleGoogle** [actions/setup-python#474]
**Description:**
There is 3.7.1 and 3.7.5 and incrementally all newer versions, others are missing.

**Justification:**
Python 3.7.3 is bundled with [GOG Galaxy](https://www.gog.com/galaxy) which provides Python plugins ecosystem. It would be good for plugin creators to use exact Python version in CI for build and functional tests.

For that usage it is enough to have Python 3.7.3 x86 on win32 and Python 3.7.3 x64 on darwin, but for being complete linux versions probably should be provided as well

**Are you willing to submit a PR?**
not sure where to start

**Comment by IvanZosimov** [comment]
Hi, @UncleGoogle 👋 Thank you for the request, we will take a look at that problem.

**Comment by dmitry-shibanov** [comment]
Hello everyone. We've built versions for ubuntu-18.04, ubuntu-20.04, macOS and Windows. For now I'm going to close the issue.
