### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by jemshit** [actions/setup-python#475]
ubuntu-latest, github hosted

<img width="966" alt="Screen Shot 2022-08-04 at 15 45 29" src="https://user-images.githubusercontent.com/1948828/182850517-75dd69f8-e7c1-47fb-a9e6-4d92d7eab70e.png">
<img width="974" alt="Screen Shot 2022-08-04 at 15 45 35" src="https://user-images.githubusercontent.com/1948828/182850533-64c432b3-4c4e-4164-900a-5a3df62ebec8.png">
<img width="526" alt="Screen Shot 2022-08-04 at 15 46 00" src="https://user-images.githubusercontent.com/1948828/182850535-07746413-9537-4ec8-b344-d3db44f95a20.png">

**Comment by dmitry-shibanov** [comment]
Hello @jemshit. Thank you for your report. For cache you need to specify python-version or python-version-file. Could you please try to specify one of them ?

**Comment by jemshit** [comment]
> Hello @jemshit. Thank you for your report. For cache you need to specify python-version or python-version-file. Could you please try to specify one of them ?

This was working fine before without error. Doesn't the version specified in PATH works for cache?

**Comment by dmitry-shibanov** [comment]
According to the code you need to specify a version to enable cache. 
- https://github.com/actions/setup-python/blob/main/src/setup-python.ts#L81

**Comment by jemshit** [comment]
Error disappeared after specifying python-version
