### ISSUE TITLE
Question: should '3.11-dev' match release candidates too ?

### ISSUE THREAD

**Issue by neutrinoceros** [actions/setup-python#478]
**Description:**
It seems that currently, version '3.11-dev' is mapped to '3.11.0b5', which is the last beta version. I’d expect release candidates to have higher priority. Is this a bug ?

**Justification:**
The '-dev' suffix is useful to keep checking in the latest iteration of a future Python version, it seems it would make sense to have it match release candidates.

**Are you willing to submit a PR?**
Yes. But I’m not sure I’d be able to fix this myself (not familiar with the language).

**Comment by vsafonkin** [comment]
Hi @neutrinoceros, it's not a bug, `setup-python` action downloads python from [python-versions repository](https://github.com/actions/python-versions) and there was no `3.11 rс` version in this repo.
This version has just been added: https://github.com/actions/python-versions/pull/183 and now it works as expected.

**Comment by neutrinoceros** [comment]
confirmed. Thank you !
