### ISSUE TITLE
Add Support for TK in provided python instances

### ISSUE THREAD

**Issue by jbcpollak** [actions/setup-python#48]
Hello,

A few people (myself included) have run into issues trying to run code that imports tkinter. It would be helpful if the provided python packages supported TK:

https://github.community/t5/GitHub-Actions/GitHub-Action-for-python-import-of-quot-tkinter-quot-fails/m-p/40644#M4305

**Comment by konradpabjan** [comment]
TKinter support was added a while back ago: https://github.com/actions/virtual-environments/issues/275
