### ISSUE TITLE
Restore Poetry cache when there's no exact match

### ISSUE THREAD

**Issue by Tenzer** [actions/setup-python#483]
**Description:**
Looking at the code for handling of cache for pip, it specifies a value for `restoreKey`:
https://github.com/actions/setup-python/blob/592a7a7a45a48972db5452787b01b1f407e38948/src/cache-distributions/pip-cache.ts#L65-L66

The benefit of this is you will get a cache hit even though the `requirements.txt` file has changed, which will help speed up the installation of dependencies.

The configuration for Poetry does however not do this:
https://github.com/actions/setup-python/blob/2f06e9da25e11351919e97ebc9d3cd20dc7208ab/src/cache-distributions/poetry-cache.ts#L56-L64

With Poetry, you will only get a cache hit if the `poetry.lock` hasn't changed. This means that dependency installation will take longer because it's done from scratch, even if there's just one dependency that has been updated.

Since Poetry can remove dependencies that aren't specified in `poetry.lock`, I think it should be okay to restore from the cache even though the lock file has changed.

The same may be the case for Pipenv, where the cache only will be used if `Pipfile.lock` also is unchanged.

**Justification:**
This will vastly speed up build times on PRs with changes to the dependencies for users of Poetry (and possibly Pipenv) because they can reuse a populated cache.

**Are you willing to submit a PR?**
Yes.

**Comment by dmitry-shibanov** [comment]
Hello @Tenzer. We're not planing to add restore keys for poetry because the action caches `virtualenv` directory that is why it has a chance not to resave new dependencies. For pip it caches global cache.

**Comment by Tenzer** [comment]
Ah, so it's a tradeoff between getting cache hits when dependencies are changed and ensuring the cache hits are 100% accurate when the dependencies aren't changed?

**Comment by dmitry-shibanov** [comment]
Hello @Tenzer. We can get case when dependencies are changed but because we have restore keys the action will download previous `virtualenv` and poetry won't update dependencies because `virtualenv` already exists. Besides, restore keys can lead unexpected growth of the cache size. 

For now I'm going to close the issue.
