### ISSUE TITLE
Add full support for SQLite

### ISSUE THREAD

**Issue by pedrocamargo** [actions/setup-python#49]
Software that uses SQLite extensions such  as Spatialite and RasterLite require Python versions with extension loading enabled in Python.

Currently, any code that uses Spatialite throws an error when enabling extension loading.  Attempted Ubuntu and MacOS runners and the error is the same.

**ERROR** 

AttributeError: 'sqlite3.Connection' object has no attribute 'enable_load_extension'

**Stack trace**
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <aequilibrae.project.project.Project object at 0x1192b5750>
path_to_file = '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/test_file.sqlite'
new_project = True

    def __init__(self, path_to_file: str, new_project=False):
        self.path_to_file = path_to_file
        self.parameters = Parameters().parameters
        if not os.path.isfile(path_to_file):
            if not new_project:
                raise FileNotFoundError(
                    "Model does not exist. Check your path or use the new_project=True flag to create a new project"
                )
            else:
                self.__create_empty_project()
        else:
            self.conn = sqlite3.connect(self.path_to_file)
>       self.conn.enable_load_extension(True)
E       AttributeError: 'sqlite3.Connection' object has no attribute 'enable_load_extension'

aequilibrae/project/project.py:24: AttributeError

**Comment by konradpabjan** [comment]
Feature request to improve SQLite in our image generation repo (where Python gets installed).

https://github.com/actions/virtual-environments/issues/317

**Comment by nikita-bykov** [comment]
I will close this item as the related issue was resolved in virtual-environments.
