### ISSUE TITLE
Consistency in the management of the variable AGENT_TOOLSDIRECTORY on self-hosted runner

### ISSUE THREAD

**Issue by FabienSe** [actions/setup-python#497]
**Description:**
How is managed the environnement variable `AGENT_TOOLSDIRECTORY` is different for `setup-python` and the installation script used by [python-versions](https://github.com/actions/python-versions) to install python.

In our self-hosted runner, we got the following `RUNNER_TOOL_CACHE=/home/user/_work/_tool` and  `AGENT_TOOLSDIRECTORY=`
The action `setup-python` with the following code 
https://github.com/actions/setup-python/blob/434aeabbb4286782ee8393c55a08efe7edd89027/src/setup-python.ts#L70-L76
Do not consider `AGENT_TOOLSDIRECTORY` if the variable is set but empty.
The following log is then displayed:
`##[debug]Python is expected to be installed into /home/user/_work/_tool`

But the script in `python-versions` with the code 
https://github.com/actions/python-versions/blob/41636d513658f21d19139d217299ee5327d3f70d/installers/nix-setup-template.sh#L11-L18
Consider `AGENT_TOOLSDIRECTORY` if it is set and empty because the condition checks only if the variable is set.
Therefore we got the installation script which is trying to install python in the folder `/Python`.
The expected behavior would be the use of the following path  `/home/user/_work/_tool/Python`

Either the `setup-python` or `python-versions` needs to align on the other.

**Action version:**
[`4.2.0`](https://github.com/actions/setup-python/releases/tag/v4.2.0)

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
All versions

**Repro steps:**  
- Set `RUNNER_TOOL_CACHE=/home/user/_work/_tool` and  `AGENT_TOOLSDIRECTORY=`
- See that the installation path used by `setup-python` and `python-versions` is different

**Expected behavior:**
Consistency in the management of the variable  `AGENT_TOOLSDIRECTORY` 

**Actual behavior:**
Not the same management of the variable  `AGENT_TOOLSDIRECTORY`  by `setup-python` and `python-versions`

**Comment by vsafonkin** [comment]
Hi @FabienSe, we will take a look at this, thank you for your report.

**Comment by panticmilos** [comment]
Hi @[FabienSe](https://github.com/FabienSe), 

we can confirm this consistency “issue” is meant to work in that way since `action/python-versions` is meant to work on hosted runners, with predefined directories, and to be used by `actions/setup-python`. I could suggest you fork the repo and align behavior if you need anything specific.

For now, I will close the issue, but feel free to reopen it, open new issue or continue conversation here :)
