### ISSUE TITLE
Show installed version in action log

### ISSUE THREAD

**Issue by robindaumann** [actions/setup-python#50]
I use `actions/setup-python@v1` in my project with a version constraint like this `python-version: '3.x'`. In the actions log i can not see the actually installed version, like it is the case for `actions/setup-elixir@v1.2.0` where I also use a version constraint. It would be nice if we could extend the output.

Output for this action:
```
Run actions/setup-python@v1
  with:
    python-version: 3.x
    architecture: x64
Added matchers: 'python'. Problem matchers scan action output for known warning or error strings and report these inline.
```

Output for setup-elixir:
```
Run actions/setup-elixir@v1.2.0
  with:
    otp-version: 22.x
    elixir-version: 1.9.x
    install-hex: true
    install-rebar: true
Installing OTP 22.2.1
Installing Elixir v1.9.4 <--- this line
```

**Comment by konradpabjan** [comment]
PR #51 has been merged in with the corresponding changes.

All changes from `master` have also been merged into `releases/v1` and tags have been updated. Using `setup-python@v1` will now show the version that was configured

Thanks again for the contribution @robindaumann
