### ISSUE TITLE
Make 3.x match 3.x-dev in case there is no stable release yet

### ISSUE THREAD

**Issue by lazka** [actions/setup-python#501]
Current situation: We will get 3.11 in about a month and I want to test it to CI from now on.

This means I now have to use `3.11-dev` and in one month downgrade to `3.11` to get the stable release from then on.

Ideally `3.11` would match `3.11-dev` as long as there exists no stable release yet for that version, unless I'm missing something.

I know it's possible to do `3.11.0-alpha - 3.11.0` but that still would require me to clean things up eventually and I'd like to add it once and never touch it again.

**Comment by EwoutH** [comment]
Yes, this would be a great feature. I support this!

**Comment by vsafonkin** [comment]
Hi @lazka, thank you for your help, we will take a look at this.

**Comment by mayeut** [comment]
This is #414

**Comment by brcrista** [comment]
Let's consolidate on https://github.com/actions/setup-python/issues/213 since that's been around for a while and has more people following it.
