### ISSUE TITLE
Cache pip dependencies from `pyproject.toml` file (without `requirements.txt`)

### ISSUE THREAD

**Issue by EwoutH** [actions/setup-python#502]
**Description:**
Currently setup-python (v4) produces an error when trying to cache pip packages defined in a `.pyproject.toml` file instead of `requirements.txt`.

```
    - uses: actions/setup-python@v4
      with:
        cache: 'pip'
```
results in
```
Error: No file in /home/runner/work/EMAworkbench/EMAworkbench matched to [**/requirements.txt], make sure you have checked out the target repository
```
It would be great if pip packages defined in a `.pyproject.toml` file could also be cached, without a `requirements.txt` file present. Support for caching defined extras ([optional dependencies](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies)) would also be great.

**Justification:**
setup-python should support projects following the latest build and configuration standards.

**Are you willing to submit a PR?**
Not at this moment

**Comment by dmitry-shibanov** [comment]
Hello @EwoutH. Thank you for your feature request. The action uses requirements.txt file to generate hash for the primary key. You can override this file with [cache-dependency-path](https://github.com/actions/setup-python/blob/main/action.yml#L21-L22).

**Comment by EwoutH** [comment]
Would it be useful to look for `.pyproject.toml` if `requirements.txt` can't be found? Or would that make things too complicated?
