### ISSUE TITLE
"Cache upload failed because file read failed with EBADF"

### ISSUE THREAD

**Issue by GuillaumeDesforges** [actions/setup-python#504]
**Description:**
Sometimes I get the following error in post run hook:
```
Post job cleanup.
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/org/repo --files-from manifest.txt
/home/runner/work/_actions/actions/setup-python/v3/dist/cache-save/index.js:3881
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (/home/runner/work/_actions/actions/setup-python/v3/dist/cache-save/index.js:3881:31)
    at ReadStream.emit (node:events:390:[2](https://github.com/kaiko-ai/kaiko-eng/actions/runs/3098830768/jobs/5017221970#step:15:2)8)
    at emitErrorNT (node:internal/streams/destroy:1[5](https://github.com/org/repo/actions/runs/3098830768/jobs/5017221970#step:15:5)7:8)
    at errorOrDestroy (node:internal/streams/destroy:220:7)
    at node:internal/fs/streams:258:9
    at FSReqCallback.wrapper [as oncomplete] (node:fs:[6](https://github.com/org/repo/actions/runs/3098830768/jobs/5017221970#step:15:6)60:5)
```

I then re-trigger the job manually until it works.

**Action version:** v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Python 3.8.13

**Comment by panticmilos** [comment]
hi @GuillaumeDesforges thank you for the report, we will take a look.

**Comment by panticmilos** [comment]
Hi @GuillaumeDesforges, have you noticed this behavior on v4 action maybe? Also you can provide public repo if you are able

**Comment by GuillaumeDesforges** [comment]
Unfortunately I can't make the repo public, while the issue is probably tied to our setup.

One thing I know is that we tend to have many jobs running at the same time, so there could be some concurrency issues in ça he upload?

**Comment by CandiedCode** [comment]
<img width="1048" alt="Screen Shot 2022-11-22 at 10 43 51 AM" src="https://user-images.githubusercontent.com/8380706/203371909-b09b31e9-53e9-41d8-8634-ed3a0cf0a007.png">

I am having this issue periodically with V4.

**Comment by dsame** [comment]
@GuillaumeDesforges @CandiedCode , do your builds have few jobs running in paralle?

**Comment by GuillaumeDesforges** [comment]
I think we haven't seen that for a while now on my end.

**Comment by dsame** [comment]
I was [able to reproduce](https://github.com/akv-demo/setup-python-test/actions/runs/3967067615/jobs/6798607432) the problem with [code](https://github.com/akv-demo/setup-python-test/blob/91fbcc61e72e4b7980e98c5f297f1b80d6d5c142/index.js) pretty close to the toolkit/cache (the only difference is `stream.PassThrough` instead of http request)

**Comment by GuillaumeDesforges** [comment]
Thanks @dsame , I'll do that if it happens again.

**Comment by dsame** [comment]
@GuillaumeDesforges i am closing the issue due to be inactive for a 3 weeks but please feel to reopen it or create new one in case of the problem still exists

**Comment by GuillaumeDesforges** [comment]
Hasn't happened again since then. Thanks for the help anyway 🙂

**Comment by ployt0** [comment]
I just got this error running self hosted:

```yaml
      - name: set up JDK 17
        uses: actions/setup-java@v3
```

Here's the log:

```text
Post job cleanup.
/usr/bin/tar --posix --use-compress-program zstdmt -cf cache.tzst --exclude cache.tzst -P -C /home/<<runner-user>>/actions-runner/_work/<<repo-name>>/<<repo-name>> --files-from manifest.txt
Warning: Failed to save: uploadChunk (start: 201326592, end: 234881023) failed: Cache service responded with 503
/home/<<runner-user>>/actions-runner/_work/_actions/actions/setup-java/v3/dist/cleanup/index.js:401
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (/home/<<runner-user>>/actions-runner/_work/_actions/actions/setup-java/v3/dist/cleanup/index.js:401:31)
    at ReadStream.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at errorOrDestroy (node:internal/streams/destroy:220:7)
    at node:internal/fs/streams:262:9
    at FSReqCallback.wrapper [as oncomplete] (node:fs:671:5)
```

This is the almost-default "Android CI" github action. I changed the JDK to 17 because my project required it.

It worked first time on a github runner, but I wanted to run it self hosted. It failed because of this. I re-ran it after 20 minutes of worrying and it passed.
