### ISSUE TITLE
Add support for -dev for PyPy and other interpreters

### ISSUE THREAD

**Issue by jaraco** [actions/setup-python#508]
In https://github.com/actions/setup-python/issues/213#issuecomment-1200902196_, Ivan suggested that instead of providing support for pre-release versions, users should expect to append `-dev` to every version. Unfortunately, if one attempts to append `-dev` to a PyPy version, the action fails with the error:

> Invalid 'version' property for PyPy. Both Python version and PyPy versions should satisfy SemVer notation. See README for examples and documentation.

This error is confusing because it suggests that `-dev` isn't allowed for either (C)Python or PyPy, when in fact appending `-dev` is the recommended workaround to the behavior that emergent versions of Python are invisible without it on CPython.

In any case, this issue is primarily a feature request to bring PyPy (and any future interpreters) to parity with CPython with `-dev` support so that `-dev` doesn't have to be specified in each and every version and pollute the version number in the matrix.

**Comment by vsafonkin** [comment]
Hi @jaraco, we will take a look at this, thanks.

**Comment by mattip** [comment]
Hi. PyPy dev here. The list of available pypy versions comes from [this file](https://downloads.python.org/pypy/versions.json) which is managed from [the PyPy repo](https://foss.heptapod.net/pypy/pypy/-/blob/branch/default/pypy/tool/release/versions.json). Would you like the `-dev` version to be an alias for the `nightly` PyPy builds? That would be pretty easy to add to the `versions.json` file.

**Comment by dmitry-shibanov** [comment]
Hello @jaraco. I think it is not necessary to add support for dev because it changes version from `3.8-dev` to `~3.8.0-0`. For PyPy you can achieve the similar behaviour by specifying [allow-prerelease](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#allow-pre-releases).

For now I'm going to close the feature request. if you have any concerns feel free to ping us.
