### ISSUE TITLE
Support for Python 3.12

### ISSUE THREAD

**Issue by xqt** [actions/setup-python#514]
**Description:**
Please add support for Python 3.12

**Justification:**
Python 3.12 is in alpha state. It should be able to test code with Python 3.12 with github action. Please add that release to versions-manifest.json. Thank you.

**Comment by vsafonkin** [comment]
Hi @xqt, we will take a look at this, thank you.

**Comment by vsafonkin** [comment]
@xqt, python 3.12 is unavailable in official python ftp: https://www.python.org/ftp/python/
We will add it when it is available there.

**Comment by EwoutH** [comment]
Is Python 3.12 now available? @panticmilos could you give some context?

**Comment by panticmilos** [comment]
Hi @EwoutH, I thought @vsafonkin explained the situation. I will reopen it till we add it.

**Comment by vsafonkin** [comment]
I think it will be better to keep this issue as opened until we add python 3.12 support.

**Comment by alexprengere** [comment]
For the record 3.12a1 has been released: https://www.python.org/ftp/python/3.12.0/

**Comment by kxrob** [comment]
Ping! Did this fall into oblivion?

**Comment by e-korolevskii** [comment]
Hello @kxrob 
We are still working on it

**Comment by hugovk** [comment]
In the meantime, https://github.com/deadsnakes/action can be used to test on Python 3.12.

**Comment by EwoutH** [comment]
Could we pin this issue? That makes it easier to find and keep track of?

(see [Pinning an issue to your repository](https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository))

**Comment by e-korolevskii** [comment]
Hi all!
Python 3.12.0-alpha.1 is now available!
Thank you for your patience!
