### ISSUE TITLE
New Python 3.11 darwin build packaging causes permission issues 

### ISSUE THREAD

**Issue by P403n1x87** [actions/setup-python#515]
**Description:**

It seems that the way of packaging Python builds on macOS has changed with the latest rc releases of Python 3.11. This is causing permission issues in some of my CI jobs: https://github.com/P403n1x87/austin/actions/runs/3121727300

From the summary, you can see that the Python 3.11 job is failing on macOS only, and the output shows that the issue is with permissions. My hunch is that the new packaging causes the interpreter to be installed in a protected location of the file system.

It would be great for my uses if the new packaging could at least accept an option to allow installing Python in a non-protected location, to allow my CI to work again, like with other Python releases.

**Justification:**

Some observability tools might require the binaries to be installed in non-protected locations. The new installation method is likely to break the CI for such tools.

**Are you willing to submit a PR?**

I'd love to, but I'm not familiar with how things are built and published in python-versions :(.

**Comment by vsafonkin** [comment]
Hi @P403n1x87 , indeed, we have decided to use the official python package for macOS starting from version 3.11.0 (release candidates is included). This package is installing by macOS installer tool to default system directory `/Library/Frameworks/Python.framework/Versions/...`

I'm not sure if we can change this behavior. If you see a way to do this, you can suggest your changes to the installation script in `python-versions` repo: https://github.com/actions/python-versions/blob/main/installers/macos-pkg-setup-template.sh

Thank you!

**Comment by P403n1x87** [comment]
Ah I see! I'm afraid this doesn't have an easy solution then 🙁 . I think the main issue is that the Python binary links to the library in the `/Library` area of the FS. Even by creating a "thick" venv, the link would remain, which would still cause the permission issue. One option would be to copy that linked library over and change the binary to link to the copy instead. Alternatively, running with an image that has the SIP disabled would do, but I don't think they exist?

**Comment by vsafonkin** [comment]
@P403n1x87, unfortunately we can't disable SIP for macOS hosted runners, sorry.

**Comment by mfriedenhagen** [comment]
Hi, maybe it would be possible to create a non-SIP enabled volume and install to that one? https://www.unix.com/man-page/OSX/8/installer/ has an option to choose another installation target volume.

**Comment by P403n1x87** [comment]
> Hi, maybe it would be possible to create a non-SIP enabled volume and install to that one? https://www.unix.com/man-page/OSX/8/installer/ has an option to choose another installation target volume.

Ah, that's a good point, @mfriedenhagen. But I wonder if that wouldn't break the installation, as I understand that the rpaths in the binaries are absolute 🤔 .

**Comment by mfriedenhagen** [comment]
Never did this on macOS, just read on the Python discussion forum. I found https://stackoverflow.com/questions/12521802/print-rpath-of-an-executable-on-macos and to me it looks like executable often just look in a relative path. For standard applications you may just use ~/Applications, maybe ~/Library could hold a user installation?

**Comment by P403n1x87** [comment]
Often, but not in the case of Python 😭 . I've been pointed to this discussion earlier today, that has some more details on the topic: https://discuss.python.org/t/creating-a-standalone-cpython-distribution/19402/15

**Comment by P403n1x87** [comment]
One of the possible solutions mentioned in this [discussion](https://discuss.python.org/t/permission-issues-with-observability-tools-and-the-official-macos-installer/19736/11) is that of removing the signature from the binaries. That seems to provide a workaround that's good enough for me.
