### ISSUE TITLE
Unable to install Python on RedHat Self-hosted GitHub Runner

### ISSUE THREAD

**Issue by moneygit** [actions/setup-python#519]
**Description:**
Version 3.x was not found in the local cache
Error: Version 3.x with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

**Action version:**
v3.0.0

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
All versions

**Repro steps:**  
Self-hosted GitHub Runner Service on Red Hat Enterprise Linux, 7.9:GA:server, Kernel: Linux 3.10.0-1160.76.1.el7.x86_64

`    steps:`
`      - name: checkout actions repo`
`        uses: actions/checkout@v3`

`      - name: Set up Python`
`        uses: actions/setup-python@v3`
`        with:`
`          python-version: 3.8.10`

**Expected behavior:**
Ability to install multiple instances of Python at different version levels

**Actual behavior:**
```
Error: Version 3.x with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
No CentOS or RedHat Python installation available on https://github.com/actions/python-versions/releases or in the versiuons-manifest
Nothing is downloaded into the tool folder.
.../_work/_tool/

**Comment by vsafonkin** [comment]
Hi @moneygit, as I understand the `setup-python` action uses [toolkit library](https://github.com/actions/toolkit) to find version and this logic gets platform version:
https://github.com/actions/toolkit/blob/1bc93f3cdf638ff423193f992119be08b7bb0666/packages/tool-cache/src/manifest.ts#L68

Probably this code `os.platform()` return not `linux` value in this case with self-hosted, I can't check it.

**Comment by anhdle14** [comment]
Is there a way to work around this issue?

Specific version and also platform variable for example?

**Comment by vsafonkin** [comment]
@anhdle14, there is no a way to specify platform via `setup-python` action at the moment, sorry.

**Comment by vsafonkin** [comment]
I'm going to close this issue, feel free to reopen it if you have any concerns, thank you!

**Comment by navachaitanyak** [comment]
There should be some work around for this

**Comment by MaxymVlasov** [comment]
Please repone issue, it not works

**Comment by bertobert** [comment]
The underlying cause it that the toolkit library checks for the existence and content of the /etc/lsb-release file. I created one with "DISTRIB_RELEASE=18.04" and I could successfully run setup-python with the version 3.11.2.
I tried 20.04 but I then got an issue with an old GLIBC version. 
Using ubi:8.9-1028 as base image.

**Comment by chrheg** [comment]
Test out adding the /etc/lsb-release with "DISTRIB_RELEASE=18.04" on RHEL8. This workaround let us use this action to manage different versions of python. Adding an option to force platform would be great to avoid having this workaround :)

**Comment by Sardonyx001** [comment]
Testing out the `/etc/lsb-release` workaround on RHEL 9.3 and apparently setup-python tries to install libpython (3.9 or 3.10) that depends on GLIBC_2.35 whereas RHEL9.3 only goes sup to GLIBC_2.34 ....

**Comment by Mel-Howard** [comment]
is there going to be a fix for this'?

**Comment by MaxymVlasov** [comment]
>is there going to be a fix for this'?

I suppose simpler to create a new issue and point this one in description.

For now, there a workaround available:

```yaml
jobs:
  pre-commit:
    runs-on: [self-hosted]
    container: python:3.12-slim
```

**Comment by mukteshkrmishra** [comment]
Is there a workaround for this?
