### ISSUE TITLE
`set-output` command is getting deprecated

### ISSUE THREAD

**Issue by Saviq** [actions/setup-python#524]
**Description:**
The `set-output` command is deprecated:

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Actions now warn about using it:

![obraz](https://user-images.githubusercontent.com/231077/196673084-ca3415b9-eb39-4278-af26-9828ece86b74.png)

**Action version:**
v3

**Comment by vsafonkin** [comment]
Hi @Saviq, thank you for your help, we will take a look at this.

**Comment by dmitry-shibanov** [comment]
Hello @Saviq. Could you please try to use the v4 tag ?

**Comment by Saviq** [comment]
@dmitry-shibanov thanks, I somehow missed there's a v4, must've been the `checkout@v3` above in the README.

Fixed!
