### ISSUE TITLE
Poetry cache with POETRY_VIRTUALENVS_IN_PROJECT env variable

### ISSUE THREAD

**Issue by jleclanche** [actions/setup-python#525]
I couldn't find documentation for this so I looked in the code directly:

https://github.com/actions/setup-python/blob/8bcd2560e267a43fbd8ff66c50da8a61825a0782/src/cache-distributions/poetry-cache.ts

From a cursory glance, it does not look like using `cache: "poetry"` would work if `POETRY_VIRTUALENVS_IN_PROJECT` is set to `1` (or true or whatever).

I find it preferable to use environment variables for poetry's configuration when in CI, because it avoids running extra shell commands (it's faster overall, less superfluous logging, clearer purpose, etc).

**Comment by vsafonkin** [comment]
Hi @jleclanche, we will take a look at this, thank you.

**Comment by dmitry-shibanov** [comment]
Hello @jleclanche. I think the issue should be resolved. We released a new [version](https://github.com/actions/setup-python/releases/tag/v4.5.0) of the action with support of `POETRY_VIRTUALENVS_IN_PROJECT` or `poetry config virtualenvs.in-project true`. I've tested and it works as expected. 

For now I'm going to close the issue.
