### ISSUE TITLE
Exception calling "ExtractToDirectory" with "2" argument(s): "The process cannot access the file...because it is being used by another process."

### ISSUE THREAD

**Issue by ZainRizvi** [actions/setup-python#528]
**Description:**
During file unzip, occasionally It appears that the download utility doesn't quite let go of it's write locks, causing the unzip function to fail with access denied.

Specifically, when invoking this workflow on a windows machine we get the error: 

```
Run actions/setup-python@v2
Version 3.x was not found in the local cache
Version 3.x is available for downloading
Download from "https://github.com/actions/python-versions/releases/download/3.10.8-3271105491/python-3.10.8-win32-x64.zip"
Extract downloaded archive
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\actions-runner\_work\_temp\b63b1[91](https://github.com/pytorch/pytorch/actions/runs/3286969486/jobs/5416280929#step:4:98)7-8768-4c55-80c7-3ced2f941ef4', 'C:\actions-runner\_work\_temp\1c2b084d-8f48-479c-8e1d-376e871aa930')"
Exception calling "ExtractToDirectory" with "2" argument(s): "The process cannot access the file 
'C:\actions-runner\_work\_temp\b63b1917-8768-4c55-80c7-3ced2f941ef4' because it is being used by another process."
At line:1 char:111
+ ... catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : IOException
```

**Action version:**
This is using actions/setup-python@v2. However, I checked the code that does the unzipping and the v2 version is identical to the one used in the current main branch.

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows Server 2019

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
3.x

**Repro steps:**  
Here is the github exception stack with the error (which occurs during the Setup Windows step): https://github.com/pytorch/pytorch/actions/runs/3286969486/jobs/5416280929#step:4:10

This action is invoked from here:
1. Workflow is triggered from here: https://github.com/pytorch/pytorch/blob/38543d8da0ddce0734ce1ecebb7013382508e142/.github/workflows/periodic.yml#L172-L179
2. Which invokes: https://github.com/pytorch/pytorch/blob/38543d8da0ddce0734ce1ecebb7013382508e142/.github/workflows/_win-test.yml#L72-L75
3. Which triggers the setup-python action here:
https://github.com/pytorch/pytorch/blob/38543d8da0ddce0734ce1ecebb7013382508e142/.github/actions/setup-win/action.yml#L57

The exact line in setup-python where the unzip failure occurs is this one:
https://github.com/actions/setup-python/blob/98c991d13f3149457a7c1ac4083885d0d9db98e1/src/install-python.ts#L79

Either adding a delay between download and unzip, or adding retry loop around the unzip operation would prevent this from recurring.

**Expected behavior:**
Unzipping and python installation to succeed

**Actual behavior:**
It appears that the download utility didn't quite let go of it's write locks, causing the unzip function to fail with access denied, failing the entire action

**Comment by vsafonkin** [comment]
Hi @ZainRizvi, we will take a look at this, thank you for your report.

**Comment by dmitry-shibanov** [comment]
Hello @ZainRizvi. Sorry for the late reply. Could you please try to install the latest version of the pwsh on the self-hosted ?

**Comment by dmitry-shibanov** [comment]
Hello @ZainRizvi, just a gentle ping.

**Comment by dmitry-shibanov** [comment]
Hello everyone. For now I'm going to close the issue.
