### ISSUE TITLE
Turn off error matchers?

### ISSUE THREAD

**Issue by cclauss** [actions/setup-python#53]
As discussed at https://github.community/t5/GitHub-Actions/Possible-to-turn-off-error-matchers/td-p/31070 how can we get rid of these confusing messages?

There is a message in https://github.com/ddelange/pipgrip/commit/74f5a858bd535a90f48e5486dad7cbc0472daa7c/checks?check_suite_id=393749770 that says:
```
Run actions/setup-python@v1
Added matchers: 'python'. Problem matchers scan action output for known warning or
error strings and report these inline.
```

Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

**Comment by konradpabjan** [comment]
Looks like problem matchers aren't set up which is why the message is being displayed, for context: https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md

I'll work on adding something so that it goes away

**Comment by konradpabjan** [comment]
https://github.com/actions/runner/pull/363

**Comment by konradpabjan** [comment]
The runner has been updated and released with all the changes that should make problem matcher messages go away (if you turn debug on you'll still see them)
