### ISSUE TITLE
3.11.0 for MacOS Missing

### ISSUE THREAD

**Issue by daegontaven** [actions/setup-python#531]
**Description:**
My jobs are failing for 3.11.0 for darwin. Darwin release is missing.

**Action version:**
v4

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

3.11.0

**Repro steps:**  
https://github.com/OpenDebates/openskill.py/actions/runs/3320892122/jobs/5487821864

**Expected behavior:**
3.11.0 to be found and downloaded

**Actual behavior:**
`Error: Version 3.11 with arch x64 not found`

**Comment by vsafonkin** [comment]
Hi @daegontaven, there is a problem with `sqlite3` python module for macOS python build:
https://github.com/actions/python-versions/actions/runs/3318527098/jobs/5482697138

We are already investigating it.

**Comment by vsafonkin** [comment]
@daegontaven, python 3.11.0 was added for macOS runner. Please check your builds.

**Comment by daegontaven** [comment]
Closing as it is fixed now. Thank you!
