### ISSUE TITLE
Python is not in the subpath, throwing a error when building with poetry

### ISSUE THREAD

**Issue by wiltso** [actions/setup-python#534]
**Description:**
This action has worked in the past (1 November 2022), but it suddenly stopped working. Have tried to run the action with a few different python versions (3.8, 3.9 and 3.10) and also with actions/setup-python@v4 and actions/setup-python@v3. The action always fails on the `poetry build` stage as python isn't a subpath of the repo (better description below).

**Action version:**
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

**Repro steps:**

>       - name: "Install build dependencies"
>         run: >
>           sudo apt-get install --no-install-recommends --assume-yes gettext
>           && pip install --upgrade --disable-pip-version-check pip
>           && pip install --upgrade setuptools wheel
>           && pip install --upgrade poetry
> 
>       - name: "Install poetry requirements"
>         run: poetry install --no-root
> 
>       - name: "Build the wheel"
>         run: poetry build

**Expected behavior:**
The poetry build step has worked fine meaning it built the package without any error

**Actual behavior:**

> Run poetry build
> Skipping virtualenv creation, as specified in config file.
> Building `package_name` (0.2.5)
>   - Building sdist
> 
> '/opt/hostedtoolcache/Python/3.10.8/x64/bin/python3.10' is not in the subpath of '/home/runner/work/_repo-name_/_package-name_' OR one path is relative and the other is absolute.
> Error: Process completed with exit code 1.

**Comment by marko-zivic-93** [comment]
Hello @wiltso 
Thank you for your report. We will investigate this and come back to you as soon as possible :)

**Comment by MaksimZhukov** [comment]
Hello @wiltso! Thank you for reporting this.
Could you please provide us with a link to the public repository for further investigation?

**Comment by wiltso** [comment]
Hello @MaksimZhukov, Unfortunately it's not a public repo so I can't provide a link.

**Comment by wiltso** [comment]
No I didn't make any changes that would affect the release script.
I also ran the exact same release script in another repo and it worked with getting any errors.
