### ISSUE TITLE
Poetry virtualenv is not created when the project is not in the repository's root

### ISSUE THREAD

**Issue by elilutsky** [actions/setup-python#539]
**Description:**
`poetry env use` is run in the repository's root, causing it to fail since no `pyproject.toml` is present.

https://github.com/actions/setup-python/blob/47c4a7af1d72897a511c975c95a5335bb6329dec/src/cache-distributions/poetry-cache.ts#L37-L44

Currently, only a warning is being displayed:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/16135381/201472193-4756417d-ff48-47cb-b13d-bf5a6be9fcf2.png">

Actually, this is solved by @oranav in  #447.

**Action version:**
v4

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**
All poetry versions

**Repro steps:**  
Create a repository with a Poetry project inside a subfolder and run the action.

**Expected behavior:**
Either fail hard or run `env use` on all Poetry projects inside the repository

**Actual behavior:**
Prints a warning

**Comment by MaksimZhukov** [comment]
Hello @elilutsky! Thank you for reporting this!
We will investigate the issue and get back to you as soon as we have updates.

**Comment by oranav** [comment]
I think this is essentially a symptom of #446

**Comment by MaksimZhukov** [comment]
Hello @elilutsky!
We've merged PR https://github.com/actions/setup-python/pull/447 and released `v4.5.0` action version. Could please confirm that the issue has been fixed?

**Comment by MaksimZhukov** [comment]
I am closing this issue. Please let us know if you have any objections
