### ISSUE TITLE
Python 3.6 x64 on Linux: Error: Version 3.6 with arch x64 not found

### ISSUE THREAD

**Issue by SamuelMarks** [actions/setup-python#544]
**Description:**
I've got a little project that I want to test on 3.6-3.11 on Windows, Linux, macOS. I've had no issues so far. Just upgraded to v4 of setup-python and now it doesn't work.

**Action version:**
v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
3.6

**Repro steps:**  
https://github.com/offscale/cdd-python

**Expected behavior:**
It should work (it used to work)

**Actual behavior:**
```
Run actions/setup-python@v4
  with:
    python-version: [3](https://github.com/offscale/cdd-python/actions/runs/3494131617/jobs/5857054239#step:3:3).6
    architecture: x6[4](https://github.com/offscale/cdd-python/actions/runs/3494131617/jobs/5857054239#step:3:4)
    check-latest: false
    token: ***
    update-environment: true
Version 3.[6](https://github.com/offscale/cdd-python/actions/runs/3494131617/jobs/5857054239#step:3:6) was not found in the local cache
Error: Version 3.6 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Comment by KonstantinKlepikov** [comment]
this affects all versions 3.6.* on ubuntu

**Comment by marko-zivic-93** [comment]
Hello @SamuelMarks 
We will investigate the issue and come back to you as soon as we have some news for you :)

**Comment by ReeceASharp** [comment]
Seems to be the same issue as #543 and the github runners updating from 20.04 to 22.04. There are no tarballs for 22.04 for any python 3.6.* [versions](https://github.com/actions/python-versions/blob/main/versions-manifest.json#L3680). The fix may just be to hard-code the platform version to `ubuntu-20.04` like @albertz did with https://github.com/rwth-i6/returnn/commit/38ecab17d781c4b74db6a174c8097187380b4ddc

**Comment by dvershinin** [comment]
@SamuelMarks I think this is prematurely closed via a commit message. Can you reopen this? Hardcoding the Ubuntu version is not the best fix. There are many repos out there that would have to do the same thing, so it's best to be fixed in action.

**Comment by SamuelMarks** [comment]
@dvershinin Ah yes it was the commit message that did it. This issue should remain open. Depressing to see people link to this issue as a reason to drop support for Python 3.6 =(

…and great to see you guys working on a fix

**Comment by lumip** [comment]
I'm having the same problem for python 3.6 on a github action running on `ubuntu-latest`.  The issue seems to simply be that there is no available build of Python 3.6 for `ubuntu-22.04` (yet) from [python-versions](https://github.com/actions/python-versions) - as evident from the [versions manifest](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json).

I assume this is simply due to the fact that there has been no minor release of Python 3.6 after ubuntu 22.04 was released, so a build for that system was simply never triggered.

Now, if we could get someone to somehow cause a build for 3.6 for 22.04 to happen, that'd be great, but I have no idea where to address this request, as the python-versions repository has no possibility to open any issues, but maybe maintainers here can do something about that?

@levrik from the same version manifest linked above, it seems that Python 3.9 should work from 3.9.12 on but no earlier.

**Comment by levrik** [comment]
@lumip Yeah. Already figured this and upgraded.

**Comment by dmitry-shibanov** [comment]
Hello everyone. Python 3.6 [reached end-of-life on Dec 12, 2021](https://peps.python.org/pep-0494/#lifespan).  Therefore, we won’t be supporting it with new versions of our hosted runners.  If you need Python 3.6, it’s still available on `ubuntu-20.04`.
There are a couple reasons we stop supporting end-of-life versions.  They no longer have maintenance support, so there’s no path forward for fixing bugs or security issues.  Also, they tend to run into compat issues with dependencies on newer operating systems, which is a source of confusing bugs.

For now I'm going to close the issue.

**Comment by SamuelMarks** [comment]
Ok well yesterday I moved one old project of mine to test Python versions 2.7, 3.5, 3.6 on Ubuntu 20.04 https://github.com/offscale/offconf/blob/master/.github/workflows/main.yml

Works alright… but not sure I agree with removing support from newer OSs of building and supporting Python versions. There are plenty of ways to support new versions without worry, e.g., [pyenv](https://github.com/pyenv/pyenv). But honestly compiling and building on any platform is rather simple (by hand). Any issue I've run into has been straightforward to resolve; thus far.

**Comment by MatteoH2O1999** [comment]
Hello everyone,
I don't know if this is still relevant, but if anyone is interested I have been developing a wrapper for this action that will build the deprecated versions from source: [Build and Setup Python](https://github.com/marketplace/actions/build-and-setup-python).
It is still in its early stages, but it should work fine with 3.6 on `ubuntu-latest`

**Comment by ghecadmin** [comment]
Hello Team 

Please find the issue 
![image](https://github.com/actions/setup-python/assets/113425202/122951f2-379c-4c96-92a4-00250a33aa97)

I am not able to the below version as well 
![image](https://github.com/actions/setup-python/assets/113425202/d4edcd68-cb60-40c4-9e0a-0189d3a259ca)

https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

Regards
