### ISSUE TITLE
Please provide Python 3.8.15

### ISSUE THREAD

**Issue by prmtl** [actions/setup-python#550]
**Description:**
Please provide latest version of Python 3.8 branch which is 3.8.15. As described in https://github.com/actions/python-versions#adding-new-versions

**Justification:**
Python 3.8.15 was released on 11th of October https://www.python.org/downloads/release/python-3815/ and it was security fix release containg bunch of important security fixes.

**Are you willing to submit a PR?**
Yes, but probably outside contributions for this request is not good idea.

**Comment by marko-zivic-93** [comment]
Hello @prmtl 
Thank you for your report. We will take a look at your issue and come back to you as soon as we have some information :)

**Comment by MaksimZhukov** [comment]
Hello @prmtl !
Thank you for letting us know!
We have published a release for Python `3.8.15`. Feel free to use it with `setup-python` action.

**Comment by prmtl** [comment]
Than you for such quick response and even quicker action :)
