### ISSUE TITLE
[BUG] Setting up pypy2/pypy3 on macOS is inconsistent with Ubuntu

### ISSUE THREAD

**Issue by webknjaz** [actions/setup-python#56]
```yaml
runs-on: macOS-latest
...
steps:
- uses: actions/checkout@master
- name: Set up Python ${{ matrix.python-version }}
  uses: actions/setup-python@v1.1.1
  with:
    python-version: pypy3  # or pypy2
- name: Log Python version
  run: >-
    python --version
- name: Log Python location
  run: >-
    which python
```

Output for Ubuntu (with `pypy3` / https://github.com/pypa/setuptools/pull/1967/checks?check_run_id=389069197#step:4:1):
```console
$ python --version
Python 3.6.9 (5da45ced70e5, Oct 09 2019, 19:12:54)
[PyPy 7.2.0 with GCC 6.2.0 20160901]
$ which python
/opt/hostedtoolcache/PyPy/3.6.9/x64/bin/python
```

Output for macOS (with `pypy3` / https://github.com/pypa/setuptools/pull/1967/checks?check_run_id=389069238#step:4:1):
```console
$ python --version
Python 2.7.17
$ which python
/usr/local/bin/python
```

Output for Ubuntu (with `pypy2` / https://github.com/pypa/setuptools/pull/1967/checks?check_run_id=389069417#step:4:1):
```console
$ python --version
Python 2.7.13 (8cdda8b8cdb8, Apr 14 2019, 14:06:44)
[PyPy 7.1.1 with GCC 6.2.0 20160901]
$ which python
/opt/hostedtoolcache/PyPy/2.7.13/x64/bin/python
```

Output for macOS (with `pypy2` / https://github.com/pypa/setuptools/pull/1967/checks?check_run_id=389069522#step:4:1):
```console
$ python --version
Python 2.7.17
$ which python
/usr/local/bin/python
```

**Comment by konradpabjan** [comment]
All versions of PyPy2 and PyPy3 should now be consistent between all runners 

PyPy2: `2.7.13`
PyPy3: `3.6.9`

Example matrix build: https://github.com/konradpabjan/Testing2/runs/490066687?check_suite_focus=true

There can sometimes be minor discrepancies between how/when image updates roll out. Windows + Ubuntu go out at the same time while Mac can be a little earlier or later. We try to keep all three synchronized as best we can. Any updates can be seen here (currently for Ubuntu and Windows, we're working on getting Mac in the same repo): https://github.com/actions/virtual-environments/releases
