### ISSUE TITLE
Intermittent failures setting up 3.11.0 on macos-11

### ISSUE THREAD

**Issue by AlexWaygood** [actions/setup-python#568]
Hi,

We've been getting intermittent failures over at typeshed over the last few days when trying to set up Python 3.11.0 on `macos-11`. The problems _appear_ to have started when we pinned our Python version to `"3.11.0"` (previously it was just `"3.11"`).

<details>
<summary>The output logged to the CI terminal is (click to expand):</summary>

```
Run actions/setup-python@v4
  with:
    python-version: 3.11.0
    cache: pip
    cache-dependency-path: requirements-tests.txt
    check-latest: false
    token: ***
    update-environment: true
  env:
    PIP_DISABLE_PIP_VERSION_CHECK: 1
    FORCE_COLOR: 1
    TERM: xterm-256color
Version 3.11.0 was not found in the local cache
Version 3.11.0 is available for downloading
Download from "https://github.com/actions/python-versions/releases/download/3.11.0-3328127706/python-3.11.0-darwin-x64.tar.gz"
Extract downloaded archive
/usr/bin/tar xz -C /Users/runner/work/_temp/0508e595-870b-447c-9f90-557debae33c8 -f /Users/runner/work/_temp/d37af55f-8fec-4bc9-9331-1f011c1da5ab
Execute installation script
Check if Python hostedtoolcache folder exist...
Deleting Python /Users/runner/hostedtoolcache/Python/3.11.1/x64
Install Python binaries from prebuilt package
installer: Package name is Python
installer: Upgrading at base path /
installer: The upgrade was successful.
Create hostedtoolcach symlinks (Required for the backward compatibility)
Create Python 3.11.0 folder
Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
Error: ln: python311: File exists
Error: The process '/bin/bash' failed with exit code 1
```

</details>

Our workflow file is [here](https://github.com/python/typeshed/blob/main/.github/workflows/stubtest_stdlib.yml). Examples of failing runs:

- https://github.com/python/typeshed/actions/runs/3721746816/jobs/6312109900
- https://github.com/python/typeshed/actions/runs/3720359533/jobs/6309784870
- https://github.com/python/typeshed/actions/runs/3703102727/jobs/6274149510

The error only seems to be raised _some_ of the time. (Maybe around 50% of our 3.11/macOS runs at the moment?)

Any idea what's going on here?

**Action version:**
`actions/setup-python@v4`

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
3.11.0

**Comment by MaksimZhukov** [comment]
Hello @AlexWaygood! Thanks for reporting this!
We will investigate the issue and come back to you as soon as we have any updates

**Comment by MaksimZhukov** [comment]
There was a problem with the Python 3.11.0 package. We rebuilt it, so you won't face the issue again.
I am closing the issue. Please contact us if you have any concerns.
Thanks!

**Comment by AlexWaygood** [comment]
Brilliant, thanks @MaksimZhukov!
