### ISSUE TITLE
Poetry cache: support caching custom installation (dependency groups)

### ISSUE THREAD

**Issue by jond01** [actions/setup-python#582]
**Description:**
The command [`poetry install`](https://python-poetry.org/docs/cli/#install) has many [options](https://python-poetry.org/docs/cli/#options-2) to install dependencies from single `poetry.lock` file: `--with`, `--without`, `--only`, all applicable to the specified [dependency groups](https://python-poetry.org/docs/managing-dependencies/#dependency-groups) - a concept that has been [introduced since Poetry 1.2](https://python-poetry.org/blog/announcing-poetry-1.2.0/#dependency-groups).
The cache options in the setup-python action do not naturally support multiple environments for the same `poetry.lock` file:
https://github.com/actions/setup-python/blob/dec86ecf4e7508d3930ae42abcdc575f35ea490d/src/cache-distributions/poetry-cache.ts#L48-L50

A possible workaround is to add marker files with the additional arguments to the `cache-dependency-path` input:
https://github.com/actions/setup-python/blob/dec86ecf4e7508d3930ae42abcdc575f35ea490d/action.yml#L21-L22

**Justification:**
Installing only specific dependency groups is a common situation in multiple workflows. For example, when one runs tests job/workflow, they do not need the linting or general development tools to be installed. This keeps the environment sterile and minimal.

**Are you willing to submit a PR?**
Since this proposal requires API changes, the actions team should decide on the API first.

**Comment by MaksimZhukov** [comment]
Hello @jond01! Thank you for the suggested idea!
We will consider adding this feature and will let you know as soon as we have any decision.

**Comment by dmitry-shibanov** [comment]
Hello @jond01. The purpose of caching is to cover the majority of use cases. If you need more customization we should advise to use [actions/cache](https://github.com/actions/cache)

For now I'm going to close the issue.
