### ISSUE TITLE
Please add python 3.8.16

### ISSUE THREAD

**Issue by hajapy** [actions/setup-python#583]
**Description:**
Python 3.8.16 is missing for all platforms. 3.8.16 was released Dec 6, 2022 and is a security fix release.
https://www.python.org/downloads/release/python-3816/

**Action version:**
setup-python@v4.4.0

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

 3.8.16

**Repro steps:**  
Use the setup-python action with python version 3.8.16.

**Expected behavior:**
Action is able to use python version 3.8.16.

**Actual behavior:**
Build fails with:

```
Version 3.8.16
   was not found in the local cache
  Error: The version '3.8.16
  ' with architecture 'x64' was not found for Ubuntu 20.04.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

Inspection of the manifest indicates 3.8.16 is missing for all platforms, not just ubuntu 20.04.

**Comment by e-korolevskii** [comment]
Hello @hajapy! Thank you for reporting this!
We will investigate the issue and get back to you as soon as we have updates.

**Comment by e-korolevskii** [comment]
Hello @hajapy!

Version 3.8.16 was [added](https://github.com/actions/python-versions/pull/217). For now, I'm going to close this issue.
