### ISSUE TITLE
PDM caching

### ISSUE THREAD

**Issue by frafra** [actions/setup-python#587]
**Description:**
PDM uses `$USER/.cache/pdm` as cache. It would be nice to have it supported, along pip, pipenv and poetry.

**Justification:**
PDM is a quite popular tool, similar to poetry, and it should be easy to support it as well (I hope).

**Comment by e-korolevskii** [comment]
Hello @frafra! Thank you for the suggested idea!
We will consider adding this feature and will let you know as soon as we have any decision.

**Comment by dmitry-shibanov** [comment]
Hello @frafra. As I know `PDM` has the official action. You can try to use this [action](https://github.com/pdm-project/setup-pdm). You can specify version of pdm and enable cache through it.

**Comment by dmitry-shibanov** [comment]
Hello everyone. We're not planing to implement PDM caching because `pdm-project` organization provides action to enable caching for PDM. 

For now I'm going to close the feature request.
