### ISSUE TITLE
Running the action on two parallels job in the same windows machine leads to path issues

### ISSUE THREAD

**Issue by Hish15** [actions/setup-python#596]
**Description:**
When using the action setup-python on two runners simultaneously (on the same machine), the action fails.
Python is not added to PATH. Using the full path from `outputs.python-path` does not work either

**Action version:**
Specify the action version

**Platform:**
- [x] Windows

**Runner type:**
- [x] Self-hosted

**Tools version:**
'3.10'

**Repro steps:**  
I define this composite action and use it in two parallel job on a windows machine with two available runners
```yaml
name: 'Setup ninja toolchain'
description: 'Download and sets ninja'
inputs:
  version: # id of input
    description: 'Version to fetch format is vX.Y.Z'
    default: '1.8.2'
  force_cache:
    description: 'If true force the installation by bypassing the cache'
    default: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: do-the-action
      shell: powershell
      run: python --version        
```

**Expected behavior:**
The python version must be outputed

**Actual behavior:**
I get the error `python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program.`

The debug run of the actions gives : 
```
Run actions/setup-python@v4
##[debug]Python is expected to be installed into RUNNER_TOOL_CACHE==C:\gh-runners\iotsecprojects3\_work\_tool
##[debug]Semantic version spec of 3.10 is 3.10
##[debug]isExplicit: 
##[debug]explicit? false
##[debug]isExplicit: 3.10.9
##[debug]explicit? true
##[debug]evaluating 1 versions
##[debug]matched: 3.10.9
##[debug]checking cache: C:\gh-runners\iotsecprojects3\_work\_tool\Python\3.10.9\x[64](https://github.schneider-electric.com/IoTSECprojects/AOS_FW/runs/576095?check_suite_focus=true#step:2:66)
##[debug]Found tool in cache Python 3.10.9 x64
::set-output name=python-version::3.10.9
##[debug]='3.10.9'
::set-output name=python-path::C:\gh-runners\iotsecprojects3\_work\_tool\Python\3.10.9\x64\python.exe
##[debug]='C:\gh-runners\iotsecprojects3\_work\_tool\Python\3.10.9\x64\python.exe'
Successfully set up CPython (3.10.9)
##[add-matcher]C:\gh-runners\iotsecprojects3\_work\_actions\actions\setup-python\v4\.github\python.json
##[debug]Added matchers: 'python'. Problem matchers scan action output for known warning or error strings and report these inline.
##[debug]Node Action run completed with exit code 0
##[debug]pythonLocation='C:\gh-runners\iotsecprojects3\_work\_tool\Python\3.10.9\x64'
##[debug]PKG_CONFIG_PATH='C:\gh-runners\iotsecprojects3\_work\_tool\Python\3.10.9\x64/lib/pkgconfig'
##[debug]Finished: run
##[debug]Evaluating condition for step: 'run'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
```

**Comment by dmitry-shibanov** [comment]
Hello @Hish15. Sorry for the late response. Do you use any virtualization on your machine or some other approach ?

**Comment by Hish15** [comment]
Hi @dmitry-shibanov, no virtualization. I set up two self hosted runners by hand, on two differents folders
I forgot to mention that I'm running this on a GHE instance.

**Comment by dmitry-shibanov** [comment]
Hello @Hish15. I think the best approach will be using any variant of virtualisation. For example you can try to use docker containers or use two separate self-hosted runners because you have two agents on the same environment that is why it can get conflicts. 

For now I'm going to close the issue.
