### ISSUE TITLE
update-environment input is not available

### ISSUE THREAD

**Issue by Hish15** [actions/setup-python#597]
**Description:**
I get the error
```
Unexpected input(s) 'update-environment', valid inputs are ['python-version', 'python-version-file', 'cache', 'architecture', 'token', 'cache-dependency-path']
```
Yet this is documented here https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-update-environment-flag

**Action version:**
'actions/setup-python@v4' (SHA:d09bd5e6005b175076f227b13d9730d56e9dcfcb)

**Platform:**
- [x] Windows

**Runner type:**
- [x] Self-hosted

**Tools version:**
3.10

**Comment by e-korolevskii** [comment]
Hello @Hish15 !

Try using the latest version of the action.

**Comment by Hish15** [comment]
Hi @e-korolevskii 
I realized that I'm on a private instance of this action. Is it normal that we have a @v4 version that does not have this input?
Look like this repo is also at @v4.

**Comment by e-korolevskii** [comment]
This field was added after the commit you are referring to.
Since this is not a braking change, the major version of the action has not been updated, however, our recommendation is to always use the latest version of the action.

**Comment by Hish15** [comment]
It does make sense. thanks for your answers
