### ISSUE TITLE
Broken Poetry caches for PyPy on Windows

### ISSUE THREAD

**Issue by Parnassius** [actions/setup-python#599]
**Description:**
Restoring a Poetry cache for PyPy on Windows leads to Poetry complaining about a broken virtual environment.

**Action version:**
v4

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [X] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**

- pypy-3.7 (7.3.9-3.7.13)
- pypy-3.8 (7.3.11-3.8.16)
- pypy-3.9 (7.3.11-3.9.16)

**Repro steps:**  
See this workflow file for a minimal reprodution example: https://github.com/Parnassius/test-actions-setup-python-599/blob/main/.github/workflows/main.yml
Running the workflow with a clean cache everything works correctly (log: https://github.com/Parnassius/test-actions-setup-python-599/actions/runs/4085239363)
Running the workflow a second time leads to this issue (log: https://github.com/Parnassius/test-actions-setup-python-599/actions/runs/4085261480)

**Expected behavior:**
The cache is restored correctly.

**Actual behavior:**
Poetry complains that the virtual environment is broken and it recreates it with the default python version (currently CPython 3.9.13)

**Comment by e-korolevskii** [comment]
Hello @Parnassius! Thank you for reporting this!
We will investigate the issue

**Comment by priyagupta108** [comment]
Hi @Parnassius 👋,
Sorry for the late response.
We've tested this on our end and everything appears to be working as expected. Could you please confirm if you are still experiencing the issue? If the problem is no longer relevant, we will proceed to close this ticket.
Looking forward to your update.
Thank you!

**Comment by Parnassius** [comment]
I honestly don't remember exactly what the issue was, but trying to reproduce it on my test repo I'm now unable to do so. Probably the issue was fixed by one of the updates released in the meantime. I'm closing this
