### ISSUE TITLE
pythonLocation value inconsistent between CPython and PyPy

### ISSUE THREAD

**Issue by rossmacarthur** [actions/setup-python#60]
The value of `pythonLocation` is inconsistent between CPython and PyPy

On both **pypy2** and **pypy3** the `bin` path segment is included in the `pythonLocation` variable:

**pypy3** `pythonLocation`
```
/opt/hostedtoolcache/PyPy/3.6.9/x64/bin
```

**pypy2** `pythonLocation`
```
/opt/hostedtoolcache/PyPy/2.7.13/x64/bin
```

But for the CPython versions it isn't.
**3.6** `pythonLocation`
```
/opt/hostedtoolcache/Python/3.6.10/x64
```

**2.7** `pythonLocation`
```
/opt/hostedtoolcache/Python/2.7.17/x64
```

I would expect the PyPy versions to be consistent with CPython builds

**Comment by henryiii** [comment]
I second this! It really surprised me that "bin" is being added to the PyPy `pythonLocation`, but not any others. It makes it hard to make a general setup that encompasses both.
