### ISSUE TITLE
Incomplete docs for allow-prerelease flag

### ISSUE THREAD

**Issue by bdarnell** [actions/setup-python#605]
**Description:**

The docs for the new [allow-prerelease flag in advanced-usage.md](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#allow-pre-releases) are incomplete. The sample configuration provided does not actually set the `allow-prerelease` flag. 

Additionally, it was not until I tried to use this flag that I discovered it is not in a release yet. I suggest either adding notes in the docs about when each feature was/will be added, or make it easier to discover version-specific docs. 

**Action version:**

In the `main` branch, not in any release yet.

**Comment by e-korolevskii** [comment]
Hello @bdarnell.

You can find release notes [here](https://github.com/actions/setup-python/releases).
For now, I will close this issue but if you have any additional questions feel free to ask them here.
