### ISSUE TITLE
Unable to Install Python with GitHub Actions

### ISSUE THREAD

**Issue by rksju0611** [actions/setup-python#608]
**Description:**
I am able to run setup-python for actions/setup-python@v4 however i get below error when installing python-
" Error: unable to get local issuer certificate"

Please help

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by e-korolevskii** [comment]
Hello @rksju0611!

Please, provide steps for reproducing this issue.

**Comment by rksju0611** [comment]
name: CI

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Install python version
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

**Comment by rksju0611** [comment]
I ran above GitHub Actions

**Comment by rksju0611** [comment]
please let me know how to install python and resolve this issue

**Comment by MaksimZhukov** [comment]
Hello @rksju0611!
I could not reproduce your issue. I guess it is related to the configuration of your self-hosted runner. Is it possible to provide us with a public repository for further investigation?

There is a documentation in the repository that may help you resolve the issue, please take a look: 
1) [Using setup-python with a self-hosted runner](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-setup-python-with-a-self-hosted-runner)
2) [Using setup-python on GHES](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-setup-python-on-ghes)

This [documentation](https://www.ebuilderz.com/ssl-certificate-error/) can be helpful as well.

**Comment by MaksimZhukov** [comment]
@rksju0611 just a gentle reminder

**Comment by MaksimZhukov** [comment]
I am closing the issue due to the lack of response. Please contact us and we will continue investigation

**Comment by cacti77** [comment]
@rksju0611 - did you ever solve this? If so, how please? I have the same error with a self-hosted runner on Windows 10.

**Comment by cacti77** [comment]
I opened #679 asking for more advice on how to resolve this.
