### ISSUE TITLE
Effect of python 2 sunset on setup-python

### ISSUE THREAD

**Issue by hayd** [actions/setup-python#63]
From the blogpost announcement:
https://github.blog/changelog/2020-02-27-github-actions-breaking-change-python-2-being-removed-from-all-virtual-environments/

> If you're using setup-python, please update your workflows to use Python versions 3.x.

which reads like "python 2 won't be supported by setup-python", is this the case?
If so, what workarounds are there?
Perhaps it's worth updating the README to reflect this.

**Comment by konradpabjan** [comment]
After a lot of customer feedback we've decided to keep Python 2.7 even though it has reached EOL. The standard protocol is to remove deprecated/EOL software after around 6 months but we've decided to make an exception for this.

For more information, see: https://github.com/actions/virtual-environments/issues/399

No new timeline for when Python 2.7 will be removed, but expect a blog post or something similar once it's decided that it's time to remove it
