### ISSUE TITLE
Hello patrick

### ISSUE THREAD

**Issue by Starmania** [actions/setup-python#636]
I think Patrick shouldn't be here...

https://github.com/actions/setup-python/blob/dfa76f8d0df0f92390ab2d42e57c6537748ecc71/__tests__/cache-restore.test.ts#L18-L24

https://github.com/actions/setup-python/blob/dfa76f8d0df0f92390ab2d42e57c6537748ecc71/__tests__/cache-restore.test.ts#L146-L155

**Comment by e-korolevskii** [comment]
Hello @Starmania 
Thank you for your report. We'll investigate the issue and get back to you.

**Comment by dmitry-shibanov** [comment]
Hello @Starmania. For now I'm going to close the issue. Feel free to ping us when you fill out the form.
