### ISSUE TITLE
Version 3.8.1 with arch x64 not found

### ISSUE THREAD

**Issue by cat-turner** [actions/setup-python#64]
It seems that with updates we remove support for earlier python versions

```
 Set up Python 3.8.11s
3.8.2 (x64)
Run actions/setup-python@v1
##[error]Version 3.8.1 with arch x64 not found
Available versions:

2.7.17 (x64)
3.5.9 (x64)
3.6.10 (x64)
3.7.6 (x64)
3.8.2 (x64)
```

Would it be possible to maintain support for 3.8.1 or at least give a warning so we can do updates at our own pace?

**Comment by madhurig** [comment]
@cat-turner - Minor versions are automatically updated and only one minor version is provided for python currently sine they are not considered breaking changes. For major versions, a changelog is posted https://github.blog/changelog/ in advance.
