### ISSUE TITLE
Incorrect error message when a specific Python version requires a downlevel pip

### ISSUE THREAD

**Issue by dirkf** [actions/setup-python#643]
**Description:**

`actions/setup-python` logs an error, as shown below, on installing a specific Python version that is not supported by the latest _pip_. For example, Python 3.5.x requires _pip_ < 21. Since the version of Python was specified and the correct _pip_ was ensured, the older _pip_ version is expected and not an error.

Even if a newer _pip_ were available, this should be an informational or warning message.

See also #233.

**Action version:**

v4 and earlier

**Platform:** (probably irrelevant)
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:** (probably irrelevant)
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

A version that doesn't support the latest _pip_, eg 3.5.x.

**Repro steps:**  

Use actions/setup-py to install a specific Python version that doesn't support the latest _pip_, eg 3.5.x. Eg, https://github.com/ytdl-org/youtube-dl/actions/runs/4624273941/jobs/8178946389.

**Expected behavior:**

The specified Python version should be installed with the latest version of _pip_ for that version.

**Actual behavior:**

This output is generated:

```console
[error]You are using pip version 20.3.4, however version 23.0.1 is available.
```
Python 3.5.x is not supported by pip > 20.3.4, so this is correct behaviour and not an `[error]`.

**Comment by dirkf** [comment]
Apparently there is a dependency on [`python-versions`](https://github.com/actions/python-versions/pull/117) where older versions of Python need to be rebuilt. Meanwhile there are environment variables that should be segt in the setup  script.

**Comment by dmitry-shibanov** [comment]
Hello @dirkf. Thank you for your report. We'll investigate the issue.

**Comment by dmitry-shibanov** [comment]
Hello @dirkf. Sorry for the late response. I've checked build and previous reply. I think it will be better to set up environment variables on the job level because it comes from the pip directly. Besides, possibly some users will need this messages. 

For now I'm going to close the issue.
