### ISSUE TITLE
Post install Python step fails on Windows PC

### ISSUE THREAD

**Issue by EvgeniyRub** [actions/setup-python#660]
**Description:**
I am using such notation in my yaml:
      

> - name: Install python and packages
>         uses: actions/setup-python@v4
>         with:
>           python-version: '3.11'
>           cache: 'pipenv'

Worfkflow runs on self-hosted Windows installed runner

And when it comes to "Post job cleanup." in "Post install python and packages", I got an error:

> Post job cleanup.
> ##[debug]paths for caching are C:\Users\runner\.virtualenvs
> ##[debug]Checking zstd --quiet --version
> ##[debug]Unable to locate executable file: zstd. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
> ##[debug]
> ##[debug]zstd version: null
> ##[debug]implicitDescendants 'false'
> ##[debug]followSymbolicLinks 'true'
> ##[debug]implicitDescendants 'false'
> ##[debug]omitBrokenSymbolicLinks 'true'
> ##[debug]Search path 'C:\Users\runner\.virtualenvs'
> ##[debug]Matched: ../../../../Users/runner/.virtualenvs
> ##[debug]Cache Paths:
> ##[debug]["../../../../Users/runner/.virtualenvs"]
> ##[debug]Archive Path: C:\actions-runner\_work\_temp\3fb79f86-4d86-[40](https://github.com/aoscloud/aos_integration_tests/actions/runs/4831497409/jobs/8609034721#step:56:40)a2-9064-b7dd8fe5e8fd\cache.tgz
> "C:\Program Files\Git\usr\bin\tar.exe" --posix -cf cache.tgz --exclude cache.tgz -P -C C:/actions-runner/_work/aos_integration_tests/aos_integration_tests --files-from manifest.txt --force-local -z
> /bin/sh: line 1: gzip: command not found
> /usr/bin/tar: cache.tgz: Cannot write: Broken pipe
> /usr/bin/tar: Child returned status 127
> /usr/bin/tar: Error is not recoverable: exiting now
> Warning: Failed to save: "C:\Program failed with error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2
> ##[debug]Node Action run completed with exit code 0
> ##[debug]Finishing: Post Install python and packages

Why does it consider directories like in linux(Posix)?

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [X] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by dmitry-shibanov** [comment]
Hello @EvgeniyRub. Thank you for your report. Could you please try to remove cache step ?

**Comment by dusan-trickovic** [comment]
Hello, @EvgeniyRub ! Just giving you a gentle ping to see if there are any updates on your end regarding this issue? Thank you!

**Comment by dmitry-shibanov** [comment]
Hello @EvgeniyRub. For now I'm going to close the issue. If you have any additional information feel free to ping us.
