### ISSUE TITLE
Ubuntu ARM64 support for self hosted runners

### ISSUE THREAD

**Issue by Joeri-Abbo** [actions/setup-python#678]
**Description:**
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.
We are migrating to ARM64 Linux with os Ubuntu when i try to run a workflow. It breaks because ARM64 for ubuntu is not in the manifest https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

**Action version:**
v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
I think all versions I checkt with  3.11.3 and  3.10.7

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.
We are migrating to ARM64 Linux with os Ubuntu when i try to run a workflow. It breaks because ARM64 for ubuntu is not in the manifest https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```name: CI Test

on:
  workflow_call:

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.3"
```

**Expected behavior:**
Be able to run python setup for ARM64 ubuntu

**Actual behavior:**
It does not find the version in the manifest
<img width="1154" alt="image" src="https://github.com/actions/setup-python/assets/34270045/d9ef6758-9f21-4c6a-9ad1-69f9c76596d5">

**Comment by danielloader** [comment]
Relates to https://github.com/actions/setup-python/issues/108

**Comment by danielxt7** [comment]
Yes please! we would love to have this support as well - we have a similar setup with self-hosted runners on ARM64 instances in AWS - and the workarounds suggested in #108 do not work since we're using a linux image

Thank you!

**Comment by edmondop** [comment]
@danielxt7 this workaround is gold https://github.com/temporalio/sdk-python/pull/172/files#diff-e0c5149ab771083cacddbeaf3336656118f582f6311228e0b8652c3209a7dd2eR32-R39

**Comment by aparnajyothi-y** [comment]
Hello Everyone, The version-manifest.json file has been updated to include arm64 support for latest versions of Python >= 3.8. We are now proceeding to close this issue.

Please feel free to reach out if any further concerns or clarifications are needed.
