### ISSUE TITLE
When using setup-python's version of python to install dependencies, no module named pip error in subproc

### ISSUE THREAD

**Issue by narendasan** [actions/setup-python#680]
**Description:**

I am trying install dependencies for an action in my repo but get an error during the `pip install -r requirements.txt` that in a subproc there is no module named pip

https://github.com/pytorch/TensorRT/actions/runs/5149654103/jobs/9272930952#step:11:102

**Action version:**
Specify the action version

4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

3.9.4

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

You can fine the action definition here: https://github.com/pytorch/TensorRT/blob/main/.github/workflows/docgen.yml

**Expected behavior:**
A description of what you expected to happen.

The dependencies (tensorrt) should install 

**Actual behavior:**
A description of what is actually happening.

Installation fails and the action is unable to complete

**Comment by dusan-trickovic** [comment]
Hello, @narendasan ! Thank you for creating the issue! We will take a look and see what can be done :)

**Comment by aparnajyothi-y** [comment]
Hello @narendasan, I apologize for the delay in response. We have investigated the issue, and the TensorRT import error (ImportError: libcudnn.so.8: cannot open shared object file) is related to the absence of the required CUDA and cuDNN libraries in the environment. The setup-python job itself is running successfully. Please find the screenshot for reference.
<img width="1415" alt="Screenshot 2024-10-29 at 8 55 51 PM" src="https://github.com/user-attachments/assets/0a8e2f02-eb9b-4981-9682-d9a4bfb5d803">

Upon reviewing the dependencies for TensorRT, we found that it requires specific versions of CUDA and cuDNN to function properly. If these libraries are not installed or configured correctly, import errors will occur.

Please ensure that these libraries are installed prior to attempting to import TensorRT to resolve the issue.

If you need any further assistance, please feel free to reach out.

**Comment by narendasan** [comment]
Sounds good thanks for looking

**Comment by aparnajyothi-y** [comment]
Hello @narendasan, Thank you for confirming hence we are proceeding to close this issue. 
Feel free to reach us in case any clarifications/concerns to reopen this issue.
