### ISSUE TITLE
Github action python version will become 3.1 when tested with python 3.10

### ISSUE THREAD

**Issue by rikonaka** [actions/setup-python#695]
**Description:**

I have set up some python versions as follows.

```bash
jobs:
  build-coverage:
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]
        pytorch-version: [1.9.1, 1.10.1, 1.11.0, 1.12.1, 1.13.1, 2.0.1]
```

But when github action is run, python 3.10 becomes 3.1.

![bug](https://github.com/actions/setup-python/assets/13602602/d14951c4-f1ee-496e-84e8-956bab6ab1b0)

Here is the detailed action running infomation [link](https://github.com/Harry24k/adversarial-attacks-pytorch/actions/runs/5413521339/jobs/9839196105?pr=144)

**Action version:**

IDK, the default action provided by Github.

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

`3.10`

**Repro steps:**  

Here is [link](https://github.com/Harry24k/adversarial-attacks-pytorch/pull/144).

**Expected behavior:**

Run python 3.10 for testing.

**Actual behavior:**

Run python 3.1 for testing.

**Comment by IvanZosimov** [comment]
Hi, @rikonaka 👋 This behavior is one of the peculiarities of YAML. Try to wrap python versions in quotes, so the YAML parser can interpret them as strings - then it should work properly.
I'm closing this issue. If you have any other questions, feel free to ping us!

**Comment by rikonaka** [comment]
> Hi, @rikonaka 👋 This behavior is one of the peculiarities of YAML. Try to wrap python versions in quotes, so the YAML parser can interpret them as strings - then it should work properly. I'm closing this issue. If you have any other questions, feel free to ping us!

Thank you for your reply! 😊
