### ISSUE TITLE
Also look at `$RUNNER_TOOL_CACHE` for finding the tool cache directory

### ISSUE THREAD

**Issue by brcrista** [actions/setup-python#71]
See this code: https://github.com/actions/runner/blob/6bec1e3bb832aad26f4ad5b64759a8e4d468df24/src/Runner.Common/HostContext.cs#L233

The runner prefers `RUNNER_TOOL_CACHE` and then falls back to `RUNNER_TOOLSDIRECTORY`.  `setup-python` only uses the latter: https://github.com/actions/setup-python/blob/9ac730844c47e52575257e93faf193c4530bc095/src/find-python.ts#L6

- [ ] Update the code
- [ ] Update the [self-hosted guidance](https://github.com/actions/setup-python#using-setup-python-with-a-self-hosted-runner)

**Comment by konradpabjan** [comment]
Closing, the `RUNNER_TOOLSDIRECTORY` was recently removed as it is no longer needed. See https://github.com/actions/setup-python/pull/85#discussion_r415658230 for more info
