### ISSUE TITLE
Versions prefixed with `==` fail to be found when not in the local cache

### ISSUE THREAD

**Issue by Harmon758** [actions/setup-python#711]
**Description:**
When a version is prefixed with `==` and is not found in the local cache, it fails to be found for downloading.

I encountered this while specifying the version through `project.requires-python` in `pyproject.toml`.
I'm not sure if `python-version` also has this issue, but I presume so.

**Action version:**
v4.7.0

**Platforms:**
- [X] Ubuntu
- [X] macOS
- [X] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
Every Python version not in the local cache

**Repro steps:**  
I was originally using `python-version: ['3.10.10']`, which [successfully downloads](https://github.com/Harmon758/Harmonbot/actions/runs/5745881878/job/15574520762#step:3:32).
Upon changing to use `python-version-file: pyproject.toml` with `requires-python = "==3.10.10"` (under `[project]`) in `pyproject.toml`, [the version fails to be found](https://github.com/Harmon758/Harmonbot/actions/runs/5745943813/job/15574684243#step:3:13).

Additionally, I confirmed that this is only an issue when the version is not found in the local cache, as removing the patch version in `pyproject.toml` and changing it to `requires-python = "==3.10"` [successfully installs the version in the local cache](https://github.com/Harmon758/Harmonbot/actions/runs/5746049553/job/15574947323#step:3:12).

**Expected behavior:**
The version is successfully downloaded and installed

**Actual behavior:**
The version fails to be found

**Comment by dmitry-shibanov** [comment]
Hello @Harmon758. Thank you for your report. We will take a look at the issue.

**Comment by dmitry-shibanov** [comment]
Hello @Harmon758. Could you please try to use `actions/setup-python@main`?

**Comment by dmitry-shibanov** [comment]
Hello @Harmon758. The new [version of the action](https://github.com/actions/setup-python/releases/tag/v4.7.1) was released and the major tag was updated. For now I'm going to close the issue.

**Comment by Harmon758** [comment]
Apologies for the delay in testing out the fix.
I can confirm now though that #726 [has resolved the issue](https://github.com/Harmon758/Harmonbot/actions/runs/6596631033/job/17922874542#step:3:13) [after updating to v4.7.1](https://github.com/Harmon758/Harmonbot/commit/fef2399361feaaf403bf951af05e355a236f4137).
Thank you!
