### ISSUE TITLE
Arm64 version on windows

### ISSUE THREAD

**Issue by mwangistan** [actions/setup-python#715]
**Description:**
There are no releases for Arm64 python version of windows. The version is however available here: https://www.python.org/ from python >= 3.11 but not yet added in the manifest
https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

**Justification:**
Feature will support arm64 pip package releases on windows 

**Are you willing to submit a PR?**

**Comment by dmitry-shibanov** [comment]
Hello @mwangistan. Thank you for your report. We'll take a look at this feature request.

**Comment by mwangistan** [comment]
Thanks @dmitry-shibanov

**Comment by maruel** [comment]
Hi! This is something we need too, can this be prioritized?

**Comment by saschanaz** [comment]
Looks like the manifest now has arm64 👀

**Comment by aparnajyothi-y** [comment]
Hello Everyone, The version-manifest.json file has been updated to include arm64 support for Python >= 3.11. We are now proceeding to close this feature request.

Please feel free to reach out if any further concerns or clarifications are needed.
