### ISSUE TITLE
Support non-ubuntu linux distributions by specify location of versions-manifest.json

### ISSUE THREAD

**Issue by ganadist** [actions/setup-python#716]
**Description:**
I'm using GHES with runners under CentOS / Rocky Linux.
But `setup-python` is supported on recent Ubuntu versions only, and it fails on other linux distributions, yet.
So, I propose to support other linux distributions by simple changes.

**Justification:**
* Recent actions/tool-cache library supports to determine platform version for non-ubuntu linux distros ( https://github.com/actions/toolkit/pull/594 )
* `setup-python` actions has hard coded location of `versions-manifest.json`.
  If location of `versions-manifest.json` can be provided users, actions can be used for various linux platform.
  I propose 3 inputs options for this.
    - versions-manifest-repo-owner : Github owner of `versions-manifest.json`
    - versions-manifest-repo-name :  Github repository of `versions-manifest.json`
    - versions-manifest-repo-branch :  Github branch of `versions-manifest.json`
  If these values are not set, default value should be same with current behavior.

**Are you willing to submit a PR?**

I'll try it :D

**Comment by aparnajyothi-y** [comment]
Hello, Thank you for your feature request. While supporting non-Ubuntu Linux distributions could be beneficial, it introduces added complexity, increases maintenance overhead, and could lead to misconfigurations. We believe that focusing on a single, consistent platform ensures a more stable and reliable experience for most users. As per [our support policy](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-setup-python-with-a-self-hosted-runner), we only support versions available on our hosted runners. This ensures a more consistent and reliable experience across all environments.We appreciate your understanding and encourage you to share any further ideas in the future.

**Comment by aparnajyothi-y** [comment]
Hello Everyone, Please let us know in case of clarifications needed on the above.

**Comment by ganadist** [comment]
> As per [our support policy](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-setup-python-with-a-self-hosted-runner), we only support versions available on our hosted runners. This ensures a more consistent and reliable experience across all environments. We appreciate your understanding and encourage you to share any further ideas in the future.

Thanks for the clarification.

My actual request was not about providing binary distribution for non-Ubuntu Linux.
But my request was suggestion how about providing small extension to specify customized manifest to use setup-python on non-Ubuntu Linux.

This itself doesn't take much effort, and if anyone use it at their own risk,  it would be easy and useful on non-Ubuntu Linux distribution.

**Comment by aparnajyothi-y** [comment]
Hello @ganadist, We appreciate your feedback regarding the potential for a customized manifest option for setup-python on non-Ubuntu Linux distributions. As per [our support policy](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-setup-python-with-a-self-hosted-runner), we currently only support versions available on our hosted runners. However, we’ll certainly keep your suggestion in mind for future updates once support for non-Ubuntu Linux distributions is added to our hosted runners.

For now, we’ll proceed to close the issue, but please feel free to reach out if you have any further questions or concerns. We also encourage you to share any additional ideas in the future.
