### ISSUE TITLE
OpenSSL v1 EOL - SSL Failure on Debian Bookworm

### ISSUE THREAD

**Issue by tustvold** [actions/setup-python#721]
**Description:**

This action appears to install a working pip installation on debian bookworm based images, as a result of failing to find libssl

https://github.com/apache/arrow-datafusion/actions/runs/5973988915/job/16207622288?pr=7282

```
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyarrow/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyarrow/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyarrow/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyarrow/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pyarrow/
Could not fetch URL https://pypi.org/simple/pyarrow/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pyarrow/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement pyarrow (from versions: none)
ERROR: No matching distribution found for pyarrow
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
```

I have not confirmed this, but I suspect this is because python is being built against openssl v1. This is [EOL in September](https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/) and consequently debian bookworm now exclusively ships openssl v3. Other major distros are likely to follow shortly, if they haven't already.

**Action version:**
v4

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by dmitry-shibanov** [comment]
Hello @tustvold. Thank you for your report. I think it is an expected behaviour because python versions were generated for Ubuntu (20.04, 22.04) but your container runs on `Debian GNU/Linux 12`

**Comment by tustvold** [comment]
Perhaps this is a documentation issue then, as this platform restriction does not appear to be very clearly highlighted? _I also expect Ubuntu will eventually run into this issue as it follows debian._

**Comment by duxbuse** [comment]
I am seeing this issue on Ubuntu 22.04

**Comment by priya-kinthali** [comment]
Hello @tustvold 👋,
Apologies for the delayed response.
Could you please let us know if this issue is still relevant. If not, we will proceed to close this ticket.
Thank you!

**Comment by tustvold** [comment]
I think this has been fixed
