### ISSUE TITLE
Can't Find Versions Not In Tool Cache When Using `pyproject.toml`

### ISSUE THREAD

**Issue by Kurt-von-Laven** [actions/setup-python#725]
**Description:**

`actions/python-versions` [released Python 3.11.5 5 days ago](https://github.com/actions/python-versions/releases/tag/3.11.5-5999813088), and [it's listed in `versions-manifest.json`](https://github.com/actions/python-versions/blob/38c560b52f288b4d4203c657ccd8e67eec686439/versions-manifest.json#L572-L578), but it isn't found when using [`python-version-file: pyproject.toml`](https://github.com/ScribeMD/slack-templates/blob/3295788c64dcb5ed780609d72ec1fcb105bd987a/action.yaml#L42-L45). We don't experience this issue when using [`python-version: 3.11.5`](https://github.com/ScribeMD/pre-commit-action/blob/f4db107703caaec616451449a759b20ab2e9ab72/action.yaml#L58-L61).

**Action version:**
4.7.0

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Python 3.11.5

**Repro steps:**  

- [Create a `pyproject.toml` that pins Python 3.11.5](https://github.com/renovate-bot/slack-templates/blob/5f66da91399f044f31bcb85e4f3672a4322f95a8/pyproject.toml#L43).
- Add the following step to a GitHub Actions workflow on the `ubuntu-22.04` GitHub-hosted runner:
    
    ```yaml
    - name: Set up Python based on Python version in pyproject.toml.
      uses: actions/setup-python@v4.7.0
      with:
        python-version-file: pyproject.toml
    ```
    
- [Run the workflow](https://github.com/ScribeMD/slack-templates/actions/runs/6056779121/job/16445379214?pr=426).

**Expected behavior:**

Python 3.11.5 successfully installs.

**Actual behavior:**

The workflow fails with the following error:

```
Version ==3.11.5 was not found in the local cache
  Error: The version '==3.11.5' with architecture 'x64' was not found for Ubuntu 22.04.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Comment by dmitry-shibanov** [comment]
Hello @Kurt-von-Laven. Thank you for your report. We'll take a look at this issue.

**Comment by Kurt-von-Laven** [comment]
We are seeing the same issue with 3.11.4 occassionally now that [`ubuntu-22.04 (20230903.1)`](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230903.1) is rolling out with Python 3.11.5 rather than Python 3.11.4.

**Comment by Kurt-von-Laven** [comment]
We are also seeing this issue when using `python-version`, so I have updated the issue accordingly.

**Comment by dmitry-shibanov** [comment]
Hello @Kurt-von-Laven. Could you please try to use `actions/setup-python@main`?

**Comment by Kurt-von-Laven** [comment]
Thank you for the quick fix! This is working for us now.

**Comment by dmitry-shibanov** [comment]
Hello @Kurt-von-Laven. The new [version of the action](https://github.com/actions/setup-python/releases/tag/v4.7.1) was released and the major tag was updated. For now I'm going to close the issue.
