### ISSUE TITLE
Cache createad on macos is unusable for next macos build on the same python version

### ISSUE THREAD

**Issue by fizyk** [actions/setup-python#730]
**Description:**
Pretty recently I've started using setup-python cache feature for my tests. I have a shared workflow with actions 
https://github.com/fizyk/actions-reuse/blob/main/.github/actions/pipenv/action.yml
That I reuse in my other projects. Like here:
https://github.com/ClearcodeHQ/pytest-mysql/pull/456/files

However, in this particular PR linked, I have two consecutive sets of builds running one after another on macos. And the second fails if the cache exists, if it doesn't (i.e., it gets removed manually) the 2nd build works fine.

See https://github.com/ClearcodeHQ/pytest-mysql/actions/runs/6233151257

**Action version:**
v4

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Python 3.9. 3.10, 3.11

**Repro steps:**  
Create two builds python builds (one after another) on macos using same python version.

**Expected behavior:**
Build succeded 

**Actual behavior:**
Build using existing cache fails.

**Comment by dmitry-shibanov** [comment]
Hello @fizyk. Thank you for your report. We'll take a look at this issue.

**Comment by fizyk** [comment]
@dmitry-shibanov I think I know the exact cause, i'm installing libmysql package that's being built on installation.
And I have two runs on given python version on macos each is exactly the same except for the one is run against installed MySQL (and libmysql is compiled against it) and the other against mariaDB (and compiled against) both databases are installed in different locations, and that's why cache built on one wouldn't work on the other.

I think, the solution would be to have a custom, manual postfix to cache key, because otherwise as far as setup-python is concerned, all conditions are exactly the same.

**Comment by priyagupta108** [comment]
@fizyk 👋 , Sorry for the late response.
Could you please confirm if adding a custom manual postfix to the cache key resolves your concern? If you need any further assistance, please let us know. Otherwise, if this issue has been resolved or is no longer relevant, we will proceed with closing this ticket.
Thank you for your understanding.

**Comment by fizyk** [comment]
Let's close it as no longer relevant. I've changed the dependencies, actions logs are no longer available.

**Comment by priyagupta108** [comment]
Thank you for the update. I am proceeding to close this issue as it is no longer relevant. Please reach out if there are any other concerns or issues.
