### ISSUE TITLE
Update to node20

### ISSUE THREAD

**Issue by benwells** [actions/setup-python#735]
**Description:**
Node 16 has reached end of life on September 11, 2023.

https://github.com/actions/runner now supports node 20 as of [v2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0) and we encourage teams to update their actions to run on node 20 runtime by default. 

[Changelog here](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

**Justification:**
Justification or a use case for your proposal.

**Are you willing to submit a PR?**

**Comment by dmitry-shibanov** [comment]
Hello @benwells. Thank you for your feature request. We'll take a look on it.

**Comment by plocket** [comment]
I'm getting warnings in my github action that this action needs to be updated.

**Comment by gionn** [comment]
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-python@v4

to ease the life of searchers

**Comment by dmitry-shibanov** [comment]
Hello everyone. For now I'm going to close the issues because it was released in [v5.0.0](https://github.com/actions/setup-python/releases/tag/v5.0.0).
