### ISSUE TITLE
Python 3.5.9 SIGABORTs

### ISSUE THREAD

**Issue by tysonite** [actions/setup-python#74]
Python 3.5.9 running on GHA crashes with SIGABORT as visible in this workflow: https://github.com/tysonite/robotframework/runs/528709914?check_suite_focus=true#step:13:89

The output of Python process includes:
```
double free or corruption (!prev)
```

The freshly downloaded (and compiled) Python 3.5.9 from official web site does not crash on the same operation on Ubuntu 18.04.

**Comment by nikita-bykov** [comment]
Hello @tysonite!
This issue has been open for a year without any activity, so I'm going to close it as stale.
Please feel free to contact us if the issue is still relevant to you and we will reopen it.
Thanks!
