### ISSUE TITLE
ERROR: No .egg-info directory found in C:\Users\Dell\AppData\Local\Temp\pip-pip-egg-info-7dlijmq6

### ISSUE THREAD

**Issue by Anudeep-ds** [actions/setup-python#747]
**Description:**
running requirements.txt file i am facing the below issue "ERROR: No .egg-info directory found in C:\Users\Dell\AppData\Local\Temp\pip-pip-egg-info-7dlijmq6"

vs code i am using

**Platform:**

- [x] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Tools version:**
 conda venv 3.8

**Repro steps:**  
requirements.txt contains below

transformers
transformers[sentencepiece]
datasets
sacrebleu 
rouge_score 
py7zr
pandas
nltk
tqdm
PyYAML
matplotlib
torch
notebook
boto3
mypy-boto3-s3
python-box==6.0.2
ensure==1.0.2
fastapi==0.78.0
uvicorn==0.18.3
Jinja2==3.1.2
-e .
-----------------------------------------------------------------------
Setup.py contains below

import setuptools

with open("README.md", "r", encoding="utf-8") as f:
    long_description = f.read()

__version__ = "0.0.0"

REPO_NAME = "Text-Summarizer"
AUTHOR_USER_NAME = "Anudeep-ds"
SRC_REPO = "textSummarizer"
AUTHOR_EMAIL = "tirumalasettyanudeep@gmail.com"

setuptools.setup(
    name=SRC_REPO,
    version=__version__,
    author=AUTHOR_USER_NAME,
    author_email=AUTHOR_EMAIL,
    description="A small python package for NLP app",
    long_description=long_description,
    long_description_content="text/markdown",
    url=f"https://github.com/{AUTHOR_USER_NAME}/{REPO_NAME}",
    project_urls={
        "Bug Tracker": f"https://github.com/{AUTHOR_USER_NAME}/{REPO_NAME}/issues",
    },
    package_dir={"": "src"},
    packages=setuptools.find_packages(where="src")
)
---------------------------------------------------------------------------------
running requirements.txt file i am facing the below issue "ERROR: No .egg-info directory found in C:\Users\Dell\AppData\Local\Temp\pip-pip-egg-info-7dlijmq6"

tries different things like dowgrading upgrading pytho version , removing setup tools

but nothing worked

**Expected behavior:**
it need to install all the packages

**Actual behavior:**
ERROR: No .egg-info directory found in C:\Users\Dell\AppData\Local\Temp\pip-pip-egg-info-7dlijmq6
![image](https://github.com/actions/setup-python/assets/124252038/6e52c9b3-2895-41cc-9e51-fa632fc707f2)

**Comment by dmitry-shibanov** [comment]
Hello @Anudeep-ds. Thank you for your report. We'll take a look at this issue.

**Comment by priyagupta108** [comment]
Hi @Anudeep-ds 👋, It appears the error you're encountering is related to running your requirements.txt file in a VS Code environment, which is outside the scope of the `setup-python` GitHub Action. The setup-python action is designed to set up specific Python versions in GitHub Actions workflows, not to manage dependencies within a local development environment like VS Code.
Closing this issue as it is not related to the `setup-python` action. Please feel free to reach out to us in case of any concerns.
