### ISSUE TITLE
Readme refers to old version of actions/checkout

### ISSUE THREAD

**Issue by Julian-O** [actions/setup-python#755]
**Description:**

The [Readme documentation](https://github.com/actions/setup-python/blob/main/README.md) references `actions/checkout@v3`.
The latest version is `actions/checkout@v4`.

**Action version:**
Latest readme

**Platform:**
- N/A

**Runner type:**
- N/A

**Tools version:**
- N/A

**Repro steps:**  
- N/A

**Expected behavior:**
Should model ideal behaviour - using the latest version.

**Actual behavior:**
Has out-dated reference.

**Comment by dmitry-shibanov** [comment]
Hello @Julian-O. Thank you for your report. We'll take a look on it.

**Comment by kurtmckee** [comment]
Multiple PRs have been filed to address this; each varies slightly, but #729 has multiple approvals. I recommend merging #729.

#727, #729, #738

**Comment by Julian-O** [comment]
@kurtmckee: Thanks. While all of those look worthy, only #738 actually tackles this particular issue.

**Comment by kurtmckee** [comment]
#738 is highly targeted and doesn't touch other files that also need to be updated (such as the actual workflow files that execute).

I've updated my recommendation, above, to #727 because it addresses many more cases, including the README.

**Comment by Julian-O** [comment]
@kurtmckee: I apologise. I looked at 727 on my phone, and thought it didn't update README. I see now it does. No need for 738 if you approve 727.

**Comment by kurtmckee** [comment]
No apology needed! We're both contributing our time as we can and making recommendations to the `actions/setup-python` maintainers. 👍

**Comment by dmitry-shibanov** [comment]
Hello everyone. We've updated the documentation. For now I'm going to close the issue.
