### ISSUE TITLE
ERROR: failed to solve: python:3.11-slim: failed to do request: Head "https://registry-1.docker.io/v2/library/python/manifests/3.11-slim": EOF

### ISSUE THREAD

**Issue by ericmjl** [actions/setup-python#763]
**Description:**
During the GitHub Actions workflow for publishing a Python package to PyPI, the Docker build process fails repeatedly. The error occurs when attempting to load metadata for `python:3.11-slim` from Docker's official registry. The process ends with an EOF error, indicating a potential issue with the registry or network connectivity.

**Action version:**
- GitHub Actions `checkout@v4`
- GitHub Actions `setup-python@v3`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
- Python version: `3.11`

**Repro steps:**  
1. Trigger the `Release Python Package` workflow on GitHub Actions.
2. Observe the Docker build process during the `Publish Python Package to PyPI` job.
3. The build fails while loading metadata for `python:3.11-slim` from Docker's registry.
4. Error shown: `failed to do request: Head "https://registry-1.docker.io/v2/library/python/manifests/3.11-slim": EOF`

Relevant links:
- Workflow run: [https://github.com/ericmjl/llamabot/actions/runs/6835433785/job/18589215561](https://github.com/ericmjl/llamabot/actions/runs/6835433785/job/18589215561)
- Workflow definition: [https://github.com/ericmjl/llamabot/blob/main/.github/workflows/release-python-package.yaml](https://github.com/ericmjl/llamabot/blob/main/.github/workflows/release-python-package.yaml)

**Expected behavior:**
The Docker build process should successfully complete, allowing the Python package to be published to PyPI without any errors.

**Actual behavior:**
The Docker build process fails while trying to fetch the `python:3.11-slim` image from Docker's registry, resulting in an EOF error and preventing the package from being published.

**Comment by dmitry-shibanov** [comment]
Hello @ericmjl. Thank you for your report. We'll take a look at the issue.

**Comment by priyagupta108** [comment]
Hi @ericmjl 👋,
Apologies for the delayed response.
Please let us know if this issue is still relevant. If not, we will proceed to close this ticket.
Thanks!

**Comment by ericmjl** [comment]
Please feel free to close this. Not sure what the resolution ended up being, but haven't encountered this bug in my own work since posting.

**Comment by door3010** [comment]
I got the same issue, on command:
`docker compose up -d --build`

So i entirely deleted the container
ran:
`docker compose up -d --build` 
got the sam error
(ofc because we have no container to update)

then ran:
`docker compose up -d`
and it went smooth without any problem
and then:
`docker compose up -d --build`
was working correctly

It all started when i have tried to ran:
`docker compose up -d --build`
 when container was running, so it might be the problem, and the solution is to entirely create new container
