### ISSUE TITLE
Document pythonLocation

### ISSUE THREAD

**Issue by lostmsu** [actions/setup-python#78]
There does not seem to be any documentation referring to `pythonLocation`.

**Comment by arBmind** [comment]
I agree on documenting this variable.
But I would also suggest to rename the variable to: `PYTHON_INSTALL_DIR` as this is used by the python installers.

**Comment by IvanZosimov** [comment]
Hi, @lostmsu and @arBmind 👋 ! The `pythonLocation` environment variable was documented in the [latest release](https://github.com/actions/setup-python/releases/tag/v4.0.0) of the action. Thank you for contributing 🚀 ! By now I'm going to close this issue. 

If you have any additions or suggestions feel free to ping us!

**Comment by jgehrcke** [comment]
> It contains the absolute path to the folder where the desired version of Python or PyPy is installed

If for example the Python executable is in `/path/to/usr/bin/python` what is the value of pythonLocation then? Is that `/path/to/usr/`? Or `/path/to/`? Or maybe `/path/to/usr/bin/`? :)
