### ISSUE TITLE
Cannot specify a version range for PyPy

### ISSUE THREAD

**Issue by jwodder** [actions/setup-python#786]
PyPy 7.3.13 has a bug that causes my tests to fail.  Now that PyPy 7.3.14 is out, I would like all PyPy tests to use that version or higher, but I cannot figure out how to do that.

* Specifying just `pypy-3.10` as the Python version doesn't give me 7.3.14 at the moment, apparently because that version isn't installed in the `ubuntu-latest` image yet.
* Specifying `pypy-3.10-v7.3.14` is not an option, as I would like to automatically use any later PyPy versions once they're released without having to edit my workflow.
* Specifying `>= pypy-3.10-v7.3.14` causes the actions/setup-python action to fail with "The version '>= pypy-3.9-v7.3.14' with architecture 'x64' was not found for Ubuntu 22.04."

**Comment by HarithaVattikuti** [comment]
Hello, @jwodder ! Thank you for reporting this issue, we will look into it :)

**Comment by aparnajyothi-y** [comment]
Hello @jwodder, Thank you once again for creating the issue.
As per this [current implementation](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#pypy, installing of the latest version depends on the latest pushed version of python on ubuntu-latest images and for downloadable PyPy versions from the [official PyPy site](https://downloads.python.org/pypy/), All available versions that we can download are listed in [versions.json](https://downloads.python.org/pypy/versions.json) file. If we enable check latest : true , it will install the latest version from the  ubuntu-latest images. The PyPy 7.3.14 version was pushed to ubuntu-latest image last week and it is installed by using pypy-3.10-v7.3.14. Please find the screenshots for reference.

<img width="1272" alt="image" src="https://github.com/actions/setup-python/assets/147696841/731bef1d-db3d-4a45-ad83-183ee56fc799">


In case of any further clarifications,  please feel free to reach us.

**Comment by jwodder** [comment]
[`check-latest: true`](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#check-latest-version) appears to meet my needs.
