### ISSUE TITLE
Unexpected response code from remote provider InternalServerError

### ISSUE THREAD

**Issue by BrightRan** [actions/setup-python#79]
In [this ticket](https://github.community/t5/GitHub-Actions/Unexpected-response-code-from-remote-provider/td-p/53552), the users reported when they use the **`setup-python`** action in their workflows, sometimes they will get the errors like as the following:
```
Check warning on line 1 in .github

@@github-actions
github-actions / Python 3.5 on macos-latest

.github#L1
There was a failure in sending the provision message: Unexpected response code from remote provider InternalServerErro
```
```
 Check failure on line 1 in .github

@github-actions
github-actions/ Python 3.5 on macos-latest

.github#L1
Provisioning request delayed or failed to send 5 time(s). This is over the limit of 3 time(s).
```

**Comment by konradpabjan** [comment]
Responded to customers/users in the ticket: https://github.community/t5/GitHub-Actions/Unexpected-response-code-from-remote-provider/m-p/56917/highlight/true#M10035

Infrastructure issue not related to this action (even though they were using `setup-python` during the time the error was hit)
