### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by winlover32** [actions/setup-python#795]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by HarithaVattikuti** [comment]
Closing as spam

**Comment by HarithaVattikuti** [comment]
Closing as spam
