### ISSUE TITLE
Question: does the rate limit apply to self-hosted GitHub runners?

### ISSUE THREAD

**Issue by davidham** [actions/setup-python#797]
**Description:**
We are experiencing the [rate limit issue](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#avoiding-rate-limit-issues) when running this action on our self-hosted GHES server, and with self-hosted runners. We are planning to migrate to GitHub Enterprise Cloud soon, but we will be keeping our self-hosted runners. Will we still need to supply a GH token when we are running GitHub Cloud but with self-hosted runners?

**Action version:**
v2

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Tools version:**
3.7

**Comment by aparnajyothi-y** [comment]
Hello @davidham, Thank you for creating this issue and we will look into it :)

**Comment by priyagupta108** [comment]
Hello @davidham, Thank you for reaching out.
Yes, you will still need to supply a GitHub token. As mentioned in the [advanced-usage.md](https://github.com/actions/setup-python/blob/871daa956ca9ea99f3c3e30acb424b7960676734/docs/advanced-usage.md#using-setup-python-on-ghes) , the `setup-python` action dynamically downloads Python distributions from `actions/python-versions` on github.com (outside of the appliance). These requests are made via unauthenticated requests by default, which are limited to [60 requests per hour per IP](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#:~:text=The%20primary%20rate%20limit%20for%20unauthenticated%20requests%20is%2060%20requests%20per%20hour.). If you have self-hosted runners making these requests, regardless of whether you are using GitHub Enterprise Cloud or a GHES, these rate limits apply. Providing a token will increase these rate limits and reduce the chance of encountering rate limit errors.

Hope this clarifies! :)

**Comment by davidham** [comment]
Sounds good, thanks @priyagupta108!

**Comment by priyagupta108** [comment]
Thank you for your response, @davidham! I'm going to close this issue now.
If you have any other issues or need any clarification, please feel free to reach out to us. :)
