### ISSUE TITLE
setup-python succeeds but python version not used in following steps (self-hosted)

### ISSUE THREAD

**Issue by JonathanRenon-EDB** [actions/setup-python#805]
**Description:**
setup-python runs successfully but is not being used by default in following steps.
the environment variable seem correctly set and running `/opt/hostedtoolcache/Python/3.9.18/x64/python --version` shows the correct version whereas `python --version` returns `3.10.12`
I understand the issue might also be in the self-hosted runner configuration but not sure what could cause it to ignore environment variable set by setup-python.

**Action version:**
`v4` or `v5`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**

`python-version: 3.9`
**Repro steps:**  
using self-hosted (aws) ubuntu-22.04 runner use setup-python with version 3.9

**Expected behavior:**
setup-python successfully runs and following steps use the specified version by default

**Actual behavior:**
setup-python successfully runs and following steps use stock version (here 3.10) of the runner

**Comment by HarithaVattikuti** [comment]
Hello @JonathanRenon-EDB,
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by priyagupta108** [comment]
Hello @JonathanRenon-EDB 👋 , just a gentle reminder regarding this issue. If you have any updates or need further assistance, please let us know :)

**Comment by JonathanRenon-EDB** [comment]
Hello,
Thanks for the input, I won't be able to provide more information, I'm not managing the runner myself, the PATH was tested and looked good, as you stated it's probably a shell configuration issue.
there is no point keeping the ticket opened here.
thank you for the time spent.
