### ISSUE TITLE
Could not make it work with self-hosted MacOs

### ISSUE THREAD

**Issue by buremba** [actions/setup-python#81]
The action doesn't seem to work on self-hosted MacOs. Here is the error log:

![image](https://user-images.githubusercontent.com/82745/79238686-5eceae00-7e78-11ea-9bbe-89cc8e3dd2f3.png)

I tried both:
```
- uses: actions/setup-python@v1
with:
          python-version: "3.8.2"
```

and without specifying the version:

```
- uses: actions/setup-python@v1
```

The documentation states that the latest version is 3.8.2 and it has built for x64. As you see in the picture, there is no `Available versions:` in the logs.

**Comment by konradpabjan** [comment]
If you're using a self-hosted runner, you need to setup the tools cache yourself. You can find instructions here: https://github.com/actions/setup-python#using-setup-python-with-a-self-hosted-runner

If you only need one version of Python, you can avoid using `setup-python` and whatever version of Python you have in PATH will be used.

Why is setup needed? Hosted runners that we maintain have multiple python versions cached and installed when the images get built. You can read up about it here: https://github.com/actions/setup-python#hosted-tool-cache

Essentially, if you're using one of our hosted runners, all that `setup-python` is doing is changing the `PATH variable to point to a version of Python that is already installed. If you're using a self-hosted runner, you have to download and setup the necessary versions of Python first.
