### ISSUE TITLE
Failed to set up python in my workflows

### ISSUE THREAD

**Issue by lyz0326** [actions/setup-python#810]
**Description:**
Error: No file in /home/runner/work/daily-sign/daily-sign matched to [**/poetry.lock], make sure you have checked out the target repository is https://github.com/lyz0326/daily-sign/
 The log:
[0_work.txt](https://github.com/actions/setup-python/files/14120540/0_work.txt)

The repost
**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
python 3.10

**Repro steps:**  
Every time I start the workflow.

**Expected behavior:**
The python document will work successfully.

**Actual behavior:**
It can't work in Actions.

**Comment by aparnajyothi-y** [comment]
Hello @lyz0326
Thank you for creating the issue and we will look into it.

**Comment by aparnajyothi-y** [comment]
"Hello @lyz0326 , Thank you once again for creating this issue.
We have investigated the issue as per the current implementation of cache dependency package managers. For the supported package manager poetry, The action defaults to searching for a dependency file of Poetry(poetry.lock for poetry) in the repository, and uses its hash as a part of the cache key. Input cache-dependency-path is used for cases when multiple dependency files are used, they are located in different subdirectories or different files for the hash that want to be used.
So in case of Poetry package manager, the respective repository should contain poetry.lock file as a cache dependency path or you can just supply poetry.lock file in the repository to work. We tested the both the approaches like by adding poetry.lock file/cach-dependency-path in our local it resolved the error (Error: No file in /home/runner/work/daily-sign/daily-sign matched to [**/poetry.lock], make sure you have checked out). Please find the below screenshots for reference.

For more information on caching packages dependecies, please refer this documentation"


<img width="965" alt="image" src="https://github.com/actions/setup-python/assets/147696841/17bd35f0-6de7-42fd-bdd9-b7462f060516">

<img width="1735" alt="image" src="https://github.com/actions/setup-python/assets/147696841/b3b27336-558c-4da6-87b8-e62443617927">

**Comment by aparnajyothi-y** [comment]
Hello @lyz0326, Please let us know, whether the issue resolved after adding the poetry.lock file to your repository or still you are still facing the same issue to provide further assistance. Thank you in advance.

**Comment by aparnajyothi-y** [comment]
Hello @lyz0326, Please confirm, whether the issue resolved after adding the poetry.lock file to your repository or still you are still facing the same issue to provide further assistance.

**Comment by aparnajyothi-y** [comment]
Hello @lyz0326, Proceeding to close this issue after two reminders as we didn't hear anything from you.
Feel free to reach us to reopen this for further assistance. Thank you.
