### ISSUE TITLE
pipx not found on macOS 14 runners

### ISSUE THREAD

**Issue by ghisvail** [actions/setup-python#820]
**Description:**
I can't run the test suite for my project in CI using the `macos-14` beta runners.

`actions/setup-python@v5` does not seem to provide or expose `pipx` for `macos-14` like it does for `macos-13`. 

**Action version:**
actions/setup-python@v5

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Python versions from 3.10 to 3.12

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**

Working on `macos-13`:

```
> Run pipx install hatch
creating virtual environment...
creating shared libraries...
upgrading shared libraries...
installing hatch...
done! ✨ 🌟 ✨
  installed package hatch 1.9.3, installed using Python 3.12.1
  These apps are now globally available
    - hatch
```

**Actual behavior:**

Failing on `macos-14`:

```
> Run pipx install hatch
/Users/runner/work/_temp/3cc431c7-bf69-4c05-874f-ddac7c522372.sh: line 1: pipx: command not found
Error: Process completed with exit code 127.
```

**Comment by mayeut** [comment]
`pipx` is managed in the https://github.com/actions/runner-images repo:
xref https://github.com/actions/runner-images/issues/9256

**Comment by aparnajyothi-y** [comment]
Hi @ghisvail, Thank you for creating this issue and we will look into it :)

**Comment by ghisvail** [comment]
TIL, `pipx` is provided by the base runner image, not this action.

Thanks @mayeut for the xref and my apologies for the duplicate :pray:

**Comment by aparnajyothi-y** [comment]
Hello @ghisvail, 
We are proceeding to close as this issue is not related to setup-python. Thank you.
