### ISSUE TITLE
J

### ISSUE THREAD

**Issue by Angel0Manuel** [actions/setup-python#836]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by HarithaVattikuti** [comment]
Closing as spammy
