### ISSUE TITLE
PyPy3 doesn't create envs properly on Windows, 7.3.1 would fix

### ISSUE THREAD

**Issue by altendky** [actions/setup-python#84]
https://github.com/pytest-dev/pytest-twisted/pull/85
https://foss.heptapod.net/pypy/pypy/issues/3155

In short, PyPy3 has used `bin/` everywhere instead of doing `Scripts/` on Windows.  While I wish \_everything\_ was consistently `bin/`, ...  it isn't.  PyPy3 7.3.1 corrects this.  Thanks for updating when you get a chance.

To help searches lead here, here's an example warning (to be an error at somepoint) from tox.

https://github.com/pytest-dev/pytest-twisted/pull/85/checks?check_run_id=459428253#step:5:15
```
WARNING: test command found but not installed in testenv
  cmd: C:\hostedtoolcache\windows\PyPy\3.6.9\x86\python.EXE
  env: D:\a\pytest-twisted\pytest-twisted\.tox\pypy3-defaultreactor
Maybe you forgot to specify a dependency? See also the whitelist_externals envconfig setting.
```

**Comment by konradpabjan** [comment]
PyPy 3.7.1 should be rolling out shortly to all images: https://github.com/actions/virtual-environments/issues/730

**Comment by miketimofeev** [comment]
@altendky The image with PyPy 7.3.1 has been rolled out. Could you check the behavior, please?

**Comment by altendky** [comment]
No luck so far.  I tried a few rebuilds and also bumped up to `setup-python@v2`.  I'll note that the above linked issue refers only to Ubuntu images.  I added some reporting of Python version since the existing build didn't report the PyPy version, only the version of the Python language it claims to support.  That still reads out 7.3.0.  Thanks for following up here.

https://github.com/pytest-dev/pytest-twisted/pull/85/checks?check_run_id=671909832

![image](https://user-images.githubusercontent.com/543719/81852143-92106580-9528-11ea-8eef-9149cdc0b7c7.png)

**Comment by miketimofeev** [comment]
@altendky @konradpabjan we've started a new image rollout with PyPy 7.3.1 on board. The propagation will take about 3-4 days.

**Comment by altendky** [comment]
@miketimofeev, I appreciate the progress update.  I'll keep an eye out.

**Comment by altendky** [comment]
As far as I can tell I'm still getting 7.3.0.  I think I'm using `windows-latest`.  Should I need to do something other than just triggering a new build?  The most recent one I started by closing and reopening https://github.com/pytest-dev/pytest-twisted/pull/85.

https://github.com/pytest-dev/pytest-twisted/pull/85/checks?check_run_id=736837323#step:5:19

Side note, the following pages list the implemented Python language version instead of the PyPy version.  Well, both would probably be nice.

https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md#pypy
https://github.com/actions/virtual-environments/blob/master/images/win/Windows2016-Readme.md#pypy

**Comment by miketimofeev** [comment]
@altendky we're going to finish new image deployment with PyPy 7.3.1 today. Here are pre-releases where PyPy listed properly
https://github.com/actions/virtual-environments/releases/tag/win19%2F20200531.1
https://github.com/actions/virtual-environments/releases/tag/win16%2F20200531.1

**Comment by altendky** [comment]
Looks good over at https://github.com/pytest-dev/pytest-twisted/runs/756007102.  Thanks!
