### ISSUE TITLE
my_script.py



### ISSUE THREAD

**Issue by FrequentC123** [actions/setup-python#844]
**Description:**
Describe your proposal.

**Justification:**
Justification or a use case for your proposal.

**Are you willing to submit a PR?**

![Screenshot-3.png](https://github.com/actions/setup-python/assets/166241504/97a39063-66e1-4d8c-bf0d-b1eb6c307323)

[]()ython

steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
  with:
    python-version: '3.10' 
- run: python my_script.py

**Comment by FrequentC123** [comment]
ython

steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
  with:
    python-version: '3.10' 
- run: python my_script.py

**Comment by aparnajyothi-y** [comment]
Closing as spammy
