### ISSUE TITLE
Failing with current ubuntu:latest container

### ISSUE THREAD

**Issue by ay0o** [actions/setup-python#854]
**Description:**
Starting somewhere between yesterday and today, `setup-python` is failing with the current `ubuntu:latest` container.

**Action version:**
`v4`, `v5`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**
All versions.

**Repro steps:**  
Use the action with any job with `container: ubuntu:latest`

**Expected behavior:**
Python is configured

**Actual behavior:**
```
 Version 3.12 was not found in the local cache
  Error: The version '3.12' with architecture 'x64' was not found for this operating system.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Workaround:**
Instead of `latest`, use another tag such as `22.04`.

**Comment by HarithaVattikuti** [comment]
Hello @ay0o 
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by ay0o** [comment]
this is the SHA of the current latest: `sha256:562456a05a0dbd62a671c1854868862a4687bf979a96d48ae8e766642cd911e8`

**Comment by bdlake** [comment]
Experienced the same error on our self-hosted runners using `ubuntu:latest` base image. Just as @ay0o suggested, using `ubuntu:22.4` for latest 22.04 image fixed the issue. Seems that latest 22.04 image caused it https://hub.docker.com/layers/library/ubuntu/latest/images/sha256-28a2b328825ac02db5c29d9356bfba80ba6c4b6ebfcac5a91a4656fa3453775a?context=explore

**Comment by ay0o** [comment]
the content of `/etc/lsb-release` has not changed and uses the same format as expected by the code of the action in the `_getOsVersion()` function:
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"
```

Also, just in case something odd happened, `os.platform()` returns `linux` as expected:

```
> os.platform()
'linux'
```

**Comment by ay0o** [comment]
So, in summary:

Ubuntu 24.04 was released a week ago and since then, marking the beginning of this issue because the tag `latest` replaced the previous version.

However, [python-versions](https://github.com/actions/python-versions) has not caught up with it and it's missing the release for 24.04.

**Comment by ay0o** [comment]
Ubuntu 24.04 is already available at https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json, hence solving this issue

**Comment by aparnajyothi-y** [comment]
Hello @ay0o, Thank you once again for creating this issue. We have investigated the issue, actions/python-versions added the support for python-version : 3.12.3 for ubuntu-24.04 and ubuntu-latest tag is placed to 22.04 instead of 24.04. Please find the screenshots for reference.
Please let us know in case of any further clarifications needed.
<img width="1367" alt="image" src="https://github.com/actions/setup-python/assets/147696841/fc1582a4-eda2-45fc-a340-662c84d6a5bd">

<img width="988" alt="image" src="https://github.com/actions/setup-python/assets/147696841/6ed8ec68-b30c-4a00-ad7d-9c93a810d792">

**Comment by stweil** [comment]
"Run actions/setup-python@v5" still fails in my GitHub actions with Ubuntu 24.04 (see [example](https://github.com/stweil/ocrd_all/actions/runs/9233671289/job/25406386606).
