### ISSUE TITLE
Getting `A new release of pip is available: 21.1.1 -> 24.0` on `macos-latest`

### ISSUE THREAD

**Issue by IAmVigneswaran** [actions/setup-python#862]
**Description:**
For some reason, I am getting this error when building for macOS binary.

https://github.com/TheAcharya/Airlift/actions/runs/9012264975/job/24761207438#step:6:43

```
[notice] A new release of pip is available: 21.1.1 -> 24.0 [notice] To update, run: python3.8 -m pip install --upgrade pip
```

**Action version:**
https://github.com/TheAcharya/Airlift/actions/runs/9012264975

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  

This is my workflow .yml  file.

https://github.com/TheAcharya/Airlift/blob/7860a2735257e7b93b3eba5fbc593ac66d8e3310/.github/workflows/release_github_text.yml#L96

**Expected behavior:**
Based on the action logs, `Successfully installed pip-24.0` is stated. 

**Actual behavior:**
But unsure why is `Notice:  A new release of pip is available: 21.1.1 -> 24.0` shown.

Could you please advise.

Thank you.

**Comment by IAmVigneswaran** [comment]
I believe I have resolve the issue by adding this.

https://github.com/TheAcharya/Airlift/blob/beec8e516ad23f8484defbd9d344ec043e6a56bc/.github/workflows/release_github.yml#L94

```
        uses: actions/setup-python@v5
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1
```

Thank you.

**Comment by HarithaVattikuti** [comment]
Hello @IAmVigneswaran 
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by Nik12325** [comment]
uses: actions/setup-python@v5
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1

**Comment by mayeut** [comment]
@HarithaVattikuti, a rebuild of 3.8.10 should fix this.

**Comment by gowridurgad** [comment]
Hello @IAmVigneswaran , The issue you're encountering is due to the runner images not supporting Python version 3.8, which results in the error message. If you prefer not to see this error message, you can suppress it by adding the environment variable PIP_DISABLE_PIP_VERSION_CHECK=1 to your workflow. This will disable the version check that pip executes.

**Comment by IAmVigneswaran** [comment]
@gowridurgad Thanks for the info! I have already added the environment variable.

https://github.com/TheAcharya/csv2notion-neo/blob/d2290e5dff5a4b767c559b55b1dcd0224d48e7a5/.github/workflows/release_github.yml#L94

**Comment by gowridurgad** [comment]
Hi @IAmVigneswaran, Thanks for the confirmation, we are proceeding to close this issue as the runner images
 not supporting Python version 3.8, which results in the error message. If you need any future clarifications please feel free to reach us out.
