### ISSUE TITLE
Missing support for Python 3.8 on Ubuntu 24.04 runner

### ISSUE THREAD

**Issue by stweil** [actions/setup-python#879]
**Description:**
"Run actions/setup-python@v5" fails for Python 3.8 in GitHub actions with Ubuntu 24.04 (see [example](https://github.com/stweil/ocrd_all/actions/runs/9233671289/job/25406386606)).

**Action version:**
actions/setup-python@v5

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Python 3.8

**Repro steps:**  
See link above

**Expected behavior:**
Python 3.8 should be supported (or documented as unsupported).

**Actual behavior:**
Python 3.8 does not work with the Ubuntu 24.04 runner.

**Comment by aparnajyothi-y** [comment]
Hello @stweil, Thank you for creating this issue and we will look into it :)

**Comment by aparnajyothi-y** [comment]
Hello @stweil, Thank you for creating this issue. We now have support for Python 3.8 on the Ubuntu 24.04 runner, as artifacts for the latest patch version of the Python 3.8 x64 package have been generated and released. Please find the [test workflow run](https://github.com/setup-actions-demo/test-setup-python/actions/runs/9852179191/job/27200172823) for reference.
We are closing this issue as it has been addressed. Please feel free to reach out if you need any further support or clarification, and we can reopen the issue if necessary.
