### ISSUE TITLE
Version not found when using new arm-based linux runners (ubuntu 22.04)

### ISSUE THREAD

**Issue by juanitosvq** [actions/setup-python#882]
**Description:**
I just created a runner using the newly available arm-based linux images for GitHub actions: https://github.blog/changelog/2024-06-03-actions-arm-based-linux-and-windows-runners-are-now-in-public-beta/
I am using Ubuntu 22.04 for this runner:
![image](https://github.com/actions/setup-python/assets/43006530/124059c4-ad15-4514-9f54-cc238ce4030c)

When trying to use the actions/setup-python@v5 to set up python 3.9, the action is failing with:
> The version '3.9' with architecture 'arm64' was not found for Ubuntu 22.04.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

**Action version:**
actions/setup-python@v5 

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Python 3.9

**Repro steps:**  
Create a runner using the new arm-based linux, selecting Ubuntu 22.04 by Arm Limited as Image name. Use that new runner in a GitHub Action and try to set up python3.9 using the action.

**Expected behavior:**
Should be able to set up python 3.9 in an arm-based Ubuntu 22.04 runner.

**Actual behavior:**
Unable to set up python 3.9 in an arm-based Ubuntu 22.04 runner.

**Comment by aparnajyothi-y** [comment]
Hello @juanitosvq, Thank you for creating this issue and we will look into it :)

**Comment by AlissonMachadoEmbitel** [comment]
i have the same issue, but trying to use the python3.11.9

**Comment by atwoodjw** [comment]
It's a little surprising setup-python doesn't support ARM-based Python versions yet, given ARM-based runners are in public beta now. We were able to get around this by [running jobs in a container](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container) (not using setup-python).

**Comment by aparnajyothi-y** [comment]
Hello Everyone, We are excited to announce that we've recently incorporated support for ARM64 packages on Ubuntu 22.04 ARM64 runner as part of this [Pull Request](https://github.com/actions/python-versions/pull/289). Our tests have confirmed their functionality.
With the release of Python 3.9 support for ARM64, we are now proceeding to close the related issue. However, we encourage you to verify this update from your end.
Should you encounter any further issues or require additional clarifications, please don't hesitate to reach out. We stand ready to reopen the issue if necessary.
