### ISSUE TITLE
Add Python 3.12.4 (released 2 days ago)

### ISSUE THREAD

**Issue by TWiStErRob** [actions/setup-python#883]
**Description:**

I have automated updates for everything via Renovate.
It found an upgrade for https://www.python.org/downloads/release/python-3124/
But the PR's CI failed: https://github.com/TWiStErRob/net.twisterrob.ghlint/pull/315
and while investigating, the threads lead to this repo/issue.

> Error: The version '3.12.4' with architecture 'x64' was not found for Ubuntu 22.04.

![image](https://github.com/actions/setup-python/assets/2906988/7d88da10-5c7f-40a8-bfec-b5506abcc9b9)

**Justification:**

https://github.com/actions/python-versions#:~:text=Please%20open%20an%20issue

**Are you willing to submit a PR?**

No, but I wonder if this should be automated? If Renovate is able to see new versions as soon as they come out, so does Dependabot, therefore it could open a new PR with the right contents as soon as a new version is released?

**Comment by jkowalleck** [comment]
python is fetched from https://github.com/actions/python-versions/releases/
If they dont have the thing you need, then this action cannot fetch it :-)

**Comment by aparnajyothi-y** [comment]
Hello @TWiStErRob, we merged the [PR](https://github.com/actions/python-versions/pull/284) to add python 3.12.4 support. Please validate from your end.

**Comment by TWiStErRob** [comment]
Confirmed working.

Is it normal to have days between release / automated PR opened / getting merged? Or was there an issue?

**Comment by aparnajyothi-y** [comment]
Hello @TWiStErRob, Thank you for confirming that 3.12.4 packages are working and post the release of 3.12.4 version from source, artifacts for 3.12.4 will be generated and released from actions/python-versions. There is a delay in releasing the 3.12.4 artifacts to fix the issue that caused corrupted artifacts.
We are proceeding to close this issue and feel free to reach us to reopen this issue in case of any further clarifications.
