### ISSUE TITLE
Support os-release standard

### ISSUE THREAD

**Issue by aaroncameron-wk** [actions/setup-python#890]
**Description:**
When `PipCache` attempts to generate `pip` cache keys and [invokes](https://github.com/actions/setup-python/blob/82c7e631bb3cdc910f68e0081d67478d79c6982d/src/cache-distributions/pip-cache.ts#L69) `getLinuxInfo` while running on Amazon Linux 2023, the following error occurs:
> Error: Unable to locate executable file: lsb_release. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

This is also triggered when [attempting to report errors](https://github.com/actions/setup-python/blob/82c7e631bb3cdc910f68e0081d67478d79c6982d/src/find-python.ts#L92) when searching for Python versions, so this action fails to even give helpful error information when a missing `lsb_release` isn't even the issue.

This is caused by [the dependency](https://github.com/actions/setup-python/blob/82c7e631bb3cdc910f68e0081d67478d79c6982d/src/utils.ts#L170-L172) on `lsb_release`, which is [not available on Amazon Linux 2023](https://github.com/actions/setup-python/blob/82c7e631bb3cdc910f68e0081d67478d79c6982d/src/utils.ts#L170-L172):
> AL2023 doesn't ship with the lsb_release command, and doesn't include the system-lsb-core package. Software should complete the transition to the os-release standard to maintain compatibility with Amazon Linux and other major Linux distributions.

An alternative is the [os-release standard](https://www.freedesktop.org/software/systemd/man/latest/os-release.html). Using this, at least as a fallback, would go a long way in improving the limited support of AL2023.

**Action version:**
5.1.0

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
N/A

**Repro steps:**  
Run this action on an Amazon Linux 2023 self-hosted runner with `cache: 'pip'`.

**Expected behavior:**
Action behaves as expected with pip dependencies cached.

**Actual behavior:**
> Error: Unable to locate executable file: lsb_release. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

**Comment by aparnajyothi-y** [comment]
Hello @aaroncameron-wk, Thank you for creating this issue and we will look into it :)

**Comment by mahabaleshwars** [comment]
Hello @aaroncameron-wk, 
Thank you for your insightful comments. At present, 'setup-python' utilizes 'lsb_release' for 'cache:pip' execution. The 'actions/cache' feature can be used for caching. However, please be aware that even though Amazon Linux 2023 supports GLIBC 2.34, the caching process demands an upgrade to GLIBC 2.35.

**Comment by mahabaleshwars** [comment]
Hello @aaroncameron-wk, could you please confirm if the feedback addresses your concern?

**Comment by mahabaleshwars** [comment]
Hello @aaroncameron-wk, please review the feedback provided above. we are closing this issue now. Feel free to reach out to us for any other issues.
