### ISSUE TITLE
Sporadically missing patch versions on python-versions for arm64

### ISSUE THREAD

**Issue by chris-griffin** [actions/setup-python#892]
**Description:**
Linux arm64 support was recently added to `python-versions` (https://github.com/actions/python-versions/pull/274). Many supported arm64 versions are available on main now (search for `arm64`) as you can see here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json.

These are the versions available (excluding non-releases). As you can see many patch versions are inextricably missing:
- 3.12.0-3.12.4 (all present)
- 3.11.3-3.11.9 (missing 3.11.0-3.11.2)
- 3.10.11 (missing 3.10.0-3.10.10 and **missing the latest patch** 3.10.12-3.10.14 ) 
- 3.9.13 (missing 3.9.0-3.9.12 and **missing the latest patch** 3.9.14-3.9.19)
- 3.8.10 (missing 3.8.0-3.8.9 and **missing the latest patch** 3.8.11-3.8.19)

However, many patch versions of python are missing. For example,

**Action version:**
All

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

- 3.11.0-3.11.2
- 3.10.0-3.10.10 and 3.10.12-3.10.14
- 3.9.0-3.9.12 and 3.9.14-3.9.19
- 3.8.0-3.8.9 and 3.8.11-3.8.19

**Repro steps:**  
Go to https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json and try to find the `3.9.19` version for "arch": "arm64" (or for any other version listed under the **Tools version** section)

**Expected behavior:**
All patch python versions listed under the **Tools version** section should be available for arm64

**Actual behavior:**
All patch python versions listed under the **Tools version** section are not available for arm64

**Comment by aparnajyothi-y** [comment]
Hello @chris-griffin, Thank you for creating this issue and we will look into it :)

**Comment by chris-griffin** [comment]
This was partially addressed in https://github.com/actions/python-versions/pull/289

For example, `python-3.9.19-linux-22.04-arm64.tar.gz` is now available although `python-3.9.19-darwin-arm64.tar.gz` remains unavailable. Additionally, 3.9.0-3.9.12 and 3.9.14-3.9.18 are still missing.

**Comment by chris-griffin** [comment]
> due to the fact that the Darwin arm64 artifact is not present at the source currently

Could you clarify what/where the source is in this context?

> The reason for the missing patch versions of linux arm64 packages is due to linux arm64 runners unavailability and post availity of those runners, linux arm64 packages are generated and released for the latest patch version only starting from 3.8 to 3.13.

Ok understood, thanks

**Comment by aparnajyothi-y** [comment]
Hello @chris-griffin, Thank you for your response. The python-3.9.19-darwin-arm64.tar.gz file is unavailable because the Darwin ARM64 artifact is not provided on the [official Python website](https://www.python.org/ftp/python/3.9.19/). 
We are proceeding to close this issue since the Linux ARM64 packages are generated and released for the latest patch version, contingent on their availability from the official Python website. If you need any further clarifications or support, please feel free to reach out to us to reopen this issue.
