### ISSUE TITLE
python-config in python3 setup

### ISSUE THREAD

**Issue by aragon999** [actions/setup-python#91]
The `python-config` script is not properly replaced, after using the `setup-python` action:
```
$ which python 
/opt/hostedtoolcache/Python/3.8.2/x64/bin/python
$ which python3
/opt/hostedtoolcache/Python/3.8.2/x64/bin/python3
$ which python-config
/usr/bin/python-config
$ which python3-config
/opt/hostedtoolcache/Python/3.8.2/x64/bin/python3-config
```
which will probably cause hard to debug issues, so my suggestion is, to either not replace "python" itself (probably a bad idea) or to properly replace (symlink) `python-config` to `python3-config`.

I have not tested what happens when using Python 2.

**Comment by nikita-bykov** [comment]
Hello @aragon999!
This issue has been open for a year without any activity, so I'm going to close it as stale.
Please feel free to contact us if the issue is still relevant to you and we will reopen it.
Thanks!
