### ISSUE TITLE
Python Version 3.9.2 was not found in the local cache 

### ISSUE THREAD

**Issue by badingaLuc** [actions/setup-python#920]
**Description:**
Log

Run actions/setup-python@v4
  with:
    python-version: 3.9
    check-latest: false
    token: ***
    update-environment: true
    allow-prereleases: false
Installed versions
  Version 3.9 was not found in the local cache
  Error: The version '3.9' with architecture 'arm64' was not found for Debian 11.

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows
- [x] Debian 

**Runner type:**
- [ ] Hosted
- [x] Self-hosted (Raspberry OS latest)

**Tools version:**
3.9.2

**Repro steps:**  
    runs-on: self-hosted

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

**Expected behavior:**
Find a python version

**Actual behavior:**
Failed to find

**Comment by aparnajyothi-y** [comment]
Hello @badingaLuc, Thank you for creating this issue and we will look into it :)

**Comment by priyagupta108** [comment]
Hi @badingaLuc,
Thank you for your report. Please note that Python distributions are only available for [environments](https://github.com/actions/virtual-environments#available-environments) that GitHub Actions hosted runners support. For more details, refer to this [document](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-setup-python-with-a-self-hosted-runner). If you're using an unsupported Linux distribution such as Debian, `setup-python` will not work. We are proceeding to close this ticket. Thank you for your understanding.
