### ISSUE TITLE
Python 3.12.5 missing

### ISSUE THREAD

**Issue by sscheib** [actions/setup-python#922]
**Description:**
Python 3.12.5 is not available for installation 

**Action version:**
Specify the action version: latest

**Platform:**
- [ x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x ] Hosted
- [ ] Self-hosted

**Comment by priyagupta108** [comment]
Hello @sscheib. Thank you for your report. We'll take a look on it.

**Comment by priyagupta108** [comment]
Hello @sscheib,
The Python 3.12.5 was added in scope of the following PR: [actions/python-versions#303](https://github.com/actions/python-versions/pull/303). For now I'm going to close the issue. Thank you!

**Comment by sscheib** [comment]
Thanks @priyagupta108 for the swift response and the fix! I can confirm it works perfectly 🥳
