### ISSUE TITLE
submit Pull request

### ISSUE THREAD

**Issue by Rockyspade** [actions/setup-python#927]
**Description:**
Describe your proposal.

**Justification:**
Justification or a use case for your proposal.

**Are you willing to submit a PR?**

**Comment by Rockyspade** [comment]
#gh #872   authorize merger {feature} {need triage} custome set up

**Comment by Rockyspade** [comment]
#872 close merger my-branch @Rockyspade rocky @magnetikonline @ukd1 @ukd1

**Comment by priya-kinthali** [comment]
Closing this issue as it seems like spam.

**Comment by Rockyspade** [comment]
It's seem like spam we eat? 😂 Closed
