### ISSUE TITLE
`python-version` is ignored on MacOS runners

### ISSUE THREAD

**Issue by christophfink** [actions/setup-python#929]
**Description:**
Specifying a `with: python-version` works for Windows and Linux runners, but seemingly is ignored on MacOS runners, where `setup-python` resorts to the newest Python version available

**Action version:**
actions/setup-python@5

**Platform:**
- [ ] Ubuntu
- [X] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
n/a

**Repro steps:**  
Run a GitHub workflow YAML file that specifies a `python-version` on MacOS runners. See below for an example YAML, and the following repo for a running example: https://github.com/christophfink/gh-actions-python-versions/actions/runs/10508872098 

**Expected behavior:**
`actions/setup-python` installs the requested python version (as on Windows and Linux runners)

**Actual behavior:**
`actions/setup-python` installs the ~latest~ _edit:_ default python version

![Screenshot 2024-08-22 at 15 10 49](https://github.com/user-attachments/assets/cec2d8dc-41e1-4881-8094-fcf7fa772414)

**Comment by priya-kinthali** [comment]
Hello @christophfink 👋,
Thank you for reporting this. We will investigate the issue and get back to you as soon as we have updates.

**Comment by priya-kinthali** [comment]
Hello @christophfink 👋,

Thank you for raising this issue. It seems that the problem with the `python-version` being ignored on MacOS runners may be related to the shell configuration specified in your workflow which is `shell: bash -l {0}`.
To avoid this, it is recommended to use the shell configuration like : `shell: bash`. 
For more details details, please refer to the related discussion here: [actions/setup-python#179 (comment)](https://github.com/actions/setup-python/issues/179#issuecomment-750495666). 
I hope this helps!

**Comment by christophfink** [comment]
Hi @priya-kinthali !

Thanks for your quick help, this is, indeed, fixing the issue for me. The linked issue has a great explanation, thanks for that, too.
