### ISSUE TITLE
Poetry cache docs are incorrect

### ISSUE THREAD

**Issue by AdrianDAlessandro** [actions/setup-python#940]
**Description:**
The poetry cache docs claim:

> If the `setup-python` version does not match the version specified in `pyproject.toml` and the python version in `pyproject.toml` is less than the runner's python version, `poetry install` will default to using the runner's Python version.

However this does not appear to be the case. You can see in [this workflow run](https://github.com/ImperialCollegeLondon/Auto-CORPus/actions/runs/10790043567/job/29924352087#step:6:13) that Python 3.10 is being used despite the runner's Python version being 3.12

The paired Windows action used Python 3.9 (the failure is for an unrelated reason)

**Action version:**
v5 (I'm guessing v5.2.0 was used, as it's the most recent release)

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**

Poetry version 1.8.3
Python version variability is the issue (3.9, 3.10, 3.12)
Unsure of pipx version

**Repro steps:**  
Create a python test workflow with poetry cache as [described in the docs for this action](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages). Specify Python version 3.12, but have a Python version restriction of <3.11 in the pyproject.toml

[The workflow file used](https://github.com/ImperialCollegeLondon/Auto-CORPus/blob/774c25cbd24dfec20452698f1500da75a567260e/.github/workflows/ci.yml) for the above error.

**Expected behavior:**
Workflow run fails because of incompatible python versions. The docs should also be correct.

**Actual behavior:**
Workflow succeeds, but uses the wrong python version, so it is not running what you think you are running.

**Comment by aparnajyothi-y** [comment]
Hello @AdrianDAlessandro, Thank you for creating this issue and we will get back to you once we have some feedback on this :)

**Comment by AdrianDAlessandro** [comment]
Hi @gowridurgad, yes this makes sense and is in line with what I expected, thank you!

I think maybe the docs in this action should be updated to make that clear. The note in the [Caching packages](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages) section is slightly misleading.

I can see why I misunderstood them now, so I'll try and explain it. The note says:
>**Note:** If the `setup-python` version does not match the version specified in `pyproject.toml` and the python version in `pyproject.toml` is less than the runner's python version, `poetry install` will default to using the runner's Python version.

I think this is technically the same thing you explained above, but the double use of "runner's python version" to mean two different things (the version installed by the `setup-python` **and** the default python version in the runner) is confusing.

Maybe it should be reworded as follows:
>**Warning:** If the `python-version` chosen in `setup-python` does not match the version restrictions in `pyproject.toml`, `poetry install` will fall back to using the default Python version of the host runner (whatever that may be).

Out of curiosity: what happens if the version restrictions in `pyproject.toml` is less than the default runner version? So for the example you shared this would be restricting it to Python `"<3.10"`

**Comment by gowridurgad** [comment]
Hi @AdrianDAlessandro, Thank you for the suggestion to reword the documentation for clarity. We will review and update the note in the Caching packages section accordingly.

Regarding your question, if the version restrictions in pyproject.toml specify a version less than the default runner version (e.g., Python "<3.10"), Poetry will attempt to find a compatible version. If it cannot find one, it will result in an error.

To avoid this, explicitly specify a compatible Python version in the GitHub Actions workflow using the setup-python action:

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'poetry'
    - run: poetry install
```

**Comment by gowridurgad** [comment]
Hi @AdrianDAlessandro, We are glad that you are satisfied with the explanation. We are proceeding to close this issue. If you have any further questions or need additional clarifications, please feel free to reach out.
