### ISSUE TITLE
Python version '3.11.9' not found on Debian 12

### ISSUE THREAD

**Issue by eismont21** [actions/setup-python#946]
**Description:**
The version '3.11.9' with architecture 'x64' was not found for this operating system. Yesterday everything was working correctly.

**Operating System:**
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
Kernel and Architecture Information=Linux 6.8.0-1014-azure #16~22.04.1-Ubuntu SMP Thu Aug 15 21:31:41 UTC 2024 x86_64 GNU/Linux

**Action version:**
```
uses: actions/setup-python@v5
with:
  python-version: "3.11.9"
```        

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Tools version:**

Requested Python Version: 3.11.9

**Actual behavior:**
Installed versions:
Version 3.11.9 was not found in the local cache.
Error: The version '3.11.9' with architecture 'x64' was not found for this operating system.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

**Comment by priyagupta108** [comment]
Hi @eismont21 👋 , 
Thank you for your report. We'll investigate the issue and get back to you.

**Comment by gowridurgad** [comment]
Hi @eismont21, We acknowledge your report. Please note that Python distributions are only available for [environments](https://github.com/actions/runner-images#available-environments) that GitHub Actions hosted runners support. For Future information, you can refer  to this [document](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-setup-python-with-a-self-hosted-runner) . If you're using an unsupported Linux distribution such as Debian, setup-python will not work. We are proceeding to close this ticket. Thank you for your understanding.
