### ISSUE TITLE
self-hosted runner failing while trying to get version

### ISSUE THREAD

**Issue by tabossert** [actions/setup-python#96]
**Describe the bug**
Getting the following error when running
`Version 3.x was not found in the local cache
##[error]Version 3.x with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/master/versions-manifest.json`

I have tried both v1 and v2 of setup-python and have tried setting a specific version or latest minor like above.  I am running an amazon-linux runner and I am wondering if this will only work on Ubuntu.  Could you provide some guidance.  Thanks

**Which version of the action are you using?**

- [ ] `v1`
- [ X ] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ X ] self-hosted
- [ X ] Linux
- [ ] Windows
- [ ] Mac

If applicable, please specify if you're using a container
Not using containers

**Python Versions**
Please list all of the effected versions of Python (`3.8.2`, etc.)
3.7.7, 3.x

**To Reproduce**
1. Add setup action step to actions file
2. Set Actions file to use self-hosted runner
3. Run action

**Run/Repo Url**
Private repo

**Screenshots**
<img width="1136" alt="Screen Shot 2020-05-23 at 9 49 06 AM" src="https://user-images.githubusercontent.com/37596773/82735951-b0b9ed80-9cda-11ea-847a-9a5682f32a5a.png">

**Additional context**
The runner is using amazon-linux2 based ami

**Comment by tabossert** [comment]
Seems it does work on Ubuntu with same config, might be good to add that this is Ubuntu only in readme for self-hosted

**Comment by etienne-napoleone** [comment]
I also can't run those steps locally with act on mac

**Comment by konradpabjan** [comment]
Officially we only support Python for the environments that are listed out here: https://github.com/actions/virtual-environments#available-environments

We compile Python from source for Ubuntu 1604, 1804 and Mac (10.15), the available versions for download are listed out here: https://github.com/actions/python-versions/blob/master/versions-manifest.json

If you have a local runner with something like Ubuntu 1904, then the `platform_version` will be different so nothing will be found in the manifest and the action will fail with the error you see. Same thing for Mac if you're using 10.16 (support should be coming soon-ish). 

There are two things we can do here

- [ ] Update the `README`
   - Mention we only support the same platforms as those listed in `virtual-environments`
   - Explain why we only support those platforms
         - Maintenance, maintenance, maintenance 
         - For Ubuntu and Mac, we compile from source so it is impossible to support all Linux distros and we have no plans to support more.
         - For Windows we download and use the MSI installers so those should work on all versions
- [ ] Even more logging and a better error message that says exactly why no version was found. It's very ambiguous right now.

**Comment by mariocesar** [comment]
Having the same issue with Ubuntu 18.04, I tried some other workarounds like setting the env RUNNER_TOOL_CACHE 
RUNNER_TEMP to writable directories, but no change on the output.

Is for sure this is related to the Ubuntu version where the runner is ?

**Comment by ukstv** [comment]
Hit this too. This seems like an issue in https://github.com/actions/toolkit. It reads version from `/etc/lsb-release` which seems to be deprecated in favour of `/etc/os-release`. Proposed fix in https://github.com/actions/toolkit/pull/594

**Comment by melroyvandenberg** [comment]
Help!?

**Comment by DavidGOrtega** [comment]
👋 we hit this within an ubuntu 18.04 image, I mean a self hosted runner being executed within an ubuntu 18.04

**Comment by DavidGOrtega** [comment]
As you can see @konradpabjan we even find the proper version and we download it

```
Download from "https://github.com/actions/python-versions/releases/download/3.8.4-96744/python-3.8.4-linux-18.04-x64.tar.gz"
Extract downloaded archive
```
But then the error is hit
