### ISSUE TITLE
Version 3.7 was not found in the local cache

### ISSUE THREAD

**Issue by ebattat** [actions/setup-python#962]
**Description:**
Ubuntu-latest
```
Run actions/setup-python@v5
  with:
    python-version: 3.7
    check-latest: false
    token: ***
    update-environment: true
    allow-prereleases: false
Installed versions
  Version 3.7 was not found in the local cache
  Error: The version '3.7' with architecture 'x64' was not found for Ubuntu [2](https://github.com/redhat-performance/benchmark-runner/actions/runs/11322675100/job/31484171496#step:3:2)4.04.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
For more details [see failed job]( https://github.com/redhat-performance/benchmark-runner/actions/runs/11322675100/job/31484171496)
**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

'3.7'
**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by kajweb** [comment]
Encountered the same problem.
python 3.7

**Comment by ebattat** [comment]
It's very disappointing that no one from GitHub Actions support fixed this issue immediately. (cc @kajweb )
Currently we remove Python 3.7 from our project support due to it. [PR](https://github.com/redhat-performance/benchmark-runner/pull/919)

**Comment by rjt-moonpay** [comment]
I have just started having the same issue in my actions that are using python 3.8.12 (Version 3.8.12 was not found in the local cache) - i can see it still exists in the [versions manifest](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json), so not sure why this is erroring

**Comment by rjt-moonpay** [comment]
i just realised my job was running on `ubuntu-latest` (24.04). I've fixed the Ubuntu version to 22.04 and this has resolved the issue. Looking at the versions manifest there is no version available for 24.04
![Uploading Screenshot 2024-10-15 at 12.52.10.png…]()

**Comment by aparnajyothi-y** [comment]
Hello Everyone, The Python 3.7 version is not available for Ubuntu 24.04 x64, which is why you are encountering this problem. This version is also not available for the available packages from source in the runner tool cache because it reached its End of Life (EOL) last year. We recommend using the latest versions of Python to avoid such issues. Please find the screenshots for reference.
Please feel free to reach us if any further clarifications needed.

**Comment by vtsvetkov-splunk** [comment]
Unfortunately, some projects can't upgrade from 3.7. As a fix we changed from `ubuntu-latest` to `ubuntu-22.04`.

**Comment by aparnajyothi-y** [comment]
Hello @ebattat, please let us know if the information provided above resolved your issue? If you have any further concerns or questions, feel free to reach out.

**Comment by ebattat** [comment]
@aparnajyothi-y,

Yes, I have removed Python3.7 from my project.

**Comment by aparnajyothi-y** [comment]
Hello @ebattat, Thank you for your confirmation and we are proceeding to close this issue.

Please feel free to reach us, If you encounter any further issues or need assistance.

**Comment by LatentDream** [comment]
Oups, didn't mean to tag the link from a commit message
