### ISSUE TITLE
Update documentation around `architecture` field to include arm64

### ISSUE THREAD

**Issue by michael-myers** [actions/setup-python#966]
**Description:**
In the setup-python [README](https://github.com/actions/setup-python?tab=readme-ov-file#supported-architectures) and code comments in [action.yml](https://github.com/actions/setup-python/blob/main/action.yml#L13) the `architecture` field only mentions x86 and x64, but [elsewhere](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/about-larger-runners#limitations-for-macos-larger-runners), GitHub Actions documentation says arm64 is a supported architecture across all GitHub-provided Actions. It seems like that is true, but the documentation here hasn't been updated.

If _not_ supplying the `architecture` field, will setup-python still default to x64 even on an arm64 host? Because it looks like [it will default to the arch of the host OS](https://github.com/actions/setup-python/blob/9c76e716502b18322365741b762fee22a8cffad8/src/setup-python.ts#L98).

**Action version:**
v5.2.0

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

It seems GitHub Actions provides hosted arm64 runners for all three platforms.

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**
n/a, this is about documentation

**Repro steps:**  
n/a, this is about documentation

**Expected behavior:**
n/a, this is about documentation

**Actual behavior:**
n/a, this is about documentation

**Comment by priyagupta108** [comment]
Hi @michael-myers 👋,
Thank you for pointing out the discrepancy in the documentation regarding the architecture field.
To clarify, when the architecture field is not specified, the action defaults to the host OS architecture, which includes arm64 for arm64 hosts.
We will update the documentation accordingly. If you have any additional insights or spot other documentation gaps, please let us know.

**Comment by priya-kinthali** [comment]
Hello @michael-myers 👋,
We have recently merged [PR #965](https://github.com/actions/setup-python/pull/965), which updates the [README](https://github.com/actions/setup-python#supported-architectures) and action.yml to include arm64 support in the architecture field.
Please check the updated documentation. We will now proceed to close this issue. If you have any further questions or concerns, please feel free to let us know.
Thank you!

**Comment by michael-myers** [comment]
Looks good to me, and thank you for the quick resolution! 👍🏻
