### ISSUE TITLE
Self-hosted runner fails on Mac

### ISSUE THREAD

**Issue by sanzgiri** [actions/setup-python#97]
**Describe the bug**
Self-hosted runner fails on Mac
**Which version of the action are you using?**
See this issue with both versions
- [ x] `v1`
- [ x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [ ] Linux
- [ ] Windows
- [x ] Mac

If applicable, please specify if you're using a container

**Python Versions**
Please list all of the effected versions of Python (`3.8.2`, etc.)
3.7.3, 3.7.7
**To Reproduce**
- Run action https://github.com/sanzgiri/action-numerai/runs/715859359
- If I specify python 3.7.3 or 3.7.7 for the action, it fails 
##[error]Version 3.7.3 with arch x64 not found even though that is currently the version on the mac

- If I specify python-version: '3.x' 
I get the error:

Version 3.x was not found in the local cache
Version 3.x is available for downloading
Download from "https://github.com/actions/python-versions/releases/download/3.8.3-20200514.1/python-3.8.3-macos-1014-x64.tar.gz"
Extract downloaded archive
/usr/bin/tar xz -C ./9c99d59e-64bf-4cba-9166-fe20af925cd6 -f /Users/sanzgiri/actions-runner/_work/_temp/9c99d59e-64bf-4cba-9166-fe20af925cd6
Execute installation script
##[error]The process '/bin/bash' failed with exit code 134

**Run/Repo Url**
If applicable, and if your repo/run is public, please include a URL so it is easier for us to investigate.
Private Repo 

**Screenshots**

**Additional context**

**Comment by sanzgiri** [comment]
I tried this again after several weeks. I now see an error is reported: 

`##[error]dyld: Library not loaded: /Users/runner/hostedtoolcache/Python/3.8.3/x64/lib/libpython3.8.dylib
  Referenced from: /Users/sanzgiri/actions-runner/_work/_tool/Python/3.8.3/x64/bin/./python
  Reason: image not found
##[error]./setup.sh: line 53:  9822 Abort trap: 6           ./python -m ensurepip
##[error]The process '/bin/bash' failed with exit code 134
  install dependencies`

How can I resolve this?

**Comment by sanzgiri** [comment]
Finally was able to resolve this. Traced it to openssl on the Mac. Had to downgrade it to 1.0.2t.

**Comment by bldrvnlw** [comment]
@sanzgiri I followed your tip to downgrade openssl to 1.0.2t but am still getting the error your posted on Jul 26. Did you do anything else?

```
Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
Upgrading PIP...
Error: dyld: Library not loaded: /Users/runner/hostedtoolcache/Python/3.7.7/x64/lib/libpython3.7m.dylib
  Referenced from: /Users/bvanlew/actions-runner/_work/_tool/Python/3.7.7/x64/bin/./python
  Reason: image not found
Error: ./setup.sh: line 53: 44389 Abort trap: 6           ./python -m ensurepip
Error: The process '/bin/bash' failed with exit code 134`
```

**Comment by bldrvnlw** [comment]
I found the[ solution is documented](https://github.com/actions/setup-python#mac) in the setup-python readme
