### ISSUE TITLE
More recent versions of Python 3.8, 3.9 and 3.10

### ISSUE THREAD

**Issue by joerivanruth** [actions/setup-python#978]
**Description:**
Please provide more recent versions of Python 3.8, 3.9 and 3.10.

|    | 3.8 | 3.9 | 3.10 |
|----|----|----|----|
| Version installed as of 2024-12-04 | 3.8.10 | 3.9.13 | 3.10.11 |
| Requested version at least | 3.8.17 | 3.9.17 | 3.10.12 |

**Justification:**
In versions 3.8.17, 3.9.17 and 3.10.12, the function `shutil.unpack_archive()` gained an optional keyword argument `filter=`. For security reasons it is nowadays strongly recommended to set this explicitly. It would be very useful if scripts that use `unpack_archive` can just pass this parameter without having to check which Python version they are using.

**Are you willing to submit a PR?**
I would like to but I don't know how. Also, you wouldn't and shouldn't trust the Python binaries if I compiled them.

**Comment by priya-kinthali** [comment]
Hello @joerivanruth 👋,
Thank you for this feature request. We will investigate it and get back to you as soon as we have some feedback.

**Comment by gowridurgad** [comment]
Hi @joerivanruth, For Ubuntu and macos, we are getting the latest Python versions as the images are updated with the latest toolcache versions, which can be seen here ( [ubuntu](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md), [macos](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#python) ). However, for Windows runner image, the latest versions of Python 3.8, 3.9, and 3.10 are not available, as shown [here](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#python) .  If you need these versions to be updated to the latest, please raise an issue in the  [runner images repository](https://github.com/actions/runner-images).

**Comment by gowridurgad** [comment]
Hi @joerivanruth, As this feature request is not related to setup-python, we will be closing it. If you have any further questions or need additional assistance, please feel free to reach out to us.
Thank you!
