### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by theflexstore** [actions/setup-python#980]
**Description:**

**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Comment by mahabaleshwars** [comment]
Hello @theflexstore ,
Since this appears to be spam, I am going to close the issue.
