### ISSUE TITLE
Add Python 3.13.1

### ISSUE THREAD

**Issue by lysnikolaou** [actions/setup-python#986]
**Description:**
The bugfix release 3.13.1 was released on Dec 3rd. Could we please add support for it and have the `3.13` target install 3.13.1 instead of 3.13.0?

**Justification:**
When using a `<major>.<minor>` target, the latest bugfix release should be installed.

**Are you willing to submit a PR?**
As far as I understand, no PR is needed, just a `workflow_call` on the actions/python-versions repo.

**Comment by gowridurgad** [comment]
Hello @lysnikolaou,
Thank you for this feature request. We will investigate it and get back to you as soon as we have some feedback.

**Comment by priyagupta108** [comment]
Hi @lysnikolaou 👋,
The release for Python 3.13.1 is already available in `actions/python-versions` : [Python 3.13.1 Release](https://github.com/actions/python-versions/releases/tag/3.13.1-12154081405).
The requested feature is functioning as expected. I have tested the setup, and it installs Python 3.13.1 correctly when targeting Python 3.13. Please see the screenshot below:<br/>
<img width="553" alt="Screenshot 2024-12-18 at 2 48 52 PM" src="https://github.com/user-attachments/assets/f0f3448b-2df6-4390-9511-212dc62207fc" />


Additionally, to ensure you are always getting the latest patch version, you can use `check-latest: true` input in your workflow configuration. Find out about `check-latest` [here](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#check-latest-version).

If you are still not getting the correct version, please provide the run link for further investigation.

Thank you!

**Comment by lysnikolaou** [comment]
Thanks @priyagupta108! I think this can be closed now.
